// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const flipOverdueSchedules = `-- name: FlipOverdueSchedules :many

UPDATE payment_schedules s
SET status = 'overdue'
FROM orgs o
WHERE o.id = s.org_id
  AND s.status IN ('pending', 'partial')
  AND s.deleted_at IS NULL
  AND s.due_date + COALESCE((o.settings ->> 'grace_days')::int, 0) < CURRENT_DATE
  AND ($1::uuid IS NULL OR s.org_id = $1::uuid)
RETURNING s.id, s.org_id
`

type FlipOverdueSchedulesRow struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

// The overdue sweep (internal/payment.FlipOverdue) is a platform-wide job: a
// due date is the same fact in every org. Like the other admin_* files it may
// cross orgs and is exempt from the org_id repository guard — but it takes an
// optional org_id so the org-scoped reads (GET /schedules, GET /me/schedules)
// can run it for just their own tenant before answering (API.md Phase 5).
//
// The grace period comes from each org's own settings, so the statement joins
// orgs rather than taking one number for the whole platform. It is idempotent:
// it selects only the statuses it is moving away from.
func (q *Queries) FlipOverdueSchedules(ctx context.Context, orgID pgtype.UUID) ([]FlipOverdueSchedulesRow, error) {
	rows, err := q.db.Query(ctx, flipOverdueSchedules, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlipOverdueSchedulesRow{}
	for rows.Next() {
		var i FlipOverdueSchedulesRow
		if err := rows.Scan(&i.ID, &i.OrgID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
