// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_orgs.sql

package sqlc

import (
	"context"
)

const adminCountOrgs = `-- name: AdminCountOrgs :one
SELECT count(*) FROM orgs WHERE deleted_at IS NULL
`

func (q *Queries) AdminCountOrgs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountOrgs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminListOrgs = `-- name: AdminListOrgs :many

SELECT id, name, slug, status, settings, created_at, updated_at, deleted_at, suspended_at, suspended_reason FROM orgs
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1
`

// Platform-admin queries. Files named admin_*.sql are exempt from the
// org-scope guard (see internal/db/orgscope_guard_test.go): these endpoints
// deliberately cross orgs and are reachable only behind auth.RequireAdmin.
func (q *Queries) AdminListOrgs(ctx context.Context, rowLimit int32) ([]Org, error) {
	rows, err := q.db.Query(ctx, adminListOrgs, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Org{}
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SuspendedAt,
			&i.SuspendedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
