// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_platform.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminActivateOrg = `-- name: AdminActivateOrg :one
UPDATE orgs
SET status = 'active', suspended_at = NULL, suspended_reason = NULL
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, status, settings, created_at, updated_at, deleted_at, suspended_at, suspended_reason
`

func (q *Queries) AdminActivateOrg(ctx context.Context, id pgtype.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, adminActivateOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuspendedAt,
		&i.SuspendedReason,
	)
	return i, err
}

const adminGetOrgStatus = `-- name: AdminGetOrgStatus :one
SELECT status FROM orgs WHERE id = $1 AND deleted_at IS NULL
`

// AdminGetOrgStatus is the suspension check RequireOrg runs when the Redis flag
// is cold: one primary-key lookup, cached for a few minutes afterwards.
func (q *Queries) AdminGetOrgStatus(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, adminGetOrgStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const adminJobLastRuns = `-- name: AdminJobLastRuns :many
SELECT DISTINCT ON (a.action) a.action, a.at, a.after
FROM audit_log a
WHERE a.action = ANY ($1::text[])
ORDER BY a.action, a.at DESC, a.id DESC
`

type AdminJobLastRunsRow struct {
	Action string             `json:"action"`
	At     pgtype.Timestamptz `json:"at"`
	After  []byte             `json:"after"`
}

// AdminJobLastRuns answers GET /admin/jobs from the audit rows the jobs already
// write, rather than from a second `job_runs` table that could disagree with
// them (DECISIONS.md).
func (q *Queries) AdminJobLastRuns(ctx context.Context, actions []string) ([]AdminJobLastRunsRow, error) {
	rows, err := q.db.Query(ctx, adminJobLastRuns, actions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminJobLastRunsRow{}
	for rows.Next() {
		var i AdminJobLastRunsRow
		if err := rows.Scan(&i.Action, &i.At, &i.After); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListAuditLog = `-- name: AdminListAuditLog :many
SELECT a.id, a.org_id, a.actor_user_id, a.action, a.entity_type, a.entity_id,
       a.before, a.after, a.ip, a.user_agent, a.at,
       u.full_name AS actor_name,
       COALESCE(o.name, '')::text AS org_name
FROM audit_log a
LEFT JOIN users u ON u.id = a.actor_user_id
LEFT JOIN orgs o  ON o.id = a.org_id
WHERE ($1::uuid IS NULL OR a.org_id = $1::uuid)
  AND ($2::uuid IS NULL OR a.actor_user_id = $2::uuid)
  AND ($3::text IS NULL OR a.entity_type = $3::text)
  AND ($4::uuid IS NULL OR a.entity_id = $4::uuid)
  AND ($5::text IS NULL
       OR a.action ILIKE '%' || $5::text || '%'
       OR a.entity_type ILIKE '%' || $5::text || '%')
  AND ($6::timestamptz IS NULL OR a.at >= $6::timestamptz)
  AND ($7::timestamptz IS NULL OR a.at <= $7::timestamptz)
  AND ($8::timestamptz IS NULL
       OR (a.at, a.id) < ($8::timestamptz, $9::uuid))
ORDER BY a.at DESC, a.id DESC
LIMIT $10
`

type AdminListAuditLogParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	EntityType  *string            `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Q           *string            `json:"q"`
	FromAt      pgtype.Timestamptz `json:"from_at"`
	ToAt        pgtype.Timestamptz `json:"to_at"`
	CursorAt    pgtype.Timestamptz `json:"cursor_at"`
	CursorID    pgtype.UUID        `json:"cursor_id"`
	RowLimit    int32              `json:"row_limit"`
}

type AdminListAuditLogRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Before      []byte             `json:"before"`
	After       []byte             `json:"after"`
	Ip          *string            `json:"ip"`
	UserAgent   *string            `json:"user_agent"`
	At          pgtype.Timestamptz `json:"at"`
	ActorName   *string            `json:"actor_name"`
	OrgName     string             `json:"org_name"`
}

// AdminListAuditLog is the cross-org audit search. `q` is a case-insensitive
// substring of the action or the entity type — the two fields an operator
// actually remembers ("suspend", "payment", "contract").
func (q *Queries) AdminListAuditLog(ctx context.Context, arg AdminListAuditLogParams) ([]AdminListAuditLogRow, error) {
	rows, err := q.db.Query(ctx, adminListAuditLog,
		arg.OrgID,
		arg.ActorUserID,
		arg.EntityType,
		arg.EntityID,
		arg.Q,
		arg.FromAt,
		arg.ToAt,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAuditLogRow{}
	for rows.Next() {
		var i AdminListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.UserAgent,
			&i.At,
			&i.ActorName,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOrgMembers = `-- name: AdminListOrgMembers :many
SELECT m.id, m.user_id, m.role, m.status, m.created_at,
       u.full_name, u.email
FROM org_members m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1 AND m.deleted_at IS NULL
ORDER BY m.created_at, m.id
`

type AdminListOrgMembersRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	FullName  string             `json:"full_name"`
	Email     *string            `json:"email"`
}

func (q *Queries) AdminListOrgMembers(ctx context.Context, orgID pgtype.UUID) ([]AdminListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, adminListOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListOrgMembersRow{}
	for rows.Next() {
		var i AdminListOrgMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.FullName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOrgsPage = `-- name: AdminListOrgsPage :many

SELECT o.id, o.name, o.slug, o.status, o.created_at, o.suspended_at, o.suspended_reason,
       COALESCE((SELECT ou.full_name FROM org_members m
                 JOIN users ou ON ou.id = m.user_id
                 WHERE m.org_id = o.id AND m.role = 'org_owner' AND m.deleted_at IS NULL
                 ORDER BY m.created_at, m.id LIMIT 1), '')::text AS owner_name,
       COALESCE((SELECT ou2.email FROM org_members m2
                 JOIN users ou2 ON ou2.id = m2.user_id
                 WHERE m2.org_id = o.id AND m2.role = 'org_owner' AND m2.deleted_at IS NULL
                 ORDER BY m2.created_at, m2.id LIMIT 1), '')::text AS owner_email,
       (SELECT count(*) FROM properties p
        WHERE p.org_id = o.id AND p.deleted_at IS NULL)::bigint AS properties,
       (SELECT count(*) FROM units u
        WHERE u.org_id = o.id AND u.deleted_at IS NULL)::bigint AS units,
       (SELECT count(DISTINCT c.renter_user_id) FROM contracts c
        WHERE c.org_id = o.id AND c.deleted_at IS NULL
          AND c.status IN ('active', 'expiring'))::bigint AS renters,
       (SELECT count(*) FROM contracts c2
        WHERE c2.org_id = o.id AND c2.deleted_at IS NULL
          AND c2.status IN ('active', 'expiring'))::bigint AS active_contracts,
       (SELECT count(*) FROM notification_log n
        WHERE n.org_id = o.id AND n.status = 'sent'
          AND n.created_at >= now() - INTERVAL '30 days')::bigint AS sms_sent_30d,
       (SELECT count(*) FROM notification_log n2
        WHERE n2.org_id = o.id AND n2.status = 'failed'
          AND n2.created_at >= now() - INTERVAL '30 days')::bigint AS sms_failed_30d
FROM orgs o
WHERE o.deleted_at IS NULL
  AND ($1::text IS NULL OR o.status = $1::text)
  AND ($2::text IS NULL
       OR o.name ILIKE '%' || $2::text || '%'
       OR o.slug ILIKE '%' || $2::text || '%')
  AND ($3::uuid IS NULL OR o.id = $3::uuid)
  AND ($4::timestamptz IS NULL
       OR (o.created_at, o.id) < ($4::timestamptz, $5::uuid))
ORDER BY o.created_at DESC, o.id DESC
LIMIT $6
`

type AdminListOrgsPageParams struct {
	Status   *string            `json:"status"`
	Q        *string            `json:"q"`
	OrgID    pgtype.UUID        `json:"org_id"`
	CursorAt pgtype.Timestamptz `json:"cursor_at"`
	CursorID pgtype.UUID        `json:"cursor_id"`
	RowLimit int32              `json:"row_limit"`
}

type AdminListOrgsPageRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	SuspendedAt     pgtype.Timestamptz `json:"suspended_at"`
	SuspendedReason *string            `json:"suspended_reason"`
	OwnerName       string             `json:"owner_name"`
	OwnerEmail      string             `json:"owner_email"`
	Properties      int64              `json:"properties"`
	Units           int64              `json:"units"`
	Renters         int64              `json:"renters"`
	ActiveContracts int64              `json:"active_contracts"`
	SmsSent30d      int64              `json:"sms_sent_30d"`
	SmsFailed30d    int64              `json:"sms_failed_30d"`
}

// Phase 7 platform-admin queries (SPEC §5.10, API.md Phase 7). Files named
// admin_*.sql are exempt from the org-scope guard: these statements cross orgs
// by design and are reachable only behind auth.RequireAdmin (`tms_a`).
// AdminListOrgsPage is the admin org list: one row per tenant with the owner,
// the four headline counts and 30-day SMS volume — all as correlated
// aggregates, so a hundred orgs is still one round trip.
func (q *Queries) AdminListOrgsPage(ctx context.Context, arg AdminListOrgsPageParams) ([]AdminListOrgsPageRow, error) {
	rows, err := q.db.Query(ctx, adminListOrgsPage,
		arg.Status,
		arg.Q,
		arg.OrgID,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListOrgsPageRow{}
	for rows.Next() {
		var i AdminListOrgsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.SuspendedAt,
			&i.SuspendedReason,
			&i.OwnerName,
			&i.OwnerEmail,
			&i.Properties,
			&i.Units,
			&i.Renters,
			&i.ActiveContracts,
			&i.SmsSent30d,
			&i.SmsFailed30d,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminMetrics = `-- name: AdminMetrics :one
SELECT
    (SELECT count(*) FROM orgs WHERE deleted_at IS NULL)::bigint AS orgs_total,
    (SELECT count(*) FROM orgs WHERE deleted_at IS NULL AND status = 'active')::bigint AS orgs_active,
    (SELECT count(*) FROM orgs WHERE deleted_at IS NULL AND status = 'suspended')::bigint AS orgs_suspended,
    (SELECT count(*) FROM users WHERE deleted_at IS NULL AND kind = 'renter')::bigint AS renters_total,
    (SELECT count(*) FROM units WHERE deleted_at IS NULL)::bigint AS units_total,
    (SELECT count(*) FROM units WHERE deleted_at IS NULL AND status = 'occupied')::bigint AS units_occupied,
    (SELECT count(*) FROM contracts WHERE deleted_at IS NULL
      AND status IN ('active', 'expiring'))::bigint AS contracts_active,
    (SELECT count(*) FROM notification_log WHERE status = 'sent'
      AND created_at >= now() - INTERVAL '24 hours')::bigint AS sms_sent_24h,
    (SELECT count(*) FROM notification_log WHERE status = 'failed'
      AND created_at >= now() - INTERVAL '24 hours')::bigint AS sms_failed_24h,
    (SELECT count(*) FROM notification_log
      WHERE status IN ('queued', 'sending'))::bigint AS sms_queued,
    (SELECT count(*) FROM payments WHERE deleted_at IS NULL AND status <> 'reversed'
      AND paid_at >= now() - INTERVAL '30 days')::bigint AS payments_recorded_30d,
    (SELECT COALESCE(sum(amount), 0) FROM payments WHERE deleted_at IS NULL AND status <> 'reversed'
      AND paid_at >= now() - INTERVAL '30 days')::bigint AS payments_amount_30d
`

type AdminMetricsRow struct {
	OrgsTotal           int64 `json:"orgs_total"`
	OrgsActive          int64 `json:"orgs_active"`
	OrgsSuspended       int64 `json:"orgs_suspended"`
	RentersTotal        int64 `json:"renters_total"`
	UnitsTotal          int64 `json:"units_total"`
	UnitsOccupied       int64 `json:"units_occupied"`
	ContractsActive     int64 `json:"contracts_active"`
	SmsSent24h          int64 `json:"sms_sent_24h"`
	SmsFailed24h        int64 `json:"sms_failed_24h"`
	SmsQueued           int64 `json:"sms_queued"`
	PaymentsRecorded30d int64 `json:"payments_recorded_30d"`
	PaymentsAmount30d   int64 `json:"payments_amount_30d"`
}

// AdminMetrics is the platform health panel: every counter in one statement,
// because the admin dashboard polls it.
func (q *Queries) AdminMetrics(ctx context.Context) (AdminMetricsRow, error) {
	row := q.db.QueryRow(ctx, adminMetrics)
	var i AdminMetricsRow
	err := row.Scan(
		&i.OrgsTotal,
		&i.OrgsActive,
		&i.OrgsSuspended,
		&i.RentersTotal,
		&i.UnitsTotal,
		&i.UnitsOccupied,
		&i.ContractsActive,
		&i.SmsSent24h,
		&i.SmsFailed24h,
		&i.SmsQueued,
		&i.PaymentsRecorded30d,
		&i.PaymentsAmount30d,
	)
	return i, err
}

const adminSMSMetrics = `-- name: AdminSMSMetrics :one
SELECT
    (SELECT COALESCE(-sum(delta), 0) FROM sms_credit_ledger
      WHERE reason = 'debit' AND created_at >= date_trunc('day', now()))::bigint
      AS credits_used_today,
    (SELECT count(*) FROM org_sms_credits c
      JOIN orgs o ON o.id = c.org_id AND o.deleted_at IS NULL
      WHERE c.balance < c.low_watermark)::bigint AS orgs_under_watermark,
    (SELECT count(*) FROM notification_log
      WHERE status = 'held_no_credit')::bigint AS held_total
`

type AdminSMSMetricsRow struct {
	CreditsUsedToday   int64 `json:"credits_used_today"`
	OrgsUnderWatermark int64 `json:"orgs_under_watermark"`
	HeldTotal          int64 `json:"held_total"`
}

// AdminSMSMetrics is the Phase 14 block of GET /admin/metrics: what the
// platform's orgs have spent today, how many are under their own watermark,
// and how much mail is held for want of credit.
func (q *Queries) AdminSMSMetrics(ctx context.Context) (AdminSMSMetricsRow, error) {
	row := q.db.QueryRow(ctx, adminSMSMetrics)
	var i AdminSMSMetricsRow
	err := row.Scan(&i.CreditsUsedToday, &i.OrgsUnderWatermark, &i.HeldTotal)
	return i, err
}

const adminSuspendOrg = `-- name: AdminSuspendOrg :one
UPDATE orgs
SET status = 'suspended', suspended_at = now(), suspended_reason = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, name, slug, status, settings, created_at, updated_at, deleted_at, suspended_at, suspended_reason
`

type AdminSuspendOrgParams struct {
	Reason *string     `json:"reason"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) AdminSuspendOrg(ctx context.Context, arg AdminSuspendOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, adminSuspendOrg, arg.Reason, arg.ID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuspendedAt,
		&i.SuspendedReason,
	)
	return i, err
}
