// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_contract_lifecycle.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const endLapsedContracts = `-- name: EndLapsedContracts :many
UPDATE contracts
SET status = 'ended'
WHERE status IN ('active', 'expiring') AND deleted_at IS NULL
  AND end_date <= CURRENT_DATE
RETURNING id, org_id, unit_id
`

type EndLapsedContractsRow struct {
	ID     pgtype.UUID `json:"id"`
	OrgID  pgtype.UUID `json:"org_id"`
	UnitID pgtype.UUID `json:"unit_id"`
}

func (q *Queries) EndLapsedContracts(ctx context.Context) ([]EndLapsedContractsRow, error) {
	rows, err := q.db.Query(ctx, endLapsedContracts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EndLapsedContractsRow{}
	for rows.Next() {
		var i EndLapsedContractsRow
		if err := rows.Scan(&i.ID, &i.OrgID, &i.UnitID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const flagExpiringContracts = `-- name: FlagExpiringContracts :many

UPDATE contracts
SET status = 'expiring'
WHERE status = 'active' AND deleted_at IS NULL
  AND end_date - $1::int <= CURRENT_DATE
  AND end_date > CURRENT_DATE
RETURNING id, org_id, unit_id
`

type FlagExpiringContractsRow struct {
	ID     pgtype.UUID `json:"id"`
	OrgID  pgtype.UUID `json:"org_id"`
	UnitID pgtype.UUID `json:"unit_id"`
}

// The contract lifecycle job (internal/contract.RunLifecycle) is a platform-wide
// sweep: it flags contracts approaching their end date and closes the ones past
// it, across every org. Like the other admin_* files it crosses orgs by design
// and is exempt from the org_id repository guard.
//
// Both statements are idempotent — they select on the status they are moving
// away from — so running the job twice in one hour changes nothing the second
// time, and an on-demand run from POST /admin/jobs/contract-lifecycle is safe.
func (q *Queries) FlagExpiringContracts(ctx context.Context, noticeDays int32) ([]FlagExpiringContractsRow, error) {
	rows, err := q.db.Query(ctx, flagExpiringContracts, noticeDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FlagExpiringContractsRow{}
	for rows.Next() {
		var i FlagExpiringContractsRow
		if err := rows.Scan(&i.ID, &i.OrgID, &i.UnitID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const freeUnitsWithoutLiveContract = `-- name: FreeUnitsWithoutLiveContract :many
UPDATE units
SET status = 'vacant', status_override = false
WHERE id = ANY ($1::uuid[])
  AND status <> 'vacant' AND deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM contracts c
      WHERE c.unit_id = units.id AND c.deleted_at IS NULL
        AND c.status IN ('pending_signature', 'active', 'expiring')
  )
RETURNING id
`

// FreeUnitsWithoutLiveContract flips a unit back to vacant once nothing runs on
// it, clearing the landlord's override with it: a tenancy that has ended must
// put the unit back on the vacancy board (FLOWS 4.2).
func (q *Queries) FreeUnitsWithoutLiveContract(ctx context.Context, unitIds []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, freeUnitsWithoutLiveContract, unitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
