// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assist_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeAssistSession = `-- name: CloseAssistSession :one
UPDATE assist_sessions
SET status = 'closed', closed_at = COALESCE(closed_at, now())
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, unit_id, phone, purpose, started_by_user_id, renter_user_id, link_request_id, status, code_issued_count, last_code_at, expires_at, closed_at, created_at, updated_at
`

type CloseAssistSessionParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) CloseAssistSession(ctx context.Context, arg CloseAssistSessionParams) (AssistSession, error) {
	row := q.db.QueryRow(ctx, closeAssistSession, arg.OrgID, arg.ID)
	var i AssistSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.Phone,
		&i.Purpose,
		&i.StartedByUserID,
		&i.RenterUserID,
		&i.LinkRequestID,
		&i.Status,
		&i.CodeIssuedCount,
		&i.LastCodeAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssistSession = `-- name: CreateAssistSession :one

INSERT INTO assist_sessions (
    org_id, unit_id, phone, purpose, started_by_user_id,
    code_issued_count, last_code_at, expires_at
)
VALUES (
    $1, $2, $3, $4,
    $5, 1, now(), $6
)
RETURNING id, org_id, unit_id, phone, purpose, started_by_user_id, renter_user_id, link_request_id, status, code_issued_count, last_code_at, expires_at, closed_at, created_at, updated_at
`

type CreateAssistSessionParams struct {
	OrgID           pgtype.UUID        `json:"org_id"`
	UnitID          pgtype.UUID        `json:"unit_id"`
	Phone           string             `json:"phone"`
	Purpose         string             `json:"purpose"`
	StartedByUserID pgtype.UUID        `json:"started_by_user_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

// assist_sessions is the durable shape of a landlord-assisted onboarding
// (Phase 18, SPEC §5.15, FLOWS 2b). The code itself is never here — it lives
// only in the Redis slot the SMS path writes — so these queries move the
// session's status and its stamps, nothing else.
func (q *Queries) CreateAssistSession(ctx context.Context, arg CreateAssistSessionParams) (AssistSession, error) {
	row := q.db.QueryRow(ctx, createAssistSession,
		arg.OrgID,
		arg.UnitID,
		arg.Phone,
		arg.Purpose,
		arg.StartedByUserID,
		arg.ExpiresAt,
	)
	var i AssistSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.Phone,
		&i.Purpose,
		&i.StartedByUserID,
		&i.RenterUserID,
		&i.LinkRequestID,
		&i.Status,
		&i.CodeIssuedCount,
		&i.LastCodeAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOpenAssistSessionByPhone = `-- name: FindOpenAssistSessionByPhone :one
SELECT id, org_id, unit_id, phone, purpose, started_by_user_id, renter_user_id, link_request_id, status, code_issued_count, last_code_at, expires_at, closed_at, created_at, updated_at FROM assist_sessions
WHERE org_id = $1 AND phone = $2
  AND status = 'open' AND expires_at > now()
`

type FindOpenAssistSessionByPhoneParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Phone string      `json:"phone"`
}

// FindOpenAssistSessionByPhone is the 409 `assist_open` check: one open
// session per (org, phone), which the partial unique index enforces and this
// read turns into a useful answer (the id of the session already running).
func (q *Queries) FindOpenAssistSessionByPhone(ctx context.Context, arg FindOpenAssistSessionByPhoneParams) (AssistSession, error) {
	row := q.db.QueryRow(ctx, findOpenAssistSessionByPhone, arg.OrgID, arg.Phone)
	var i AssistSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.Phone,
		&i.Purpose,
		&i.StartedByUserID,
		&i.RenterUserID,
		&i.LinkRequestID,
		&i.Status,
		&i.CodeIssuedCount,
		&i.LastCodeAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOpenAssistSessionForLink = `-- name: FindOpenAssistSessionForLink :one
SELECT id, org_id, unit_id, phone, purpose, started_by_user_id, renter_user_id, link_request_id, status, code_issued_count, last_code_at, expires_at, closed_at, created_at, updated_at FROM assist_sessions
WHERE org_id = $1 AND unit_id = $2
  AND status = 'open' AND expires_at > now()
  AND (renter_user_id = $3 OR phone = $4)
ORDER BY created_at DESC
LIMIT 1
`

type FindOpenAssistSessionForLinkParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	UnitID       pgtype.UUID `json:"unit_id"`
	RenterUserID pgtype.UUID `json:"renter_user_id"`
	Phone        string      `json:"phone"`
}

// FindOpenAssistSessionForLink finds the session a link request belongs to:
// same org, same unit, and the renter who just applied — matched on the
// account when the session already knows it, else on the phone they verified.
func (q *Queries) FindOpenAssistSessionForLink(ctx context.Context, arg FindOpenAssistSessionForLinkParams) (AssistSession, error) {
	row := q.db.QueryRow(ctx, findOpenAssistSessionForLink,
		arg.OrgID,
		arg.UnitID,
		arg.RenterUserID,
		arg.Phone,
	)
	var i AssistSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.Phone,
		&i.Purpose,
		&i.StartedByUserID,
		&i.RenterUserID,
		&i.LinkRequestID,
		&i.Status,
		&i.CodeIssuedCount,
		&i.LastCodeAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssistSession = `-- name: GetAssistSession :one
SELECT s.id, s.org_id, s.unit_id, s.phone, s.purpose, s.started_by_user_id, s.renter_user_id, s.link_request_id, s.status, s.code_issued_count, s.last_code_at, s.expires_at, s.closed_at, s.created_at, s.updated_at,
       u.unit_code                          AS unit_code,
       u.name                               AS unit_name,
       COALESCE(r.full_name, '')::text      AS renter_name,
       COALESCE(lr.status,   '')::text      AS link_request_status
FROM assist_sessions s
JOIN units u ON u.id = s.unit_id
LEFT JOIN users r ON r.id = s.renter_user_id
LEFT JOIN unit_link_requests lr ON lr.id = s.link_request_id
WHERE s.org_id = $1 AND s.id = $2
`

type GetAssistSessionParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetAssistSessionRow struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             pgtype.UUID        `json:"org_id"`
	UnitID            pgtype.UUID        `json:"unit_id"`
	Phone             string             `json:"phone"`
	Purpose           string             `json:"purpose"`
	StartedByUserID   pgtype.UUID        `json:"started_by_user_id"`
	RenterUserID      pgtype.UUID        `json:"renter_user_id"`
	LinkRequestID     pgtype.UUID        `json:"link_request_id"`
	Status            string             `json:"status"`
	CodeIssuedCount   int32              `json:"code_issued_count"`
	LastCodeAt        pgtype.Timestamptz `json:"last_code_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UnitCode          string             `json:"unit_code"`
	UnitName          string             `json:"unit_name"`
	RenterName        string             `json:"renter_name"`
	LinkRequestStatus string             `json:"link_request_status"`
}

func (q *Queries) GetAssistSession(ctx context.Context, arg GetAssistSessionParams) (GetAssistSessionRow, error) {
	row := q.db.QueryRow(ctx, getAssistSession, arg.OrgID, arg.ID)
	var i GetAssistSessionRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.Phone,
		&i.Purpose,
		&i.StartedByUserID,
		&i.RenterUserID,
		&i.LinkRequestID,
		&i.Status,
		&i.CodeIssuedCount,
		&i.LastCodeAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnitCode,
		&i.UnitName,
		&i.RenterName,
		&i.LinkRequestStatus,
	)
	return i, err
}

const getPublicAssistSession = `-- name: GetPublicAssistSession :one
SELECT s.id, s.purpose, s.status, s.expires_at, u.unit_code
FROM assist_sessions s
JOIN units u ON u.id = s.unit_id
WHERE s.id = $1
`

type GetPublicAssistSessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	Purpose   string             `json:"purpose"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UnitCode  string             `json:"unit_code"`
}

// GetPublicAssistSession backs GET /public/assist/{id}: the renter's own
// device has the session id from the QR and nothing else, so the answer is the
// unit code and the purpose — never the phone, never the org's rows.
//
// guard-exempt: unauthenticated lookup by an unguessable session id; the
// projection is the unit code and purpose alone (SPEC §5.15).
func (q *Queries) GetPublicAssistSession(ctx context.Context, id pgtype.UUID) (GetPublicAssistSessionRow, error) {
	row := q.db.QueryRow(ctx, getPublicAssistSession, id)
	var i GetPublicAssistSessionRow
	err := row.Scan(
		&i.ID,
		&i.Purpose,
		&i.Status,
		&i.ExpiresAt,
		&i.UnitCode,
	)
	return i, err
}

const issueAssistCode = `-- name: IssueAssistCode :one
UPDATE assist_sessions
SET code_issued_count = code_issued_count + 1,
    last_code_at      = now(),
    expires_at        = $1
WHERE org_id = $2 AND id = $3
  AND status = 'open' AND expires_at > now()
RETURNING id, org_id, unit_id, phone, purpose, started_by_user_id, renter_user_id, link_request_id, status, code_issued_count, last_code_at, expires_at, closed_at, created_at, updated_at
`

type IssueAssistCodeParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	OrgID     pgtype.UUID        `json:"org_id"`
	ID        pgtype.UUID        `json:"id"`
}

// IssueAssistCode records one reveal: the count the per-session cap reads, the
// timestamp, and the 30-minute window pushed out again. It refuses a closed or
// expired session in the same statement, so the cap cannot be raced.
func (q *Queries) IssueAssistCode(ctx context.Context, arg IssueAssistCodeParams) (AssistSession, error) {
	row := q.db.QueryRow(ctx, issueAssistCode, arg.ExpiresAt, arg.OrgID, arg.ID)
	var i AssistSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.Phone,
		&i.Purpose,
		&i.StartedByUserID,
		&i.RenterUserID,
		&i.LinkRequestID,
		&i.Status,
		&i.CodeIssuedCount,
		&i.LastCodeAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOpenAssistSessions = `-- name: ListOpenAssistSessions :many
SELECT s.id, s.org_id, s.unit_id, s.phone, s.purpose, s.started_by_user_id, s.renter_user_id, s.link_request_id, s.status, s.code_issued_count, s.last_code_at, s.expires_at, s.closed_at, s.created_at, s.updated_at,
       u.unit_code                          AS unit_code,
       u.name                               AS unit_name,
       COALESCE(r.full_name, '')::text      AS renter_name,
       COALESCE(lr.status,   '')::text      AS link_request_status
FROM assist_sessions s
JOIN units u ON u.id = s.unit_id
LEFT JOIN users r ON r.id = s.renter_user_id
LEFT JOIN unit_link_requests lr ON lr.id = s.link_request_id
WHERE s.org_id = $1 AND s.status = 'open' AND s.expires_at > now()
ORDER BY s.created_at DESC, s.id DESC
LIMIT $2
`

type ListOpenAssistSessionsParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	RowLimit int32       `json:"row_limit"`
}

type ListOpenAssistSessionsRow struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             pgtype.UUID        `json:"org_id"`
	UnitID            pgtype.UUID        `json:"unit_id"`
	Phone             string             `json:"phone"`
	Purpose           string             `json:"purpose"`
	StartedByUserID   pgtype.UUID        `json:"started_by_user_id"`
	RenterUserID      pgtype.UUID        `json:"renter_user_id"`
	LinkRequestID     pgtype.UUID        `json:"link_request_id"`
	Status            string             `json:"status"`
	CodeIssuedCount   int32              `json:"code_issued_count"`
	LastCodeAt        pgtype.Timestamptz `json:"last_code_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UnitCode          string             `json:"unit_code"`
	UnitName          string             `json:"unit_name"`
	RenterName        string             `json:"renter_name"`
	LinkRequestStatus string             `json:"link_request_status"`
}

// ListOpenAssistSessions is the landlord's screen: the org's sessions that are
// still live, newest first. An expired row is closed in every sense but the
// column, so the expiry is part of the filter rather than left to a sweep.
func (q *Queries) ListOpenAssistSessions(ctx context.Context, arg ListOpenAssistSessionsParams) ([]ListOpenAssistSessionsRow, error) {
	rows, err := q.db.Query(ctx, listOpenAssistSessions, arg.OrgID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenAssistSessionsRow{}
	for rows.Next() {
		var i ListOpenAssistSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UnitID,
			&i.Phone,
			&i.Purpose,
			&i.StartedByUserID,
			&i.RenterUserID,
			&i.LinkRequestID,
			&i.Status,
			&i.CodeIssuedCount,
			&i.LastCodeAt,
			&i.ExpiresAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitCode,
			&i.UnitName,
			&i.RenterName,
			&i.LinkRequestStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stampAssistLinkRequest = `-- name: StampAssistLinkRequest :exec
UPDATE assist_sessions
SET link_request_id = $1,
    renter_user_id  = COALESCE(renter_user_id, $2)
WHERE org_id = $3 AND id = $4 AND status = 'open'
`

type StampAssistLinkRequestParams struct {
	LinkRequestID pgtype.UUID `json:"link_request_id"`
	RenterUserID  pgtype.UUID `json:"renter_user_id"`
	OrgID         pgtype.UUID `json:"org_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) StampAssistLinkRequest(ctx context.Context, arg StampAssistLinkRequestParams) error {
	_, err := q.db.Exec(ctx, stampAssistLinkRequest,
		arg.LinkRequestID,
		arg.RenterUserID,
		arg.OrgID,
		arg.ID,
	)
	return err
}

const stampAssistRenter = `-- name: StampAssistRenter :exec
UPDATE assist_sessions SET renter_user_id = $1
WHERE id = $2 AND status = 'open'
`

type StampAssistRenterParams struct {
	RenterUserID pgtype.UUID `json:"renter_user_id"`
	ID           pgtype.UUID `json:"id"`
}

// StampAssistRenter attaches the account the renter created (or logged into)
// to the session the landlord opened for their number.
//
// guard-exempt: the hook runs on POST /auth/otp/verify and POST /auth/register/renter,
// which have no org context at all — the session id came from the Redis marker
// the assisted issue wrote, which is itself org-scoped.
func (q *Queries) StampAssistRenter(ctx context.Context, arg StampAssistRenterParams) error {
	_, err := q.db.Exec(ctx, stampAssistRenter, arg.RenterUserID, arg.ID)
	return err
}
