// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditLogEntry = `-- name: GetAuditLogEntry :one
SELECT a.id, a.org_id, a.actor_user_id, a.action, a.entity_type, a.entity_id,
       a.before, a.after, a.ip, a.user_agent, a.at,
       u.full_name AS actor_name
FROM audit_log a
LEFT JOIN users u ON u.id = a.actor_user_id
WHERE a.org_id = $1 AND a.id = $2
`

type GetAuditLogEntryParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetAuditLogEntryRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Before      []byte             `json:"before"`
	After       []byte             `json:"after"`
	Ip          *string            `json:"ip"`
	UserAgent   *string            `json:"user_agent"`
	At          pgtype.Timestamptz `json:"at"`
	ActorName   *string            `json:"actor_name"`
}

func (q *Queries) GetAuditLogEntry(ctx context.Context, arg GetAuditLogEntryParams) (GetAuditLogEntryRow, error) {
	row := q.db.QueryRow(ctx, getAuditLogEntry, arg.OrgID, arg.ID)
	var i GetAuditLogEntryRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.Ip,
		&i.UserAgent,
		&i.At,
		&i.ActorName,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one

INSERT INTO audit_log (org_id, actor_user_id, action, entity_type, entity_id, before, after, ip, user_agent)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, org_id, actor_user_id, action, entity_type, entity_id, before, after, ip, user_agent, at
`

type InsertAuditLogParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    pgtype.UUID `json:"entity_id"`
	Before      []byte      `json:"before"`
	After       []byte      `json:"after"`
	Ip          *string     `json:"ip"`
	UserAgent   *string     `json:"user_agent"`
}

// audit_log is append-only (enforced by triggers in 000002): INSERT + SELECT
// only. Reads are always org-scoped; the platform admin view lives in
// admin_audit.sql.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.OrgID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.Ip,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.Ip,
		&i.UserAgent,
		&i.At,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT a.id, a.org_id, a.actor_user_id, a.action, a.entity_type, a.entity_id,
       a.before, a.after, a.ip, a.user_agent, a.at,
       u.full_name AS actor_name
FROM audit_log a
LEFT JOIN users u ON u.id = a.actor_user_id
WHERE a.org_id = $1
  AND ($2::text IS NULL OR a.entity_type = $2::text)
  AND ($3::uuid IS NULL OR a.actor_user_id = $3::uuid)
  AND ($4::timestamptz IS NULL OR a.at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR a.at <= $5::timestamptz)
  AND ($6::timestamptz IS NULL
       OR (a.at, a.id) < ($6::timestamptz, $7::uuid))
ORDER BY a.at DESC, a.id DESC
LIMIT $8
`

type ListAuditLogParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	EntityType  *string            `json:"entity_type"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	FromAt      pgtype.Timestamptz `json:"from_at"`
	ToAt        pgtype.Timestamptz `json:"to_at"`
	CursorAt    pgtype.Timestamptz `json:"cursor_at"`
	CursorID    pgtype.UUID        `json:"cursor_id"`
	RowLimit    int32              `json:"row_limit"`
}

type ListAuditLogRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Before      []byte             `json:"before"`
	After       []byte             `json:"after"`
	Ip          *string            `json:"ip"`
	UserAgent   *string            `json:"user_agent"`
	At          pgtype.Timestamptz `json:"at"`
	ActorName   *string            `json:"actor_name"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.OrgID,
		arg.EntityType,
		arg.ActorUserID,
		arg.FromAt,
		arg.ToAt,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogRow{}
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.UserAgent,
			&i.At,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
