// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contract_signatures.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countContractSignatures = `-- name: CountContractSignatures :one
SELECT count(*) FROM contract_signatures
WHERE org_id = $1 AND contract_id = $2
  AND party = $3
`

type CountContractSignaturesParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	ContractID pgtype.UUID `json:"contract_id"`
	Party      string      `json:"party"`
}

func (q *Queries) CountContractSignatures(ctx context.Context, arg CountContractSignaturesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContractSignatures, arg.OrgID, arg.ContractID, arg.Party)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContractSignature = `-- name: CreateContractSignature :one

INSERT INTO contract_signatures (
    org_id, contract_id, party, user_id, method, otp_ref,
    signature_object_key, snapshot_hash, ip, user_agent
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
RETURNING id, org_id, contract_id, party, user_id, method, otp_ref, signature_object_key, snapshot_hash, ip, user_agent, signed_at, created_at, updated_at
`

type CreateContractSignatureParams struct {
	OrgID              pgtype.UUID `json:"org_id"`
	ContractID         pgtype.UUID `json:"contract_id"`
	Party              string      `json:"party"`
	UserID             pgtype.UUID `json:"user_id"`
	Method             string      `json:"method"`
	OtpRef             *string     `json:"otp_ref"`
	SignatureObjectKey *string     `json:"signature_object_key"`
	SnapshotHash       string      `json:"snapshot_hash"`
	Ip                 *string     `json:"ip"`
	UserAgent          *string     `json:"user_agent"`
}

// contract_signatures is append-only evidence: one row per party, carrying the
// hash that was on screen when it was signed plus the OTP reference, IP and
// user agent (SPEC §5.5 "Digital signing"). There is no update and no delete —
// a disputed contract is terminated and replaced, never edited.
func (q *Queries) CreateContractSignature(ctx context.Context, arg CreateContractSignatureParams) (ContractSignature, error) {
	row := q.db.QueryRow(ctx, createContractSignature,
		arg.OrgID,
		arg.ContractID,
		arg.Party,
		arg.UserID,
		arg.Method,
		arg.OtpRef,
		arg.SignatureObjectKey,
		arg.SnapshotHash,
		arg.Ip,
		arg.UserAgent,
	)
	var i ContractSignature
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ContractID,
		&i.Party,
		&i.UserID,
		&i.Method,
		&i.OtpRef,
		&i.SignatureObjectKey,
		&i.SnapshotHash,
		&i.Ip,
		&i.UserAgent,
		&i.SignedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContractSignatures = `-- name: ListContractSignatures :many
SELECT sg.id, sg.org_id, sg.contract_id, sg.party, sg.user_id, sg.method,
       sg.otp_ref, sg.signature_object_key, sg.snapshot_hash, sg.signed_at,
       COALESCE(u.full_name, '')::text AS signer_name,
       u.phone AS signer_phone
FROM contract_signatures sg
LEFT JOIN users u ON u.id = sg.user_id
WHERE sg.org_id = $1 AND sg.contract_id = $2
ORDER BY sg.signed_at, sg.party
`

type ListContractSignaturesParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	ContractID pgtype.UUID `json:"contract_id"`
}

type ListContractSignaturesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	ContractID         pgtype.UUID        `json:"contract_id"`
	Party              string             `json:"party"`
	UserID             pgtype.UUID        `json:"user_id"`
	Method             string             `json:"method"`
	OtpRef             *string            `json:"otp_ref"`
	SignatureObjectKey *string            `json:"signature_object_key"`
	SnapshotHash       string             `json:"snapshot_hash"`
	SignedAt           pgtype.Timestamptz `json:"signed_at"`
	SignerName         string             `json:"signer_name"`
	SignerPhone        *string            `json:"signer_phone"`
}

func (q *Queries) ListContractSignatures(ctx context.Context, arg ListContractSignaturesParams) ([]ListContractSignaturesRow, error) {
	rows, err := q.db.Query(ctx, listContractSignatures, arg.OrgID, arg.ContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContractSignaturesRow{}
	for rows.Next() {
		var i ListContractSignaturesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ContractID,
			&i.Party,
			&i.UserID,
			&i.Method,
			&i.OtpRef,
			&i.SignatureObjectKey,
			&i.SnapshotHash,
			&i.SignedAt,
			&i.SignerName,
			&i.SignerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
