// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contract_templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultTemplate = `-- name: ClearDefaultTemplate :exec
UPDATE contract_templates SET is_default = false
WHERE org_id = $1 AND is_default AND deleted_at IS NULL
  AND id <> $2
`

type ClearDefaultTemplateParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	KeepID pgtype.UUID `json:"keep_id"`
}

// ClearDefaultTemplate runs before promoting another template, so the partial
// unique index on (org_id) WHERE is_default never sees two.
func (q *Queries) ClearDefaultTemplate(ctx context.Context, arg ClearDefaultTemplateParams) error {
	_, err := q.db.Exec(ctx, clearDefaultTemplate, arg.OrgID, arg.KeepID)
	return err
}

const countContractsForTemplate = `-- name: CountContractsForTemplate :one
SELECT count(*) FROM contracts
WHERE org_id = $1 AND template_id = $2 AND deleted_at IS NULL
`

type CountContractsForTemplateParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	TemplateID pgtype.UUID `json:"template_id"`
}

func (q *Queries) CountContractsForTemplate(ctx context.Context, arg CountContractsForTemplateParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContractsForTemplate, arg.OrgID, arg.TemplateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContractTemplate = `-- name: CreateContractTemplate :one

INSERT INTO contract_templates (org_id, name, body_html, is_default)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, name, body_html, is_default, created_at, updated_at, deleted_at
`

type CreateContractTemplateParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	Name      string      `json:"name"`
	BodyHtml  string      `json:"body_html"`
	IsDefault bool        `json:"is_default"`
}

// Contract templates are the org's terms library. Editing one never touches an
// existing contract: a contract stores its own rendered `terms_snapshot_html`
// (SPEC §4, "contracts snapshot terms and rent at signing").
func (q *Queries) CreateContractTemplate(ctx context.Context, arg CreateContractTemplateParams) (ContractTemplate, error) {
	row := q.db.QueryRow(ctx, createContractTemplate,
		arg.OrgID,
		arg.Name,
		arg.BodyHtml,
		arg.IsDefault,
	)
	var i ContractTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.BodyHtml,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getContractTemplate = `-- name: GetContractTemplate :one
SELECT id, org_id, name, body_html, is_default, created_at, updated_at, deleted_at FROM contract_templates
WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetContractTemplateParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetContractTemplate(ctx context.Context, arg GetContractTemplateParams) (ContractTemplate, error) {
	row := q.db.QueryRow(ctx, getContractTemplate, arg.OrgID, arg.ID)
	var i ContractTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.BodyHtml,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDefaultContractTemplate = `-- name: GetDefaultContractTemplate :one
SELECT id, org_id, name, body_html, is_default, created_at, updated_at, deleted_at FROM contract_templates
WHERE org_id = $1 AND is_default AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDefaultContractTemplate(ctx context.Context, orgID pgtype.UUID) (ContractTemplate, error) {
	row := q.db.QueryRow(ctx, getDefaultContractTemplate, orgID)
	var i ContractTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.BodyHtml,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listContractTemplates = `-- name: ListContractTemplates :many
SELECT id, org_id, name, body_html, is_default, created_at, updated_at, deleted_at FROM contract_templates
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY is_default DESC, created_at DESC, id DESC
`

func (q *Queries) ListContractTemplates(ctx context.Context, orgID pgtype.UUID) ([]ContractTemplate, error) {
	rows, err := q.db.Query(ctx, listContractTemplates, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContractTemplate{}
	for rows.Next() {
		var i ContractTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.BodyHtml,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteContractTemplate = `-- name: SoftDeleteContractTemplate :one
UPDATE contract_templates SET deleted_at = now()
WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, org_id, name, body_html, is_default, created_at, updated_at, deleted_at
`

type SoftDeleteContractTemplateParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) SoftDeleteContractTemplate(ctx context.Context, arg SoftDeleteContractTemplateParams) (ContractTemplate, error) {
	row := q.db.QueryRow(ctx, softDeleteContractTemplate, arg.OrgID, arg.ID)
	var i ContractTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.BodyHtml,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateContractTemplate = `-- name: UpdateContractTemplate :one
UPDATE contract_templates
SET name       = COALESCE($1, name),
    body_html  = COALESCE($2, body_html),
    is_default = COALESCE($3, is_default)
WHERE org_id = $4 AND id = $5 AND deleted_at IS NULL
RETURNING id, org_id, name, body_html, is_default, created_at, updated_at, deleted_at
`

type UpdateContractTemplateParams struct {
	Name      *string     `json:"name"`
	BodyHtml  *string     `json:"body_html"`
	IsDefault *bool       `json:"is_default"`
	OrgID     pgtype.UUID `json:"org_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateContractTemplate(ctx context.Context, arg UpdateContractTemplateParams) (ContractTemplate, error) {
	row := q.db.QueryRow(ctx, updateContractTemplate,
		arg.Name,
		arg.BodyHtml,
		arg.IsDefault,
		arg.OrgID,
		arg.ID,
	)
	var i ContractTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.BodyHtml,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
