// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expenses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExpenseCategories = `-- name: CountExpenseCategories :one
SELECT count(*) FROM expense_categories
WHERE org_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountExpenseCategories(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenseCategories, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExpensesInCategory = `-- name: CountExpensesInCategory :one
SELECT count(*) FROM expenses
WHERE org_id = $1 AND category_id = $2 AND deleted_at IS NULL
`

type CountExpensesInCategoryParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	CategoryID pgtype.UUID `json:"category_id"`
}

// CountExpensesInCategory decides whether a category may be deleted: a
// category some expense still points at is deactivated, never removed, or the
// ledger would lose the word it was filed under.
func (q *Queries) CountExpensesInCategory(ctx context.Context, arg CountExpensesInCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpensesInCategory, arg.OrgID, arg.CategoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpense = `-- name: CreateExpense :one

INSERT INTO expenses (
    org_id, property_id, unit_id, category_id, amount, incurred_on,
    vendor, reference, note, recorded_by_user_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10
)
RETURNING id, org_id, property_id, unit_id, category_id, amount, incurred_on, vendor, reference, note, receipt_object_key, recorded_by_user_id, status, voided_at, void_reason, created_at, updated_at, deleted_at, receipt_content_type, receipt_size
`

type CreateExpenseParams struct {
	OrgID            pgtype.UUID `json:"org_id"`
	PropertyID       pgtype.UUID `json:"property_id"`
	UnitID           pgtype.UUID `json:"unit_id"`
	CategoryID       pgtype.UUID `json:"category_id"`
	Amount           int64       `json:"amount"`
	IncurredOn       pgtype.Date `json:"incurred_on"`
	Vendor           string      `json:"vendor"`
	Reference        string      `json:"reference"`
	Note             string      `json:"note"`
	RecordedByUserID pgtype.UUID `json:"recorded_by_user_id"`
}

// ---------------------------------------------------------------- expenses --
func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.OrgID,
		arg.PropertyID,
		arg.UnitID,
		arg.CategoryID,
		arg.Amount,
		arg.IncurredOn,
		arg.Vendor,
		arg.Reference,
		arg.Note,
		arg.RecordedByUserID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PropertyID,
		&i.UnitID,
		&i.CategoryID,
		&i.Amount,
		&i.IncurredOn,
		&i.Vendor,
		&i.Reference,
		&i.Note,
		&i.ReceiptObjectKey,
		&i.RecordedByUserID,
		&i.Status,
		&i.VoidedAt,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ReceiptContentType,
		&i.ReceiptSize,
	)
	return i, err
}

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (org_id, name, is_default, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, name, is_default, sort_order, active, created_at, updated_at, deleted_at
`

type CreateExpenseCategoryParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	Name      string      `json:"name"`
	IsDefault bool        `json:"is_default"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, createExpenseCategory,
		arg.OrgID,
		arg.Name,
		arg.IsDefault,
		arg.SortOrder,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IsDefault,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const expenseSummaryByCategory = `-- name: ExpenseSummaryByCategory :many
SELECT c.id, c.name,
       COALESCE(SUM(e.amount), 0)::bigint AS amount,
       COUNT(e.id)::bigint AS row_count
FROM expense_categories c
LEFT JOIN expenses e
       ON e.category_id = c.id AND e.org_id = c.org_id
      AND e.deleted_at IS NULL AND e.status = 'recorded'
      AND e.incurred_on >= $1 AND e.incurred_on < $2
      AND ($3::uuid IS NULL OR e.property_id = $3::uuid)
WHERE c.org_id = $4 AND c.deleted_at IS NULL AND c.active
GROUP BY c.id, c.name
`

type ExpenseSummaryByCategoryParams struct {
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	PropertyID pgtype.UUID `json:"property_id"`
	OrgID      pgtype.UUID `json:"org_id"`
}

type ExpenseSummaryByCategoryRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Amount   int64       `json:"amount"`
	RowCount int64       `json:"row_count"`
}

// ExpenseSummaryByCategory reads from the active categories for the same
// reason: the eight seeded rows are the chart's fixed vocabulary.
func (q *Queries) ExpenseSummaryByCategory(ctx context.Context, arg ExpenseSummaryByCategoryParams) ([]ExpenseSummaryByCategoryRow, error) {
	rows, err := q.db.Query(ctx, expenseSummaryByCategory,
		arg.FromDate,
		arg.ToDate,
		arg.PropertyID,
		arg.OrgID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseSummaryByCategoryRow{}
	for rows.Next() {
		var i ExpenseSummaryByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.RowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expenseSummaryByProperty = `-- name: ExpenseSummaryByProperty :many

SELECT p.id, p.name,
       COALESCE(SUM(e.amount), 0)::bigint AS amount,
       COUNT(e.id)::bigint AS row_count
FROM properties p
LEFT JOIN expenses e
       ON e.property_id = p.id AND e.org_id = p.org_id
      AND e.deleted_at IS NULL AND e.status = 'recorded'
      AND e.incurred_on >= $1 AND e.incurred_on < $2
WHERE p.org_id = $3 AND p.deleted_at IS NULL
  AND ($4::uuid IS NULL OR p.id = $4::uuid)
GROUP BY p.id, p.name
`

type ExpenseSummaryByPropertyParams struct {
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	OrgID      pgtype.UUID `json:"org_id"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type ExpenseSummaryByPropertyRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Amount   int64       `json:"amount"`
	RowCount int64       `json:"row_count"`
}

// ----------------------------------------------------------------- summary --
// ExpenseSummaryByProperty drives the all-properties chart. It reads from
// properties rather than from expenses so a property that spent nothing this
// month is a bar at zero rather than a gap in the series.
func (q *Queries) ExpenseSummaryByProperty(ctx context.Context, arg ExpenseSummaryByPropertyParams) ([]ExpenseSummaryByPropertyRow, error) {
	rows, err := q.db.Query(ctx, expenseSummaryByProperty,
		arg.FromDate,
		arg.ToDate,
		arg.OrgID,
		arg.PropertyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseSummaryByPropertyRow{}
	for rows.Next() {
		var i ExpenseSummaryByPropertyRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Amount,
			&i.RowCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expenseUncategorisedTotal = `-- name: ExpenseUncategorisedTotal :one
SELECT COALESCE(SUM(e.amount), 0)::bigint AS amount, COUNT(e.id)::bigint AS row_count
FROM expenses e
WHERE e.org_id = $1 AND e.deleted_at IS NULL AND e.status = 'recorded'
  AND e.category_id IS NULL
  AND e.incurred_on >= $2 AND e.incurred_on < $3
  AND ($4::uuid IS NULL OR e.property_id = $4::uuid)
`

type ExpenseUncategorisedTotalParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type ExpenseUncategorisedTotalRow struct {
	Amount   int64 `json:"amount"`
	RowCount int64 `json:"row_count"`
}

// ExpenseUncategorisedTotal is the bucket for rows filed under no category. It
// is not a category, so it cannot come out of the query above.
func (q *Queries) ExpenseUncategorisedTotal(ctx context.Context, arg ExpenseUncategorisedTotalParams) (ExpenseUncategorisedTotalRow, error) {
	row := q.db.QueryRow(ctx, expenseUncategorisedTotal,
		arg.OrgID,
		arg.FromDate,
		arg.ToDate,
		arg.PropertyID,
	)
	var i ExpenseUncategorisedTotalRow
	err := row.Scan(&i.Amount, &i.RowCount)
	return i, err
}

const expenseWindowTotal = `-- name: ExpenseWindowTotal :one
SELECT COALESCE(SUM(e.amount), 0)::bigint AS amount, COUNT(e.id)::bigint AS row_count
FROM expenses e
WHERE e.org_id = $1 AND e.deleted_at IS NULL AND e.status = 'recorded'
  AND e.incurred_on >= $2 AND e.incurred_on < $3
  AND ($4::uuid IS NULL OR e.property_id = $4::uuid)
`

type ExpenseWindowTotalParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type ExpenseWindowTotalRow struct {
	Amount   int64 `json:"amount"`
	RowCount int64 `json:"row_count"`
}

// ExpenseWindowTotal is the grand total of a window, and the same query run on
// the previous window is what `change_pct` is measured against.
func (q *Queries) ExpenseWindowTotal(ctx context.Context, arg ExpenseWindowTotalParams) (ExpenseWindowTotalRow, error) {
	row := q.db.QueryRow(ctx, expenseWindowTotal,
		arg.OrgID,
		arg.FromDate,
		arg.ToDate,
		arg.PropertyID,
	)
	var i ExpenseWindowTotalRow
	err := row.Scan(&i.Amount, &i.RowCount)
	return i, err
}

const getExpense = `-- name: GetExpense :one
SELECT e.id, e.org_id, e.property_id, e.unit_id, e.category_id, e.amount, e.incurred_on, e.vendor, e.reference, e.note, e.receipt_object_key, e.recorded_by_user_id, e.status, e.voided_at, e.void_reason, e.created_at, e.updated_at, e.deleted_at, e.receipt_content_type, e.receipt_size,
       p.name AS property_name,
       u.name AS unit_name,
       c.name AS category_name,
       rb.full_name AS recorded_by_name
FROM expenses e
JOIN properties p            ON p.id = e.property_id AND p.org_id = e.org_id
LEFT JOIN units u            ON u.id = e.unit_id AND u.org_id = e.org_id
LEFT JOIN expense_categories c ON c.id = e.category_id AND c.org_id = e.org_id
LEFT JOIN users rb           ON rb.id = e.recorded_by_user_id
WHERE e.org_id = $1 AND e.id = $2 AND e.deleted_at IS NULL
`

type GetExpenseParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetExpenseRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	PropertyID         pgtype.UUID        `json:"property_id"`
	UnitID             pgtype.UUID        `json:"unit_id"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	Amount             int64              `json:"amount"`
	IncurredOn         pgtype.Date        `json:"incurred_on"`
	Vendor             string             `json:"vendor"`
	Reference          string             `json:"reference"`
	Note               string             `json:"note"`
	ReceiptObjectKey   *string            `json:"receipt_object_key"`
	RecordedByUserID   pgtype.UUID        `json:"recorded_by_user_id"`
	Status             string             `json:"status"`
	VoidedAt           pgtype.Timestamptz `json:"voided_at"`
	VoidReason         *string            `json:"void_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ReceiptContentType *string            `json:"receipt_content_type"`
	ReceiptSize        *int64             `json:"receipt_size"`
	PropertyName       string             `json:"property_name"`
	UnitName           *string            `json:"unit_name"`
	CategoryName       *string            `json:"category_name"`
	RecordedByName     *string            `json:"recorded_by_name"`
}

func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (GetExpenseRow, error) {
	row := q.db.QueryRow(ctx, getExpense, arg.OrgID, arg.ID)
	var i GetExpenseRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PropertyID,
		&i.UnitID,
		&i.CategoryID,
		&i.Amount,
		&i.IncurredOn,
		&i.Vendor,
		&i.Reference,
		&i.Note,
		&i.ReceiptObjectKey,
		&i.RecordedByUserID,
		&i.Status,
		&i.VoidedAt,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ReceiptContentType,
		&i.ReceiptSize,
		&i.PropertyName,
		&i.UnitName,
		&i.CategoryName,
		&i.RecordedByName,
	)
	return i, err
}

const getExpenseCategory = `-- name: GetExpenseCategory :one
SELECT id, org_id, name, is_default, sort_order, active, created_at, updated_at, deleted_at FROM expense_categories
WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetExpenseCategoryParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetExpenseCategory(ctx context.Context, arg GetExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getExpenseCategory, arg.OrgID, arg.ID)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IsDefault,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listExpenseCategories = `-- name: ListExpenseCategories :many


SELECT id, org_id, name, is_default, sort_order, active, created_at, updated_at, deleted_at FROM expense_categories
WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY sort_order, name, id
`

// Expenses and their categories (SPEC §5.11, PLAN2 Phase 10, FLOWS 12).
//
// An expense is money the landlord spent on a property — the other half of the
// ledger the payments tables hold. Corrections work the way a payment reversal
// does: the row stays and is marked `voided` with a reason, because a repair
// that was recorded and then cancelled is part of the record.
//
// Every window filter is half-open on `incurred_on` — `>= from_date` and
// `< to_date` — so the handler resolves inclusive wire dates into an exclusive
// upper bound once and every query below agrees on what "the period" means.
// ------------------------------------------------------------- categories --
func (q *Queries) ListExpenseCategories(ctx context.Context, orgID pgtype.UUID) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listExpenseCategories, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategory{}
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.IsDefault,
			&i.SortOrder,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseTotals = `-- name: ListExpenseTotals :one
SELECT count(*)::bigint AS row_count, COALESCE(SUM(e.amount), 0)::bigint AS amount
FROM expenses e
WHERE e.org_id = $1 AND e.deleted_at IS NULL
  AND ($2::text IS NULL OR e.status = $2::text)
  AND ($3::uuid IS NULL OR e.property_id = $3::uuid)
  AND ($4::uuid IS NULL OR e.unit_id = $4::uuid)
  AND ($5::uuid IS NULL OR e.category_id = $5::uuid)
  AND ($6::date IS NULL OR e.incurred_on >= $6::date)
  AND ($7::date IS NULL OR e.incurred_on < $7::date)
  AND ($8::text IS NULL
       OR e.vendor ILIKE '%' || $8::text || '%'
       OR e.reference ILIKE '%' || $8::text || '%'
       OR e.note ILIKE '%' || $8::text || '%')
`

type ListExpenseTotalsParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	Status     *string     `json:"status"`
	PropertyID pgtype.UUID `json:"property_id"`
	UnitID     pgtype.UUID `json:"unit_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	Q          *string     `json:"q"`
}

type ListExpenseTotalsRow struct {
	RowCount int64 `json:"row_count"`
	Amount   int64 `json:"amount"`
}

// ListExpenseTotals answers "what does this filter add up to" over the whole
// filtered set, not the page: a ledger whose total changed as you paged would
// be worse than no total at all.
func (q *Queries) ListExpenseTotals(ctx context.Context, arg ListExpenseTotalsParams) (ListExpenseTotalsRow, error) {
	row := q.db.QueryRow(ctx, listExpenseTotals,
		arg.OrgID,
		arg.Status,
		arg.PropertyID,
		arg.UnitID,
		arg.CategoryID,
		arg.FromDate,
		arg.ToDate,
		arg.Q,
	)
	var i ListExpenseTotalsRow
	err := row.Scan(&i.RowCount, &i.Amount)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT e.id, e.org_id, e.property_id, e.unit_id, e.category_id, e.amount, e.incurred_on, e.vendor, e.reference, e.note, e.receipt_object_key, e.recorded_by_user_id, e.status, e.voided_at, e.void_reason, e.created_at, e.updated_at, e.deleted_at, e.receipt_content_type, e.receipt_size,
       p.name AS property_name,
       u.name AS unit_name,
       c.name AS category_name,
       rb.full_name AS recorded_by_name
FROM expenses e
JOIN properties p            ON p.id = e.property_id AND p.org_id = e.org_id
LEFT JOIN units u            ON u.id = e.unit_id AND u.org_id = e.org_id
LEFT JOIN expense_categories c ON c.id = e.category_id AND c.org_id = e.org_id
LEFT JOIN users rb           ON rb.id = e.recorded_by_user_id
WHERE e.org_id = $1 AND e.deleted_at IS NULL
  AND ($2::text IS NULL OR e.status = $2::text)
  AND ($3::uuid IS NULL OR e.property_id = $3::uuid)
  AND ($4::uuid IS NULL OR e.unit_id = $4::uuid)
  AND ($5::uuid IS NULL OR e.category_id = $5::uuid)
  AND ($6::date IS NULL OR e.incurred_on >= $6::date)
  AND ($7::date IS NULL OR e.incurred_on < $7::date)
  AND ($8::text IS NULL
       OR e.vendor ILIKE '%' || $8::text || '%'
       OR e.reference ILIKE '%' || $8::text || '%'
       OR e.note ILIKE '%' || $8::text || '%')
  AND ($9::date IS NULL
       OR (e.incurred_on, e.created_at, e.id)
          < ($9::date, $10::timestamptz, $11::uuid))
ORDER BY e.incurred_on DESC, e.created_at DESC, e.id DESC
LIMIT $12
`

type ListExpensesParams struct {
	OrgID          pgtype.UUID        `json:"org_id"`
	Status         *string            `json:"status"`
	PropertyID     pgtype.UUID        `json:"property_id"`
	UnitID         pgtype.UUID        `json:"unit_id"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	FromDate       pgtype.Date        `json:"from_date"`
	ToDate         pgtype.Date        `json:"to_date"`
	Q              *string            `json:"q"`
	CursorIncurred pgtype.Date        `json:"cursor_incurred"`
	CursorCreated  pgtype.Timestamptz `json:"cursor_created"`
	CursorID       pgtype.UUID        `json:"cursor_id"`
	RowLimit       int32              `json:"row_limit"`
}

type ListExpensesRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	PropertyID         pgtype.UUID        `json:"property_id"`
	UnitID             pgtype.UUID        `json:"unit_id"`
	CategoryID         pgtype.UUID        `json:"category_id"`
	Amount             int64              `json:"amount"`
	IncurredOn         pgtype.Date        `json:"incurred_on"`
	Vendor             string             `json:"vendor"`
	Reference          string             `json:"reference"`
	Note               string             `json:"note"`
	ReceiptObjectKey   *string            `json:"receipt_object_key"`
	RecordedByUserID   pgtype.UUID        `json:"recorded_by_user_id"`
	Status             string             `json:"status"`
	VoidedAt           pgtype.Timestamptz `json:"voided_at"`
	VoidReason         *string            `json:"void_reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ReceiptContentType *string            `json:"receipt_content_type"`
	ReceiptSize        *int64             `json:"receipt_size"`
	PropertyName       string             `json:"property_name"`
	UnitName           *string            `json:"unit_name"`
	CategoryName       *string            `json:"category_name"`
	RecordedByName     *string            `json:"recorded_by_name"`
}

// ListExpenses is the ledger: newest incurred first, with the identity blocks
// a table needs so a row renders without a second request. The cursor compares
// the whole sort tuple, so a page boundary inside a day cannot repeat or drop
// a row.
func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.OrgID,
		arg.Status,
		arg.PropertyID,
		arg.UnitID,
		arg.CategoryID,
		arg.FromDate,
		arg.ToDate,
		arg.Q,
		arg.CursorIncurred,
		arg.CursorCreated,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesRow{}
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.PropertyID,
			&i.UnitID,
			&i.CategoryID,
			&i.Amount,
			&i.IncurredOn,
			&i.Vendor,
			&i.Reference,
			&i.Note,
			&i.ReceiptObjectKey,
			&i.RecordedByUserID,
			&i.Status,
			&i.VoidedAt,
			&i.VoidReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ReceiptContentType,
			&i.ReceiptSize,
			&i.PropertyName,
			&i.UnitName,
			&i.CategoryName,
			&i.RecordedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxExpenseCategorySortOrder = `-- name: MaxExpenseCategorySortOrder :one
SELECT COALESCE(MAX(sort_order), 0)::int AS max_sort_order
FROM expense_categories
WHERE org_id = $1 AND deleted_at IS NULL
`

func (q *Queries) MaxExpenseCategorySortOrder(ctx context.Context, orgID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxExpenseCategorySortOrder, orgID)
	var max_sort_order int32
	err := row.Scan(&max_sort_order)
	return max_sort_order, err
}

const setExpenseReceipt = `-- name: SetExpenseReceipt :one
UPDATE expenses
SET receipt_object_key   = $1,
    receipt_content_type = $2,
    receipt_size         = $3
WHERE org_id = $4 AND id = $5 AND deleted_at IS NULL
RETURNING id, org_id, property_id, unit_id, category_id, amount, incurred_on, vendor, reference, note, receipt_object_key, recorded_by_user_id, status, voided_at, void_reason, created_at, updated_at, deleted_at, receipt_content_type, receipt_size
`

type SetExpenseReceiptParams struct {
	ReceiptObjectKey   *string     `json:"receipt_object_key"`
	ReceiptContentType *string     `json:"receipt_content_type"`
	ReceiptSize        *int64      `json:"receipt_size"`
	OrgID              pgtype.UUID `json:"org_id"`
	ID                 pgtype.UUID `json:"id"`
}

// SetExpenseReceipt writes all three receipt columns together — the key, and
// the type and size MinIO reported for the object under it — so a row can never
// describe a receipt it does not have. Clearing passes NULL for all three.
func (q *Queries) SetExpenseReceipt(ctx context.Context, arg SetExpenseReceiptParams) (Expense, error) {
	row := q.db.QueryRow(ctx, setExpenseReceipt,
		arg.ReceiptObjectKey,
		arg.ReceiptContentType,
		arg.ReceiptSize,
		arg.OrgID,
		arg.ID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PropertyID,
		&i.UnitID,
		&i.CategoryID,
		&i.Amount,
		&i.IncurredOn,
		&i.Vendor,
		&i.Reference,
		&i.Note,
		&i.ReceiptObjectKey,
		&i.RecordedByUserID,
		&i.Status,
		&i.VoidedAt,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ReceiptContentType,
		&i.ReceiptSize,
	)
	return i, err
}

const softDeleteExpenseCategory = `-- name: SoftDeleteExpenseCategory :one
UPDATE expense_categories
SET deleted_at = now()
WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, org_id, name, is_default, sort_order, active, created_at, updated_at, deleted_at
`

type SoftDeleteExpenseCategoryParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) SoftDeleteExpenseCategory(ctx context.Context, arg SoftDeleteExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, softDeleteExpenseCategory, arg.OrgID, arg.ID)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IsDefault,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET property_id = COALESCE($1::uuid, property_id),
    unit_id     = CASE WHEN $2::boolean THEN NULL
                       ELSE COALESCE($3::uuid, unit_id) END,
    category_id = CASE WHEN $4::boolean THEN NULL
                       ELSE COALESCE($5::uuid, category_id) END,
    amount      = COALESCE($6::bigint, amount),
    incurred_on = COALESCE($7::date, incurred_on),
    vendor      = COALESCE($8::text, vendor),
    reference   = COALESCE($9::text, reference),
    note        = COALESCE($10::text, note)
WHERE org_id = $11 AND id = $12
  AND deleted_at IS NULL AND status = 'recorded'
RETURNING id, org_id, property_id, unit_id, category_id, amount, incurred_on, vendor, reference, note, receipt_object_key, recorded_by_user_id, status, voided_at, void_reason, created_at, updated_at, deleted_at, receipt_content_type, receipt_size
`

type UpdateExpenseParams struct {
	PropertyID    pgtype.UUID `json:"property_id"`
	ClearUnit     bool        `json:"clear_unit"`
	UnitID        pgtype.UUID `json:"unit_id"`
	ClearCategory bool        `json:"clear_category"`
	CategoryID    pgtype.UUID `json:"category_id"`
	Amount        *int64      `json:"amount"`
	IncurredOn    pgtype.Date `json:"incurred_on"`
	Vendor        *string     `json:"vendor"`
	Reference     *string     `json:"reference"`
	Note          *string     `json:"note"`
	OrgID         pgtype.UUID `json:"org_id"`
	ID            pgtype.UUID `json:"id"`
}

// UpdateExpense edits a live row only. A voided expense finds no row here and
// the handler answers 409 — a correction is not undone by an edit.
func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.PropertyID,
		arg.ClearUnit,
		arg.UnitID,
		arg.ClearCategory,
		arg.CategoryID,
		arg.Amount,
		arg.IncurredOn,
		arg.Vendor,
		arg.Reference,
		arg.Note,
		arg.OrgID,
		arg.ID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PropertyID,
		&i.UnitID,
		&i.CategoryID,
		&i.Amount,
		&i.IncurredOn,
		&i.Vendor,
		&i.Reference,
		&i.Note,
		&i.ReceiptObjectKey,
		&i.RecordedByUserID,
		&i.Status,
		&i.VoidedAt,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ReceiptContentType,
		&i.ReceiptSize,
	)
	return i, err
}

const updateExpenseCategory = `-- name: UpdateExpenseCategory :one
UPDATE expense_categories
SET name       = COALESCE($1::text, name),
    sort_order = COALESCE($2::int, sort_order),
    active     = COALESCE($3::boolean, active)
WHERE org_id = $4 AND id = $5 AND deleted_at IS NULL
RETURNING id, org_id, name, is_default, sort_order, active, created_at, updated_at, deleted_at
`

type UpdateExpenseCategoryParams struct {
	Name      *string     `json:"name"`
	SortOrder *int32      `json:"sort_order"`
	Active    *bool       `json:"active"`
	OrgID     pgtype.UUID `json:"org_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, updateExpenseCategory,
		arg.Name,
		arg.SortOrder,
		arg.Active,
		arg.OrgID,
		arg.ID,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.IsDefault,
		&i.SortOrder,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const voidExpense = `-- name: VoidExpense :one
UPDATE expenses
SET status = 'voided', voided_at = now(), void_reason = $1
WHERE org_id = $2 AND id = $3
  AND deleted_at IS NULL AND status = 'recorded'
RETURNING id, org_id, property_id, unit_id, category_id, amount, incurred_on, vendor, reference, note, receipt_object_key, recorded_by_user_id, status, voided_at, void_reason, created_at, updated_at, deleted_at, receipt_content_type, receipt_size
`

type VoidExpenseParams struct {
	VoidReason *string     `json:"void_reason"`
	OrgID      pgtype.UUID `json:"org_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) VoidExpense(ctx context.Context, arg VoidExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, voidExpense, arg.VoidReason, arg.OrgID, arg.ID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.PropertyID,
		&i.UnitID,
		&i.CategoryID,
		&i.Amount,
		&i.IncurredOn,
		&i.Vendor,
		&i.Reference,
		&i.Note,
		&i.ReceiptObjectKey,
		&i.RecordedByUserID,
		&i.Status,
		&i.VoidedAt,
		&i.VoidReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ReceiptContentType,
		&i.ReceiptSize,
	)
	return i, err
}
