// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package sqlc

import (
	"context"
)

const dBHealthCheck = `-- name: DBHealthCheck :one
SELECT 1 AS ok
`

// Trivial round-trip used by the health endpoint and to keep `sqlc generate`
// meaningful before Phase 1 lands the real schema.
func (q *Queries) DBHealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, dBHealthCheck)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
