// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_requests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelLinkRequest = `-- name: CancelLinkRequest :one
UPDATE unit_link_requests
SET status = 'cancelled', decided_at = now()
WHERE id = $1 AND renter_user_id = $2
  AND status = 'pending' AND deleted_at IS NULL
RETURNING id, org_id, unit_id, renter_user_id, status, created_at, updated_at, deleted_at, payment_period_id, term_days, start_date, end_date, rejection_reason, decided_at, decided_by_user_id, accepted_terms_at
`

type CancelLinkRequestParams struct {
	ID           pgtype.UUID `json:"id"`
	RenterUserID pgtype.UUID `json:"renter_user_id"`
}

// CancelLinkRequest is the renter withdrawing their own pending request, so it
// is keyed by renter_user_id rather than by org.
// guard-exempt: the renter's own request, keyed by (id, renter_user_id).
func (q *Queries) CancelLinkRequest(ctx context.Context, arg CancelLinkRequestParams) (UnitLinkRequest, error) {
	row := q.db.QueryRow(ctx, cancelLinkRequest, arg.ID, arg.RenterUserID)
	var i UnitLinkRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.RenterUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PaymentPeriodID,
		&i.TermDays,
		&i.StartDate,
		&i.EndDate,
		&i.RejectionReason,
		&i.DecidedAt,
		&i.DecidedByUserID,
		&i.AcceptedTermsAt,
	)
	return i, err
}

const countPendingLinkRequest = `-- name: CountPendingLinkRequest :one
SELECT count(*) FROM unit_link_requests
WHERE unit_id = $1 AND renter_user_id = $2
  AND status = 'pending' AND deleted_at IS NULL
`

type CountPendingLinkRequestParams struct {
	UnitID       pgtype.UUID `json:"unit_id"`
	RenterUserID pgtype.UUID `json:"renter_user_id"`
}

// CountPendingLinkRequest backs the duplicate check. It is keyed by the
// renter's own id across orgs (the unit already pins the org), so it is
// exempt from the org_id guard.
// guard-exempt: keyed by (unit_id, renter_user_id); the unit determines the org.
func (q *Queries) CountPendingLinkRequest(ctx context.Context, arg CountPendingLinkRequestParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingLinkRequest, arg.UnitID, arg.RenterUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLinkRequest = `-- name: CreateLinkRequest :one

INSERT INTO unit_link_requests (
    org_id, unit_id, renter_user_id, status, payment_period_id,
    term_days, start_date, end_date, accepted_terms_at, decided_at, decided_by_user_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    now(), $9, $10
)
RETURNING id, org_id, unit_id, renter_user_id, status, created_at, updated_at, deleted_at, payment_period_id, term_days, start_date, end_date, rejection_reason, decided_at, decided_by_user_id, accepted_terms_at
`

type CreateLinkRequestParams struct {
	OrgID           pgtype.UUID        `json:"org_id"`
	UnitID          pgtype.UUID        `json:"unit_id"`
	RenterUserID    pgtype.UUID        `json:"renter_user_id"`
	Status          string             `json:"status"`
	PaymentPeriodID pgtype.UUID        `json:"payment_period_id"`
	TermDays        *int32             `json:"term_days"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	DecidedByUserID pgtype.UUID        `json:"decided_by_user_id"`
}

// A link request is a renter's application for a unit (SPEC §5.4). It is
// org-scoped like everything else, but it is also read by the renter who made
// it: those queries filter by renter_user_id instead, which is the renter's
// own isolation boundary (a renter may hold requests with several orgs).
func (q *Queries) CreateLinkRequest(ctx context.Context, arg CreateLinkRequestParams) (UnitLinkRequest, error) {
	row := q.db.QueryRow(ctx, createLinkRequest,
		arg.OrgID,
		arg.UnitID,
		arg.RenterUserID,
		arg.Status,
		arg.PaymentPeriodID,
		arg.TermDays,
		arg.StartDate,
		arg.EndDate,
		arg.DecidedAt,
		arg.DecidedByUserID,
	)
	var i UnitLinkRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.RenterUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PaymentPeriodID,
		&i.TermDays,
		&i.StartDate,
		&i.EndDate,
		&i.RejectionReason,
		&i.DecidedAt,
		&i.DecidedByUserID,
		&i.AcceptedTermsAt,
	)
	return i, err
}

const decideLinkRequest = `-- name: DecideLinkRequest :one
UPDATE unit_link_requests
SET status             = $1,
    rejection_reason   = $2,
    decided_at         = now(),
    decided_by_user_id = $3
WHERE org_id = $4 AND id = $5
  AND status = 'pending' AND deleted_at IS NULL
RETURNING id, org_id, unit_id, renter_user_id, status, created_at, updated_at, deleted_at, payment_period_id, term_days, start_date, end_date, rejection_reason, decided_at, decided_by_user_id, accepted_terms_at
`

type DecideLinkRequestParams struct {
	Status          string      `json:"status"`
	RejectionReason *string     `json:"rejection_reason"`
	DecidedByUserID pgtype.UUID `json:"decided_by_user_id"`
	OrgID           pgtype.UUID `json:"org_id"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) DecideLinkRequest(ctx context.Context, arg DecideLinkRequestParams) (UnitLinkRequest, error) {
	row := q.db.QueryRow(ctx, decideLinkRequest,
		arg.Status,
		arg.RejectionReason,
		arg.DecidedByUserID,
		arg.OrgID,
		arg.ID,
	)
	var i UnitLinkRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.RenterUserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PaymentPeriodID,
		&i.TermDays,
		&i.StartDate,
		&i.EndDate,
		&i.RejectionReason,
		&i.DecidedAt,
		&i.DecidedByUserID,
		&i.AcceptedTermsAt,
	)
	return i, err
}

const getLinkRequest = `-- name: GetLinkRequest :one
SELECT lr.id, lr.org_id, lr.unit_id, lr.renter_user_id, lr.status,
       lr.payment_period_id, lr.term_days, lr.start_date, lr.end_date,
       lr.rejection_reason, lr.decided_at, lr.decided_by_user_id,
       lr.accepted_terms_at, lr.created_at, lr.updated_at,
       u.name AS unit_name, u.unit_code, u.status AS unit_status,
       p.name AS property_name,
       o.name AS org_name, o.slug AS org_slug,
       ru.phone AS renter_phone, ru.email AS renter_email, ru.full_name AS renter_name,
       pp.label AS period_label, COALESCE(pp.days, 0)::int AS period_days,
       COALESCE(pl.amount, 0)::bigint AS price_amount, COALESCE(pl.period_days, 0)::int AS price_period_days,
       (pl.amount IS NOT NULL)::boolean AS has_price,
       COALESCE(rp.kyc_status, 'incomplete')::text AS kyc_status,
       (rp.kyc_doc_object_key IS NOT NULL)::boolean AS kyc_doc_uploaded
FROM unit_link_requests lr
JOIN units u      ON u.id = lr.unit_id AND u.org_id = lr.org_id
JOIN properties p ON p.id = u.property_id AND p.org_id = lr.org_id
JOIN orgs o       ON o.id = lr.org_id
JOIN users ru     ON ru.id = lr.renter_user_id
LEFT JOIN payment_periods pp ON pp.id = lr.payment_period_id AND pp.org_id = lr.org_id
LEFT JOIN renter_profiles rp ON rp.user_id = lr.renter_user_id AND rp.deleted_at IS NULL
LEFT JOIN LATERAL (
    SELECT pr.amount, pr.period_days FROM price_plans pr
    WHERE pr.unit_id = u.id AND pr.org_id = lr.org_id AND pr.deleted_at IS NULL
      AND pr.effective_from <= CURRENT_DATE
    ORDER BY pr.effective_from DESC, pr.created_at DESC LIMIT 1
) pl ON true
WHERE lr.id = $1 AND lr.deleted_at IS NULL
  AND lr.org_id = COALESCE($2::uuid, lr.org_id)
  AND lr.renter_user_id = COALESCE($3::uuid, lr.renter_user_id)
`

type GetLinkRequestParams struct {
	ID           pgtype.UUID `json:"id"`
	OrgID        pgtype.UUID `json:"org_id"`
	RenterUserID pgtype.UUID `json:"renter_user_id"`
}

type GetLinkRequestRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	UnitID          pgtype.UUID        `json:"unit_id"`
	RenterUserID    pgtype.UUID        `json:"renter_user_id"`
	Status          string             `json:"status"`
	PaymentPeriodID pgtype.UUID        `json:"payment_period_id"`
	TermDays        *int32             `json:"term_days"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	RejectionReason *string            `json:"rejection_reason"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	DecidedByUserID pgtype.UUID        `json:"decided_by_user_id"`
	AcceptedTermsAt pgtype.Timestamptz `json:"accepted_terms_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	UnitName        string             `json:"unit_name"`
	UnitCode        string             `json:"unit_code"`
	UnitStatus      string             `json:"unit_status"`
	PropertyName    string             `json:"property_name"`
	OrgName         string             `json:"org_name"`
	OrgSlug         string             `json:"org_slug"`
	RenterPhone     *string            `json:"renter_phone"`
	RenterEmail     *string            `json:"renter_email"`
	RenterName      string             `json:"renter_name"`
	PeriodLabel     *string            `json:"period_label"`
	PeriodDays      int32              `json:"period_days"`
	PriceAmount     int64              `json:"price_amount"`
	PricePeriodDays int32              `json:"price_period_days"`
	HasPrice        bool               `json:"has_price"`
	KycStatus       string             `json:"kyc_status"`
	KycDocUploaded  bool               `json:"kyc_doc_uploaded"`
}

func (q *Queries) GetLinkRequest(ctx context.Context, arg GetLinkRequestParams) (GetLinkRequestRow, error) {
	row := q.db.QueryRow(ctx, getLinkRequest, arg.ID, arg.OrgID, arg.RenterUserID)
	var i GetLinkRequestRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.RenterUserID,
		&i.Status,
		&i.PaymentPeriodID,
		&i.TermDays,
		&i.StartDate,
		&i.EndDate,
		&i.RejectionReason,
		&i.DecidedAt,
		&i.DecidedByUserID,
		&i.AcceptedTermsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnitName,
		&i.UnitCode,
		&i.UnitStatus,
		&i.PropertyName,
		&i.OrgName,
		&i.OrgSlug,
		&i.RenterPhone,
		&i.RenterEmail,
		&i.RenterName,
		&i.PeriodLabel,
		&i.PeriodDays,
		&i.PriceAmount,
		&i.PricePeriodDays,
		&i.HasPrice,
		&i.KycStatus,
		&i.KycDocUploaded,
	)
	return i, err
}

const listLinkRequests = `-- name: ListLinkRequests :many
SELECT lr.id, lr.org_id, lr.unit_id, lr.renter_user_id, lr.status,
       lr.payment_period_id, lr.term_days, lr.start_date, lr.end_date,
       lr.rejection_reason, lr.decided_at, lr.decided_by_user_id,
       lr.accepted_terms_at, lr.created_at, lr.updated_at,
       u.name AS unit_name, u.unit_code, u.status AS unit_status,
       p.name AS property_name,
       o.name AS org_name, o.slug AS org_slug,
       ru.phone AS renter_phone, ru.email AS renter_email, ru.full_name AS renter_name,
       pp.label AS period_label, COALESCE(pp.days, 0)::int AS period_days,
       COALESCE(pl.amount, 0)::bigint AS price_amount, COALESCE(pl.period_days, 0)::int AS price_period_days,
       (pl.amount IS NOT NULL)::boolean AS has_price,
       COALESCE(rp.kyc_status, 'incomplete')::text AS kyc_status,
       (rp.kyc_doc_object_key IS NOT NULL)::boolean AS kyc_doc_uploaded
FROM unit_link_requests lr
JOIN units u      ON u.id = lr.unit_id AND u.org_id = lr.org_id
JOIN properties p ON p.id = u.property_id AND p.org_id = lr.org_id
JOIN orgs o       ON o.id = lr.org_id
JOIN users ru     ON ru.id = lr.renter_user_id
LEFT JOIN payment_periods pp ON pp.id = lr.payment_period_id AND pp.org_id = lr.org_id
LEFT JOIN renter_profiles rp ON rp.user_id = lr.renter_user_id AND rp.deleted_at IS NULL
LEFT JOIN LATERAL (
    SELECT pr.amount, pr.period_days FROM price_plans pr
    WHERE pr.unit_id = u.id AND pr.org_id = lr.org_id AND pr.deleted_at IS NULL
      AND pr.effective_from <= CURRENT_DATE
    ORDER BY pr.effective_from DESC, pr.created_at DESC LIMIT 1
) pl ON true
WHERE lr.deleted_at IS NULL
  AND ($1::uuid IS NULL OR lr.org_id = $1::uuid)
  AND ($2::uuid IS NULL OR lr.renter_user_id = $2::uuid)
  AND ($3::uuid IS NULL OR lr.unit_id = $3::uuid)
  AND ($4::text IS NULL OR lr.status = $4::text)
  AND ($5::timestamptz IS NULL
       OR (lr.created_at, lr.id) < ($5::timestamptz, $6::uuid))
ORDER BY lr.created_at DESC, lr.id DESC
LIMIT $7
`

type ListLinkRequestsParams struct {
	OrgID        pgtype.UUID        `json:"org_id"`
	RenterUserID pgtype.UUID        `json:"renter_user_id"`
	UnitID       pgtype.UUID        `json:"unit_id"`
	Status       *string            `json:"status"`
	CursorAt     pgtype.Timestamptz `json:"cursor_at"`
	CursorID     pgtype.UUID        `json:"cursor_id"`
	RowLimit     int32              `json:"row_limit"`
}

type ListLinkRequestsRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	UnitID          pgtype.UUID        `json:"unit_id"`
	RenterUserID    pgtype.UUID        `json:"renter_user_id"`
	Status          string             `json:"status"`
	PaymentPeriodID pgtype.UUID        `json:"payment_period_id"`
	TermDays        *int32             `json:"term_days"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	RejectionReason *string            `json:"rejection_reason"`
	DecidedAt       pgtype.Timestamptz `json:"decided_at"`
	DecidedByUserID pgtype.UUID        `json:"decided_by_user_id"`
	AcceptedTermsAt pgtype.Timestamptz `json:"accepted_terms_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	UnitName        string             `json:"unit_name"`
	UnitCode        string             `json:"unit_code"`
	UnitStatus      string             `json:"unit_status"`
	PropertyName    string             `json:"property_name"`
	OrgName         string             `json:"org_name"`
	OrgSlug         string             `json:"org_slug"`
	RenterPhone     *string            `json:"renter_phone"`
	RenterEmail     *string            `json:"renter_email"`
	RenterName      string             `json:"renter_name"`
	PeriodLabel     *string            `json:"period_label"`
	PeriodDays      int32              `json:"period_days"`
	PriceAmount     int64              `json:"price_amount"`
	PricePeriodDays int32              `json:"price_period_days"`
	HasPrice        bool               `json:"has_price"`
	KycStatus       string             `json:"kyc_status"`
	KycDocUploaded  bool               `json:"kyc_doc_uploaded"`
}

// ListLinkRequests serves both inboxes. The landlord passes org_id and leaves
// renter_user_id NULL; the renter passes their own user id and leaves org_id
// NULL. Exactly one of the two is always set (the handlers own that), so a row
// is never returned to a caller outside its own boundary.
// guard-exempt: dual-scoped — org_id for the landlord inbox, renter_user_id for the renter's own list; the handler always supplies one.
func (q *Queries) ListLinkRequests(ctx context.Context, arg ListLinkRequestsParams) ([]ListLinkRequestsRow, error) {
	rows, err := q.db.Query(ctx, listLinkRequests,
		arg.OrgID,
		arg.RenterUserID,
		arg.UnitID,
		arg.Status,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinkRequestsRow{}
	for rows.Next() {
		var i ListLinkRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UnitID,
			&i.RenterUserID,
			&i.Status,
			&i.PaymentPeriodID,
			&i.TermDays,
			&i.StartDate,
			&i.EndDate,
			&i.RejectionReason,
			&i.DecidedAt,
			&i.DecidedByUserID,
			&i.AcceptedTermsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitName,
			&i.UnitCode,
			&i.UnitStatus,
			&i.PropertyName,
			&i.OrgName,
			&i.OrgSlug,
			&i.RenterPhone,
			&i.RenterEmail,
			&i.RenterName,
			&i.PeriodLabel,
			&i.PeriodDays,
			&i.PriceAmount,
			&i.PricePeriodDays,
			&i.HasPrice,
			&i.KycStatus,
			&i.KycDocUploaded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
