// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org_themes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrgTheme = `-- name: GetOrgTheme :one

SELECT org_id, preset_id, tokens, font_id, updated_at FROM org_themes WHERE org_id = $1
`

// Phase 12 theming. One row per org (the org_id is the primary key), holding
// whichever of "a preset", "an explicit token set" and "a font" the landlord
// has chosen. Resolution of that into the theme an app renders lives in
// internal/theme, not here.
func (q *Queries) GetOrgTheme(ctx context.Context, orgID pgtype.UUID) (OrgTheme, error) {
	row := q.db.QueryRow(ctx, getOrgTheme, orgID)
	var i OrgTheme
	err := row.Scan(
		&i.OrgID,
		&i.PresetID,
		&i.Tokens,
		&i.FontID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrgTheme = `-- name: UpsertOrgTheme :one
INSERT INTO org_themes (org_id, preset_id, tokens, font_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (org_id) DO UPDATE
SET preset_id = EXCLUDED.preset_id,
    tokens    = EXCLUDED.tokens,
    font_id   = EXCLUDED.font_id
RETURNING org_id, preset_id, tokens, font_id, updated_at
`

type UpsertOrgThemeParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	PresetID *string     `json:"preset_id"`
	Tokens   []byte      `json:"tokens"`
	FontID   *string     `json:"font_id"`
}

// UpsertOrgTheme writes the whole row: the tenant screen always submits a
// complete choice (a preset, or a full token set, or both), so a partial
// merge here could only produce a theme nobody asked for. `tokens` is stored
// as `{}` when the org is on a plain preset — the resolver reads an empty
// object as "no override".
func (q *Queries) UpsertOrgTheme(ctx context.Context, arg UpsertOrgThemeParams) (OrgTheme, error) {
	row := q.db.QueryRow(ctx, upsertOrgTheme,
		arg.OrgID,
		arg.PresetID,
		arg.Tokens,
		arg.FontID,
	)
	var i OrgTheme
	err := row.Scan(
		&i.OrgID,
		&i.PresetID,
		&i.Tokens,
		&i.FontID,
		&i.UpdatedAt,
	)
	return i, err
}
