// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orgs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrg = `-- name: CreateOrg :one

INSERT INTO orgs (name, slug, settings)
VALUES ($1, $2, $3)
RETURNING id, name, slug, status, settings, created_at, updated_at, deleted_at
`

type CreateOrgParams struct {
	Name     string `json:"name"`
	Slug     string `json:"slug"`
	Settings []byte `json:"settings"`
}

// orgs is the tenancy root: it is addressed by its own primary key, which is
// the org scope. Rows here are never listed across orgs outside admin_*.sql.
func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.Name, arg.Slug, arg.Settings)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrg = `-- name: GetOrg :one
SELECT id, name, slug, status, settings, created_at, updated_at, deleted_at FROM orgs WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrg(ctx context.Context, id pgtype.UUID) (Org, error) {
	row := q.db.QueryRow(ctx, getOrg, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrgBySlug = `-- name: GetOrgBySlug :one
SELECT id, name, slug, status, settings, created_at, updated_at, deleted_at FROM orgs WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrgBySlug(ctx context.Context, slug string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgBySlug, slug)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const orgSlugExists = `-- name: OrgSlugExists :one
SELECT EXISTS (SELECT 1 FROM orgs WHERE slug = $1)
`

func (q *Queries) OrgSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, orgSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE orgs
SET name     = COALESCE($1, name),
    settings = COALESCE($2, settings)
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, name, slug, status, settings, created_at, updated_at, deleted_at
`

type UpdateOrgParams struct {
	Name     *string     `json:"name"`
	Settings []byte      `json:"settings"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrg, arg.Name, arg.Settings, arg.ID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
