// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_proofs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptPaymentProof = `-- name: AcceptPaymentProof :one
UPDATE payment_proofs
SET status = 'accepted',
    payment_id = $1,
    reviewed_by_user_id = $2,
    reviewed_at = now()
WHERE org_id = $3 AND id = $4 AND status = 'submitted'
RETURNING id, org_id, contract_id, schedule_id, renter_user_id, amount, paid_at, method, reference, note, object_key, content_type, size_bytes, status, payment_id, reviewed_by_user_id, reviewed_at, rejection_reason, created_at, updated_at
`

type AcceptPaymentProofParams struct {
	PaymentID        pgtype.UUID `json:"payment_id"`
	ReviewedByUserID pgtype.UUID `json:"reviewed_by_user_id"`
	OrgID            pgtype.UUID `json:"org_id"`
	ID               pgtype.UUID `json:"id"`
}

// AcceptPaymentProof stamps the review and links the payment the allocator
// produced. `status = 'submitted'` in the predicate is what makes a second
// acceptance a 409 rather than a second payment.
func (q *Queries) AcceptPaymentProof(ctx context.Context, arg AcceptPaymentProofParams) (PaymentProof, error) {
	row := q.db.QueryRow(ctx, acceptPaymentProof,
		arg.PaymentID,
		arg.ReviewedByUserID,
		arg.OrgID,
		arg.ID,
	)
	var i PaymentProof
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ContractID,
		&i.ScheduleID,
		&i.RenterUserID,
		&i.Amount,
		&i.PaidAt,
		&i.Method,
		&i.Reference,
		&i.Note,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.PaymentID,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countProofsToday = `-- name: CountProofsToday :one
SELECT count(*) FROM payment_proofs
WHERE renter_user_id = $1 AND created_at >= now() - INTERVAL '1 day'
`

// CountProofsToday is the renter's daily submission ceiling, checked in
// Postgres as well as in Redis: the limiter fails open when Redis is down
// (SPEC §8), and the ceiling on a write must not.
// guard-exempt: renter-scoped — the caller's own claims across every org they rent from.
func (q *Queries) CountProofsToday(ctx context.Context, renterUserID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProofsToday, renterUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubmittedProofs = `-- name: CountSubmittedProofs :one
SELECT count(*) FROM payment_proofs
WHERE org_id = $1 AND status = 'submitted'
`

// CountSubmittedProofs drives the nav badge. It reads the partial index and
// nothing else, so a landlord's every page load costs one index scan.
func (q *Queries) CountSubmittedProofs(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmittedProofs, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentProof = `-- name: CreatePaymentProof :one

INSERT INTO payment_proofs (
    id, org_id, contract_id, schedule_id, renter_user_id,
    amount, paid_at, method, reference, note,
    object_key, content_type, size_bytes
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13
)
RETURNING id, org_id, contract_id, schedule_id, renter_user_id, amount, paid_at, method, reference, note, object_key, content_type, size_bytes, status, payment_id, reviewed_by_user_id, reviewed_at, rejection_reason, created_at, updated_at
`

type CreatePaymentProofParams struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	ContractID   pgtype.UUID        `json:"contract_id"`
	ScheduleID   pgtype.UUID        `json:"schedule_id"`
	RenterUserID pgtype.UUID        `json:"renter_user_id"`
	Amount       int64              `json:"amount"`
	PaidAt       pgtype.Timestamptz `json:"paid_at"`
	Method       string             `json:"method"`
	Reference    *string            `json:"reference"`
	Note         *string            `json:"note"`
	ObjectKey    string             `json:"object_key"`
	ContentType  string             `json:"content_type"`
	SizeBytes    int64              `json:"size_bytes"`
}

// Proof of payment (SPEC §5.7, PLAN2 §16.1, FLOWS 7).
//
// A proof is a claim the renter files and the landlord reviews. Nothing here
// touches a schedule: acceptance runs the existing allocator and links the
// payment it produced, which is why there is no "apply" query in this file.
//
// Every row carries the identity block the proof shape renders — unit,
// property, renter — so a review queue of twenty draws without twenty
// follow-up requests.
// The id is supplied rather than defaulted: it is minted when the upload ticket
// is issued, because the object key is `{org_id}/{proof_id}.{ext}` and the key
// has to exist before the file does.
func (q *Queries) CreatePaymentProof(ctx context.Context, arg CreatePaymentProofParams) (PaymentProof, error) {
	row := q.db.QueryRow(ctx, createPaymentProof,
		arg.ID,
		arg.OrgID,
		arg.ContractID,
		arg.ScheduleID,
		arg.RenterUserID,
		arg.Amount,
		arg.PaidAt,
		arg.Method,
		arg.Reference,
		arg.Note,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i PaymentProof
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ContractID,
		&i.ScheduleID,
		&i.RenterUserID,
		&i.Amount,
		&i.PaidAt,
		&i.Method,
		&i.Reference,
		&i.Note,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.PaymentID,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentProof = `-- name: GetPaymentProof :one
SELECT pp.id, pp.org_id, pp.contract_id, pp.schedule_id, pp.renter_user_id, pp.amount, pp.paid_at, pp.method, pp.reference, pp.note, pp.object_key, pp.content_type, pp.size_bytes, pp.status, pp.payment_id, pp.reviewed_by_user_id, pp.reviewed_at, pp.rejection_reason, pp.created_at, pp.updated_at,
       c.unit_id,
       u.name  AS unit_name,
       pr.name AS property_name,
       ru.full_name AS renter_name,
       rv.full_name AS reviewed_by_name
FROM payment_proofs pp
JOIN contracts c   ON c.id = pp.contract_id AND c.org_id = pp.org_id
JOIN units u       ON u.id = c.unit_id AND u.org_id = c.org_id
JOIN properties pr ON pr.id = u.property_id AND pr.org_id = c.org_id
JOIN users ru      ON ru.id = pp.renter_user_id
LEFT JOIN users rv ON rv.id = pp.reviewed_by_user_id
WHERE pp.id = $1
  AND pp.org_id = COALESCE($2::uuid, pp.org_id)
  AND pp.renter_user_id = COALESCE($3::uuid, pp.renter_user_id)
`

type GetPaymentProofParams struct {
	ID           pgtype.UUID `json:"id"`
	OrgID        pgtype.UUID `json:"org_id"`
	RenterUserID pgtype.UUID `json:"renter_user_id"`
}

type GetPaymentProofRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	ContractID       pgtype.UUID        `json:"contract_id"`
	ScheduleID       pgtype.UUID        `json:"schedule_id"`
	RenterUserID     pgtype.UUID        `json:"renter_user_id"`
	Amount           int64              `json:"amount"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
	Method           string             `json:"method"`
	Reference        *string            `json:"reference"`
	Note             *string            `json:"note"`
	ObjectKey        string             `json:"object_key"`
	ContentType      string             `json:"content_type"`
	SizeBytes        int64              `json:"size_bytes"`
	Status           string             `json:"status"`
	PaymentID        pgtype.UUID        `json:"payment_id"`
	ReviewedByUserID pgtype.UUID        `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason  *string            `json:"rejection_reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	UnitID           pgtype.UUID        `json:"unit_id"`
	UnitName         string             `json:"unit_name"`
	PropertyName     string             `json:"property_name"`
	RenterName       string             `json:"renter_name"`
	ReviewedByName   *string            `json:"reviewed_by_name"`
}

// GetPaymentProof is dual-scoped the way GetPayment is: the landlord supplies
// org_id, the renter supplies renter_user_id, and the handler always supplies
// one. Neither can name the other party's row.
// guard-exempt: dual-scoped — org_id for GET /proofs/{id}, renter_user_id for the renter's own; the handler always supplies one.
func (q *Queries) GetPaymentProof(ctx context.Context, arg GetPaymentProofParams) (GetPaymentProofRow, error) {
	row := q.db.QueryRow(ctx, getPaymentProof, arg.ID, arg.OrgID, arg.RenterUserID)
	var i GetPaymentProofRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ContractID,
		&i.ScheduleID,
		&i.RenterUserID,
		&i.Amount,
		&i.PaidAt,
		&i.Method,
		&i.Reference,
		&i.Note,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.PaymentID,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnitID,
		&i.UnitName,
		&i.PropertyName,
		&i.RenterName,
		&i.ReviewedByName,
	)
	return i, err
}

const listMyPaymentProofs = `-- name: ListMyPaymentProofs :many
SELECT pp.id, pp.org_id, pp.contract_id, pp.schedule_id, pp.renter_user_id, pp.amount, pp.paid_at, pp.method, pp.reference, pp.note, pp.object_key, pp.content_type, pp.size_bytes, pp.status, pp.payment_id, pp.reviewed_by_user_id, pp.reviewed_at, pp.rejection_reason, pp.created_at, pp.updated_at,
       c.unit_id,
       u.name  AS unit_name,
       pr.name AS property_name,
       ru.full_name AS renter_name,
       rv.full_name AS reviewed_by_name
FROM payment_proofs pp
JOIN contracts c   ON c.id = pp.contract_id AND c.org_id = pp.org_id
JOIN units u       ON u.id = c.unit_id AND u.org_id = c.org_id
JOIN properties pr ON pr.id = u.property_id AND pr.org_id = c.org_id
JOIN users ru      ON ru.id = pp.renter_user_id
LEFT JOIN users rv ON rv.id = pp.reviewed_by_user_id
WHERE pp.renter_user_id = $1
  AND ($2::timestamptz IS NULL
       OR (pp.created_at, pp.id) < ($2::timestamptz, $3::uuid))
ORDER BY pp.created_at DESC, pp.id DESC
LIMIT $4
`

type ListMyPaymentProofsParams struct {
	RenterUserID pgtype.UUID        `json:"renter_user_id"`
	CursorAt     pgtype.Timestamptz `json:"cursor_at"`
	CursorID     pgtype.UUID        `json:"cursor_id"`
	RowLimit     int32              `json:"row_limit"`
}

type ListMyPaymentProofsRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	ContractID       pgtype.UUID        `json:"contract_id"`
	ScheduleID       pgtype.UUID        `json:"schedule_id"`
	RenterUserID     pgtype.UUID        `json:"renter_user_id"`
	Amount           int64              `json:"amount"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
	Method           string             `json:"method"`
	Reference        *string            `json:"reference"`
	Note             *string            `json:"note"`
	ObjectKey        string             `json:"object_key"`
	ContentType      string             `json:"content_type"`
	SizeBytes        int64              `json:"size_bytes"`
	Status           string             `json:"status"`
	PaymentID        pgtype.UUID        `json:"payment_id"`
	ReviewedByUserID pgtype.UUID        `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason  *string            `json:"rejection_reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	UnitID           pgtype.UUID        `json:"unit_id"`
	UnitName         string             `json:"unit_name"`
	PropertyName     string             `json:"property_name"`
	RenterName       string             `json:"renter_name"`
	ReviewedByName   *string            `json:"reviewed_by_name"`
}

// ListMyPaymentProofs is the renter's own history, newest first, across every
// org they rent from — the same scope GET /me/payments has.
// guard-exempt: renter-scoped — the caller's own claims span every org they rent from.
func (q *Queries) ListMyPaymentProofs(ctx context.Context, arg ListMyPaymentProofsParams) ([]ListMyPaymentProofsRow, error) {
	rows, err := q.db.Query(ctx, listMyPaymentProofs,
		arg.RenterUserID,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyPaymentProofsRow{}
	for rows.Next() {
		var i ListMyPaymentProofsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ContractID,
			&i.ScheduleID,
			&i.RenterUserID,
			&i.Amount,
			&i.PaidAt,
			&i.Method,
			&i.Reference,
			&i.Note,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.PaymentID,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitID,
			&i.UnitName,
			&i.PropertyName,
			&i.RenterName,
			&i.ReviewedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentProofs = `-- name: ListPaymentProofs :many
SELECT pp.id, pp.org_id, pp.contract_id, pp.schedule_id, pp.renter_user_id, pp.amount, pp.paid_at, pp.method, pp.reference, pp.note, pp.object_key, pp.content_type, pp.size_bytes, pp.status, pp.payment_id, pp.reviewed_by_user_id, pp.reviewed_at, pp.rejection_reason, pp.created_at, pp.updated_at,
       c.unit_id,
       u.name  AS unit_name,
       pr.name AS property_name,
       ru.full_name AS renter_name,
       rv.full_name AS reviewed_by_name
FROM payment_proofs pp
JOIN contracts c   ON c.id = pp.contract_id AND c.org_id = pp.org_id
JOIN units u       ON u.id = c.unit_id AND u.org_id = c.org_id
JOIN properties pr ON pr.id = u.property_id AND pr.org_id = c.org_id
JOIN users ru      ON ru.id = pp.renter_user_id
LEFT JOIN users rv ON rv.id = pp.reviewed_by_user_id
WHERE pp.org_id = $1
  AND pp.status = $2
  AND ($3::timestamptz IS NULL
       OR (pp.created_at, pp.id) > ($3::timestamptz, $4::uuid))
ORDER BY pp.created_at, pp.id
LIMIT $5
`

type ListPaymentProofsParams struct {
	OrgID    pgtype.UUID        `json:"org_id"`
	Status   string             `json:"status"`
	CursorAt pgtype.Timestamptz `json:"cursor_at"`
	CursorID pgtype.UUID        `json:"cursor_id"`
	RowLimit int32              `json:"row_limit"`
}

type ListPaymentProofsRow struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	ContractID       pgtype.UUID        `json:"contract_id"`
	ScheduleID       pgtype.UUID        `json:"schedule_id"`
	RenterUserID     pgtype.UUID        `json:"renter_user_id"`
	Amount           int64              `json:"amount"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
	Method           string             `json:"method"`
	Reference        *string            `json:"reference"`
	Note             *string            `json:"note"`
	ObjectKey        string             `json:"object_key"`
	ContentType      string             `json:"content_type"`
	SizeBytes        int64              `json:"size_bytes"`
	Status           string             `json:"status"`
	PaymentID        pgtype.UUID        `json:"payment_id"`
	ReviewedByUserID pgtype.UUID        `json:"reviewed_by_user_id"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason  *string            `json:"rejection_reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	UnitID           pgtype.UUID        `json:"unit_id"`
	UnitName         string             `json:"unit_name"`
	PropertyName     string             `json:"property_name"`
	RenterName       string             `json:"renter_name"`
	ReviewedByName   *string            `json:"reviewed_by_name"`
}

// ListPaymentProofs is the landlord's review queue: one status at a time,
// oldest claim first, because the renter who has waited longest is the one
// owed an answer.
func (q *Queries) ListPaymentProofs(ctx context.Context, arg ListPaymentProofsParams) ([]ListPaymentProofsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentProofs,
		arg.OrgID,
		arg.Status,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentProofsRow{}
	for rows.Next() {
		var i ListPaymentProofsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ContractID,
			&i.ScheduleID,
			&i.RenterUserID,
			&i.Amount,
			&i.PaidAt,
			&i.Method,
			&i.Reference,
			&i.Note,
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.PaymentID,
			&i.ReviewedByUserID,
			&i.ReviewedAt,
			&i.RejectionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitID,
			&i.UnitName,
			&i.PropertyName,
			&i.RenterName,
			&i.ReviewedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectPaymentProof = `-- name: RejectPaymentProof :one
UPDATE payment_proofs
SET status = 'rejected',
    rejection_reason = $1,
    reviewed_by_user_id = $2,
    reviewed_at = now()
WHERE org_id = $3 AND id = $4 AND status = 'submitted'
RETURNING id, org_id, contract_id, schedule_id, renter_user_id, amount, paid_at, method, reference, note, object_key, content_type, size_bytes, status, payment_id, reviewed_by_user_id, reviewed_at, rejection_reason, created_at, updated_at
`

type RejectPaymentProofParams struct {
	RejectionReason  *string     `json:"rejection_reason"`
	ReviewedByUserID pgtype.UUID `json:"reviewed_by_user_id"`
	OrgID            pgtype.UUID `json:"org_id"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) RejectPaymentProof(ctx context.Context, arg RejectPaymentProofParams) (PaymentProof, error) {
	row := q.db.QueryRow(ctx, rejectPaymentProof,
		arg.RejectionReason,
		arg.ReviewedByUserID,
		arg.OrgID,
		arg.ID,
	)
	var i PaymentProof
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ContractID,
		&i.ScheduleID,
		&i.RenterUserID,
		&i.Amount,
		&i.PaidAt,
		&i.Method,
		&i.Reference,
		&i.Note,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.PaymentID,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const withdrawPaymentProof = `-- name: WithdrawPaymentProof :one
DELETE FROM payment_proofs
WHERE id = $1 AND renter_user_id = $2 AND status = 'submitted'
RETURNING id, org_id, contract_id, schedule_id, renter_user_id, amount, paid_at, method, reference, note, object_key, content_type, size_bytes, status, payment_id, reviewed_by_user_id, reviewed_at, rejection_reason, created_at, updated_at
`

type WithdrawPaymentProofParams struct {
	ID           pgtype.UUID `json:"id"`
	RenterUserID pgtype.UUID `json:"renter_user_id"`
}

// WithdrawPaymentProof is the renter taking a claim back. It is the one place
// a proof row is really deleted, and it is deliberate: an unreviewed claim the
// renter retracted is not a fact anybody needs to keep, and the audit row
// records that it happened. The `submitted` predicate is the lock — a decided
// proof matches nothing and the handler answers 409.
// guard-exempt: renter-scoped — a renter may only withdraw their own claim.
func (q *Queries) WithdrawPaymentProof(ctx context.Context, arg WithdrawPaymentProofParams) (PaymentProof, error) {
	row := q.db.QueryRow(ctx, withdrawPaymentProof, arg.ID, arg.RenterUserID)
	var i PaymentProof
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ContractID,
		&i.ScheduleID,
		&i.RenterUserID,
		&i.Amount,
		&i.PaidAt,
		&i.Method,
		&i.Reference,
		&i.Note,
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.PaymentID,
		&i.ReviewedByUserID,
		&i.ReviewedAt,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
