// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phase21.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const formerArrearsTotal = `-- name: FormerArrearsTotal :one
SELECT COALESCE(sum(GREATEST(s.amount - s.paid_amount, 0)), 0)::bigint AS outstanding,
       count(DISTINCT c.id)::bigint AS contracts
FROM payment_schedules s
JOIN contracts c ON c.id = s.contract_id AND c.org_id = s.org_id
WHERE s.org_id = $1 AND s.deleted_at IS NULL AND c.deleted_at IS NULL
  AND c.status IN ('ended', 'terminated')
  AND s.status IN ('pending', 'partial', 'overdue')
`

type FormerArrearsTotalRow struct {
	Outstanding int64 `json:"outstanding"`
	Contracts   int64 `json:"contracts"`
}

// FormerArrearsTotal is the headline over the same set, unpaged.
func (q *Queries) FormerArrearsTotal(ctx context.Context, orgID pgtype.UUID) (FormerArrearsTotalRow, error) {
	row := q.db.QueryRow(ctx, formerArrearsTotal, orgID)
	var i FormerArrearsTotalRow
	err := row.Scan(&i.Outstanding, &i.Contracts)
	return i, err
}

const listFormerArrears = `-- name: ListFormerArrears :many

SELECT c.id AS contract_id, c.status AS contract_status, c.renter_user_id,
       COALESCE(c.termination_effective_date, c.end_date)::date AS closed_on,
       ru.full_name AS renter_name, ru.phone AS renter_phone,
       u.id AS unit_id, u.name AS unit_name, p.id AS property_id, p.name AS property_name,
       owing.outstanding, owing.periods, owing.oldest_due,
       (SELECT max(pay.paid_at) FROM payments pay
        WHERE pay.org_id = c.org_id AND pay.contract_id = c.id
          AND pay.status <> 'reversed' AND pay.deleted_at IS NULL)::timestamptz AS last_paid_at
FROM contracts c
JOIN units u      ON u.id = c.unit_id AND u.org_id = c.org_id
JOIN properties p ON p.id = u.property_id AND p.org_id = c.org_id
JOIN users ru     ON ru.id = c.renter_user_id
JOIN LATERAL (
    SELECT COALESCE(sum(GREATEST(s.amount - s.paid_amount, 0)), 0)::bigint AS outstanding,
           count(*)::bigint AS periods,
           min(s.due_date)::date AS oldest_due
    FROM payment_schedules s
    WHERE s.org_id = c.org_id AND s.contract_id = c.id AND s.deleted_at IS NULL
      AND s.status IN ('pending', 'partial', 'overdue')
) owing ON owing.periods > 0
WHERE c.org_id = $1 AND c.deleted_at IS NULL
  AND c.status IN ('ended', 'terminated')
  AND ($2::uuid IS NULL OR p.id = $2::uuid)
  AND ($3::date IS NULL
       OR (COALESCE(c.termination_effective_date, c.end_date), c.id)
          < ($3::date, $4::uuid))
ORDER BY COALESCE(c.termination_effective_date, c.end_date) DESC, c.id DESC
LIMIT $5
`

type ListFormerArrearsParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	PropertyID pgtype.UUID `json:"property_id"`
	CursorAt   pgtype.Date `json:"cursor_at"`
	CursorID   pgtype.UUID `json:"cursor_id"`
	RowLimit   int32       `json:"row_limit"`
}

type ListFormerArrearsRow struct {
	ContractID     pgtype.UUID        `json:"contract_id"`
	ContractStatus string             `json:"contract_status"`
	RenterUserID   pgtype.UUID        `json:"renter_user_id"`
	ClosedOn       pgtype.Date        `json:"closed_on"`
	RenterName     string             `json:"renter_name"`
	RenterPhone    *string            `json:"renter_phone"`
	UnitID         pgtype.UUID        `json:"unit_id"`
	UnitName       string             `json:"unit_name"`
	PropertyID     pgtype.UUID        `json:"property_id"`
	PropertyName   string             `json:"property_name"`
	Outstanding    int64              `json:"outstanding"`
	Periods        int64              `json:"periods"`
	OldestDue      pgtype.Date        `json:"oldest_due"`
	LastPaidAt     pgtype.Timestamptz `json:"last_paid_at"`
}

// Phase 21 §21.2 — arrears after a tenancy has closed.
// ListFormerArrears is the "former tenants who still owe" board: closed
// contracts (terminated or ended) with at least one row still owing, newest
// closure first. `closed_on` is the day the tenancy stopped — the termination's
// effective date, or the end date for one that ran out.
func (q *Queries) ListFormerArrears(ctx context.Context, arg ListFormerArrearsParams) ([]ListFormerArrearsRow, error) {
	rows, err := q.db.Query(ctx, listFormerArrears,
		arg.OrgID,
		arg.PropertyID,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFormerArrearsRow{}
	for rows.Next() {
		var i ListFormerArrearsRow
		if err := rows.Scan(
			&i.ContractID,
			&i.ContractStatus,
			&i.RenterUserID,
			&i.ClosedOn,
			&i.RenterName,
			&i.RenterPhone,
			&i.UnitID,
			&i.UnitName,
			&i.PropertyID,
			&i.PropertyName,
			&i.Outstanding,
			&i.Periods,
			&i.OldestDue,
			&i.LastPaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreWrittenOff = `-- name: RestoreWrittenOff :many
UPDATE payment_schedules
SET status = CASE
        WHEN paid_amount >= amount THEN 'paid'
        WHEN due_date + $1::int < CURRENT_DATE THEN 'overdue'
        WHEN paid_amount > 0 THEN 'partial'
        ELSE 'pending'
    END,
    written_off_at = NULL, written_off_by_user_id = NULL, write_off_reason = NULL
WHERE org_id = $2 AND contract_id = $3
  AND status = 'written_off' AND deleted_at IS NULL
RETURNING id, org_id, contract_id, period_start, period_end, due_date, amount, status, created_at, updated_at, deleted_at, paid_amount, written_off_at, written_off_by_user_id, write_off_reason, original_amount, adjustment_kind, adjustment_reason, adjusted_at, adjusted_by_user_id, backfill_batch_id
`

type RestoreWrittenOffParams struct {
	GraceDays  int32       `json:"grace_days"`
	OrgID      pgtype.UUID `json:"org_id"`
	ContractID pgtype.UUID `json:"contract_id"`
}

// RestoreWrittenOff undoes a write-off: each row's status is recomputed from
// its own money and dates, the way a reversal recomputes it.
func (q *Queries) RestoreWrittenOff(ctx context.Context, arg RestoreWrittenOffParams) ([]PaymentSchedule, error) {
	rows, err := q.db.Query(ctx, restoreWrittenOff, arg.GraceDays, arg.OrgID, arg.ContractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentSchedule{}
	for rows.Next() {
		var i PaymentSchedule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ContractID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.DueDate,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PaidAmount,
			&i.WrittenOffAt,
			&i.WrittenOffByUserID,
			&i.WriteOffReason,
			&i.OriginalAmount,
			&i.AdjustmentKind,
			&i.AdjustmentReason,
			&i.AdjustedAt,
			&i.AdjustedByUserID,
			&i.BackfillBatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeOffSchedules = `-- name: WriteOffSchedules :many
UPDATE payment_schedules
SET status = 'written_off', written_off_at = now(),
    written_off_by_user_id = $1, write_off_reason = $2
WHERE org_id = $3 AND contract_id = $4
  AND status IN ('pending', 'partial', 'overdue') AND deleted_at IS NULL
RETURNING id, org_id, contract_id, period_start, period_end, due_date, amount, status, created_at, updated_at, deleted_at, paid_amount, written_off_at, written_off_by_user_id, write_off_reason, original_amount, adjustment_kind, adjustment_reason, adjusted_at, adjusted_by_user_id, backfill_batch_id
`

type WriteOffSchedulesParams struct {
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Reason      *string     `json:"reason"`
	OrgID       pgtype.UUID `json:"org_id"`
	ContractID  pgtype.UUID `json:"contract_id"`
}

// WriteOffSchedules closes every still-owing row of a contract as bad debt.
// Money already received on a partial row stays where it is.
func (q *Queries) WriteOffSchedules(ctx context.Context, arg WriteOffSchedulesParams) ([]PaymentSchedule, error) {
	rows, err := q.db.Query(ctx, writeOffSchedules,
		arg.ActorUserID,
		arg.Reason,
		arg.OrgID,
		arg.ContractID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentSchedule{}
	for rows.Next() {
		var i PaymentSchedule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ContractID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.DueDate,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PaidAmount,
			&i.WrittenOffAt,
			&i.WrittenOffByUserID,
			&i.WriteOffReason,
			&i.OriginalAmount,
			&i.AdjustmentKind,
			&i.AdjustmentReason,
			&i.AdjustedAt,
			&i.AdjustedByUserID,
			&i.BackfillBatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
