// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phase20.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const firstSchedulePeriodStart = `-- name: FirstSchedulePeriodStart :one
SELECT min(period_start)::date AS first_period_start
FROM payment_schedules
WHERE org_id = $1 AND contract_id = $2
  AND deleted_at IS NULL
`

type FirstSchedulePeriodStartParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	ContractID pgtype.UUID `json:"contract_id"`
}

// FirstSchedulePeriodStart is what the payments import compares a row's
// `paid_at` against: money dated before the rent book begins has nothing to
// settle, and the preview says so by pointing at Backfill instead of repeating
// "exceeds contract balance".
func (q *Queries) FirstSchedulePeriodStart(ctx context.Context, arg FirstSchedulePeriodStartParams) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, firstSchedulePeriodStart, arg.OrgID, arg.ContractID)
	var first_period_start pgtype.Date
	err := row.Scan(&first_period_start)
	return first_period_start, err
}

const listLastPaymentSourceForSchedules = `-- name: ListLastPaymentSourceForSchedules :many

SELECT DISTINCT ON (a.schedule_id)
       a.schedule_id, pm.source, pm.paid_at
FROM payment_allocations a
JOIN payments pm ON pm.id = a.payment_id
WHERE a.schedule_id = ANY ($1::uuid[])
  AND pm.status = 'recorded' AND pm.deleted_at IS NULL
ORDER BY a.schedule_id, pm.paid_at DESC, pm.id DESC
`

type ListLastPaymentSourceForSchedulesRow struct {
	ScheduleID pgtype.UUID        `json:"schedule_id"`
	Source     string             `json:"source"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
}

// Phase 20 §20.3 — historical payments backfill.
//
// `payments.source` (migration 000021) is written by every payment path; the
// queries here are the two things that reads need on top of it: which source
// last touched a schedule row (the "imported"/"backfilled" chip) and which rows
// a backfill has to close.
// ListLastPaymentSourceForSchedules answers the chip for a page of schedule
// rows in one round trip, the way ListAllocationsForPayments answers `applied[]`
// for a page of payments.
//
// "Last" is the newest live allocation by the payment's own `paid_at`, so a
// backdated settlement of an old period does not claim to be the newest thing
// that happened to a row the landlord has since been paid for by hand.
// Reversed and deleted payments are excluded: their money is no longer on the
// schedule, so neither is their chip.
// guard-exempt: the schedule ids were already scoped by the caller (org for the
// landlord's board, the renter's own contracts for /me/schedules).
func (q *Queries) ListLastPaymentSourceForSchedules(ctx context.Context, scheduleIds []pgtype.UUID) ([]ListLastPaymentSourceForSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listLastPaymentSourceForSchedules, scheduleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLastPaymentSourceForSchedulesRow{}
	for rows.Next() {
		var i ListLastPaymentSourceForSchedulesRow
		if err := rows.Scan(&i.ScheduleID, &i.Source, &i.PaidAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBackfillSchedules = `-- name: LockBackfillSchedules :many
SELECT id, org_id, contract_id, period_start, period_end, due_date, amount, status, created_at, updated_at, deleted_at, paid_amount, written_off_at, written_off_by_user_id, write_off_reason FROM payment_schedules
WHERE org_id = $1 AND contract_id = $2
  AND due_date <= $3 AND deleted_at IS NULL
ORDER BY due_date, period_start, id
FOR UPDATE
`

type LockBackfillSchedulesParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	ContractID pgtype.UUID `json:"contract_id"`
	Until      pgtype.Date `json:"until"`
}

// LockBackfillSchedules is the set POST /contracts/{id}/backfill works on: every
// row of the contract due on or before `until`, locked in due-date order so two
// landlords pressing the button at once cannot settle the same period twice.
//
// It returns settled rows as well as unsettled ones, because the response has to
// report how many were skipped, and "skipped" is a fact about rows that were
// already in range.
func (q *Queries) LockBackfillSchedules(ctx context.Context, arg LockBackfillSchedulesParams) ([]PaymentSchedule, error) {
	rows, err := q.db.Query(ctx, lockBackfillSchedules, arg.OrgID, arg.ContractID, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentSchedule{}
	for rows.Next() {
		var i PaymentSchedule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ContractID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.DueDate,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PaidAmount,
			&i.WrittenOffAt,
			&i.WrittenOffByUserID,
			&i.WriteOffReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const waiveSchedule = `-- name: WaiveSchedule :one
UPDATE payment_schedules SET status = 'waived'
WHERE org_id = $1 AND id = $2
  AND status IN ('pending', 'partial', 'overdue') AND deleted_at IS NULL
RETURNING id, org_id, contract_id, period_start, period_end, due_date, amount, status, created_at, updated_at, deleted_at, paid_amount, written_off_at, written_off_by_user_id, write_off_reason
`

type WaiveScheduleParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// WaiveSchedule closes one row without money, the way a termination waives the
// periods a renter will never live through. It only ever moves an unsettled row,
// so a re-run of the same backfill is a no-op rather than a second write.
func (q *Queries) WaiveSchedule(ctx context.Context, arg WaiveScheduleParams) (PaymentSchedule, error) {
	row := q.db.QueryRow(ctx, waiveSchedule, arg.OrgID, arg.ID)
	var i PaymentSchedule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ContractID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.DueDate,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PaidAmount,
		&i.WrittenOffAt,
		&i.WrittenOffByUserID,
		&i.WriteOffReason,
	)
	return i, err
}
