// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phase19.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminGetUser = `-- name: AdminGetUser :one
SELECT u.id, u.kind, u.full_name, u.phone, u.email, u.status, u.created_at,
       (SELECT count(*) FROM contracts c
        WHERE c.renter_user_id = u.id AND c.deleted_at IS NULL
          AND c.status IN ('active', 'expiring'))::bigint AS contracts_live,
       COALESCE((SELECT rp.kyc_status FROM renter_profiles rp
                 WHERE rp.user_id = u.id AND rp.deleted_at IS NULL), 'incomplete')::text AS kyc_status
FROM users u
WHERE u.id = $1 AND u.deleted_at IS NULL
`

type AdminGetUserRow struct {
	ID            pgtype.UUID        `json:"id"`
	Kind          string             `json:"kind"`
	FullName      string             `json:"full_name"`
	Phone         *string            `json:"phone"`
	Email         *string            `json:"email"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ContractsLive int64              `json:"contracts_live"`
	KycStatus     string             `json:"kyc_status"`
}

// AdminGetUser is the same row for one id, without the search predicates.
// guard-exempt: platform-admin cross-org directory.
func (q *Queries) AdminGetUser(ctx context.Context, id pgtype.UUID) (AdminGetUserRow, error) {
	row := q.db.QueryRow(ctx, adminGetUser, id)
	var i AdminGetUserRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.ContractsLive,
		&i.KycStatus,
	)
	return i, err
}

const adminListAuditForUser = `-- name: AdminListAuditForUser :many
SELECT a.id, a.org_id, a.actor_user_id, a.action, a.entity_type, a.entity_id,
       a.before, a.after, a.ip, a.user_agent, a.at,
       au.full_name AS actor_name,
       COALESCE(o.name, '')::text AS org_name
FROM audit_log a
LEFT JOIN users au ON au.id = a.actor_user_id
LEFT JOIN orgs o   ON o.id = a.org_id
WHERE (a.actor_user_id = $1
       OR (a.entity_type = 'user' AND a.entity_id = $1))
  AND ($2::timestamptz IS NULL
       OR (a.at, a.id) < ($2::timestamptz, $3::uuid))
ORDER BY a.at DESC, a.id DESC
LIMIT $4
`

type AdminListAuditForUserParams struct {
	UserID   pgtype.UUID        `json:"user_id"`
	CursorAt pgtype.Timestamptz `json:"cursor_at"`
	CursorID pgtype.UUID        `json:"cursor_id"`
	RowLimit int32              `json:"row_limit"`
}

type AdminListAuditForUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Before      []byte             `json:"before"`
	After       []byte             `json:"after"`
	Ip          *string            `json:"ip"`
	UserAgent   *string            `json:"user_agent"`
	At          pgtype.Timestamptz `json:"at"`
	ActorName   *string            `json:"actor_name"`
	OrgName     string             `json:"org_name"`
}

// AdminListAuditForUser is every row where this person is the actor *or* the
// subject: "what did they do" and "what was done to them" are the same question
// on a support call, and splitting them into two lists would hide the half the
// operator did not think to open.
// guard-exempt: platform-admin cross-org audit read.
func (q *Queries) AdminListAuditForUser(ctx context.Context, arg AdminListAuditForUserParams) ([]AdminListAuditForUserRow, error) {
	rows, err := q.db.Query(ctx, adminListAuditForUser,
		arg.UserID,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAuditForUserRow{}
	for rows.Next() {
		var i AdminListAuditForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.Ip,
			&i.UserAgent,
			&i.At,
			&i.ActorName,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many

SELECT u.id, u.kind, u.full_name, u.phone, u.email, u.status, u.created_at,
       (SELECT count(*) FROM contracts c
        WHERE c.renter_user_id = u.id AND c.deleted_at IS NULL
          AND c.status IN ('active', 'expiring'))::bigint AS contracts_live,
       COALESCE((SELECT rp.kyc_status FROM renter_profiles rp
                 WHERE rp.user_id = u.id AND rp.deleted_at IS NULL), 'incomplete')::text AS kyc_status
FROM users u
WHERE u.deleted_at IS NULL
  AND ($1::text IS NULL OR u.kind = $1::text)
  AND ($2::text IS NULL OR u.status = $2::text)
  AND ($3::text IS NULL
       OR u.full_name ILIKE $3::text || '%'
       OR lower(COALESCE(u.email, '')) LIKE lower($3::text) || '%'
       OR ($4::text IS NOT NULL
           AND COALESCE(u.phone, '') LIKE $4::text || '%'))
  AND ($5::uuid IS NULL
       OR EXISTS (SELECT 1 FROM org_members m
                  WHERE m.user_id = u.id AND m.org_id = $5::uuid AND m.deleted_at IS NULL)
       OR EXISTS (SELECT 1 FROM unit_link_requests lr
                  WHERE lr.renter_user_id = u.id AND lr.org_id = $5::uuid
                    AND lr.deleted_at IS NULL)
       OR EXISTS (SELECT 1 FROM contracts c2
                  WHERE c2.renter_user_id = u.id AND c2.org_id = $5::uuid
                    AND c2.deleted_at IS NULL))
  AND ($6::timestamptz IS NULL
       OR (u.created_at, u.id) < ($6::timestamptz, $7::uuid))
ORDER BY u.created_at DESC, u.id DESC
LIMIT $8
`

type AdminListUsersParams struct {
	Kind     *string            `json:"kind"`
	Status   *string            `json:"status"`
	Q        *string            `json:"q"`
	Phone    *string            `json:"phone"`
	OrgID    pgtype.UUID        `json:"org_id"`
	CursorAt pgtype.Timestamptz `json:"cursor_at"`
	CursorID pgtype.UUID        `json:"cursor_id"`
	RowLimit int32              `json:"row_limit"`
}

type AdminListUsersRow struct {
	ID            pgtype.UUID        `json:"id"`
	Kind          string             `json:"kind"`
	FullName      string             `json:"full_name"`
	Phone         *string            `json:"phone"`
	Email         *string            `json:"email"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ContractsLive int64              `json:"contracts_live"`
	KycStatus     string             `json:"kyc_status"`
}

// ---------------------------------------------- 19.2 platform user directory --
// AdminListUsers is the support desk's first question: who is this phone
// number. It crosses orgs by design and is reachable only behind
// auth.RequireAdmin.
//
// `q` is matched three ways at once because a caller pastes whatever the person
// on the telephone reads out: a phone (already normalised to +255… by the
// handler, so this is a prefix on the stored form), an e-mail (lower-cased
// prefix) or a name (ILIKE prefix). It is never a leading-wildcard search —
// that would table-scan every user on the platform for every keystroke.
//
// No NIDA column appears here, masked or otherwise (SPEC §8): the list is a
// search result, and a number nobody asked for must not travel in one.
// guard-exempt: platform-admin cross-org directory (SPEC §5.10).
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.Kind,
		arg.Status,
		arg.Q,
		arg.Phone,
		arg.OrgID,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListUsersRow{}
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.Status,
			&i.CreatedAt,
			&i.ContractsLive,
			&i.KycStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetUserStatus = `-- name: AdminSetUserStatus :one
UPDATE users SET status = $1
WHERE id = $2 AND deleted_at IS NULL AND status <> $1
RETURNING id, kind, phone, email, full_name, pin_hash, password_hash, email_verified_at, status, created_at, updated_at, deleted_at, locale
`

type AdminSetUserStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

// AdminSetUserStatus is the suspension switch. It only ever moves a row that is
// not already in the target state, so a second suspend finds no row and the
// handler answers 409 rather than writing a second audit row for nothing.
// guard-exempt: platform-admin cross-org write (SPEC §5.10).
func (q *Queries) AdminSetUserStatus(ctx context.Context, arg AdminSetUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, adminSetUserStatus, arg.Status, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.PinHash,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Locale,
	)
	return i, err
}

const adminUserContracts = `-- name: AdminUserContracts :many
SELECT c.id, c.org_id, o.name AS org_name, un.name AS unit_name, p.name AS property_name,
       c.status, c.start_date, c.end_date, c.rent_amount, c.created_at
FROM contracts c
JOIN orgs o       ON o.id = c.org_id
JOIN units un     ON un.id = c.unit_id
JOIN properties p ON p.id = un.property_id
WHERE c.renter_user_id = $1 AND c.deleted_at IS NULL
ORDER BY c.start_date DESC, c.id DESC
`

type AdminUserContractsRow struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	OrgName      string             `json:"org_name"`
	UnitName     string             `json:"unit_name"`
	PropertyName string             `json:"property_name"`
	Status       string             `json:"status"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	RentAmount   int64              `json:"rent_amount"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// AdminUserContracts lists every tenancy of this renter across the platform.
// guard-exempt: platform-admin cross-org directory.
func (q *Queries) AdminUserContracts(ctx context.Context, userID pgtype.UUID) ([]AdminUserContractsRow, error) {
	rows, err := q.db.Query(ctx, adminUserContracts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUserContractsRow{}
	for rows.Next() {
		var i AdminUserContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OrgName,
			&i.UnitName,
			&i.PropertyName,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.RentAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUserLinkRequests = `-- name: AdminUserLinkRequests :many
SELECT lr.id, lr.org_id, o.name AS org_name, lr.unit_id, un.name AS unit_name,
       p.name AS property_name, lr.status, lr.rejection_reason,
       lr.start_date, lr.end_date, lr.created_at
FROM unit_link_requests lr
JOIN orgs o        ON o.id = lr.org_id
JOIN units un      ON un.id = lr.unit_id
JOIN properties p  ON p.id = un.property_id
WHERE lr.renter_user_id = $1 AND lr.deleted_at IS NULL
ORDER BY lr.created_at DESC, lr.id DESC
LIMIT $2
`

type AdminUserLinkRequestsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	RowLimit int32       `json:"row_limit"`
}

type AdminUserLinkRequestsRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	OrgName         string             `json:"org_name"`
	UnitID          pgtype.UUID        `json:"unit_id"`
	UnitName        string             `json:"unit_name"`
	PropertyName    string             `json:"property_name"`
	Status          string             `json:"status"`
	RejectionReason *string            `json:"rejection_reason"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// AdminUserLinkRequests is the detail page's tenancy history, newest first.
// guard-exempt: platform-admin cross-org directory.
func (q *Queries) AdminUserLinkRequests(ctx context.Context, arg AdminUserLinkRequestsParams) ([]AdminUserLinkRequestsRow, error) {
	rows, err := q.db.Query(ctx, adminUserLinkRequests, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUserLinkRequestsRow{}
	for rows.Next() {
		var i AdminUserLinkRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OrgName,
			&i.UnitID,
			&i.UnitName,
			&i.PropertyName,
			&i.Status,
			&i.RejectionReason,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUserMemberships = `-- name: AdminUserMemberships :many
SELECT m.id, m.org_id, o.name AS org_name, o.status AS org_status, m.role, m.status, m.created_at
FROM org_members m
JOIN orgs o ON o.id = m.org_id
WHERE m.user_id = $1 AND m.deleted_at IS NULL
ORDER BY m.created_at, m.id
`

type AdminUserMembershipsRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	OrgName   string             `json:"org_name"`
	OrgStatus string             `json:"org_status"`
	Role      string             `json:"role"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// AdminUserMemberships is the org_user half of the detail page.
// guard-exempt: platform-admin cross-org directory.
func (q *Queries) AdminUserMemberships(ctx context.Context, userID pgtype.UUID) ([]AdminUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, adminUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUserMembershipsRow{}
	for rows.Next() {
		var i AdminUserMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.OrgName,
			&i.OrgStatus,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUserOrgs = `-- name: AdminUserOrgs :many
SELECT x.user_id, x.org_id, o.name AS org_name, o.status AS org_status,
       COALESCE(max(x.role), '')::text AS role,
       COALESCE(CASE WHEN bool_or(x.live) THEN 'renting'
                     WHEN bool_or(x.ended) THEN 'past'
                     WHEN bool_or(x.applied) THEN 'applied'
                     ELSE NULL END, '')::text AS relationship
FROM (
    SELECT m.user_id, m.org_id, m.role,
           FALSE AS live, FALSE AS ended, FALSE AS applied
    FROM org_members m
    WHERE m.user_id = ANY ($1::uuid[]) AND m.deleted_at IS NULL
    UNION ALL
    SELECT c.renter_user_id, c.org_id, NULL::text,
           c.status IN ('active', 'expiring', 'pending_signature'),
           c.status IN ('ended', 'terminated'), FALSE
    FROM contracts c
    WHERE c.renter_user_id = ANY ($1::uuid[]) AND c.deleted_at IS NULL
    UNION ALL
    SELECT lr.renter_user_id, lr.org_id, NULL::text, FALSE, FALSE, TRUE
    FROM unit_link_requests lr
    WHERE lr.renter_user_id = ANY ($1::uuid[]) AND lr.deleted_at IS NULL
) x
JOIN orgs o ON o.id = x.org_id AND o.deleted_at IS NULL
GROUP BY x.user_id, x.org_id, o.name, o.status
ORDER BY o.name, x.org_id
`

type AdminUserOrgsRow struct {
	UserID       pgtype.UUID `json:"user_id"`
	OrgID        pgtype.UUID `json:"org_id"`
	OrgName      string      `json:"org_name"`
	OrgStatus    string      `json:"org_status"`
	Role         string      `json:"role"`
	Relationship string      `json:"relationship"`
}

// AdminUserOrgs is the `orgs[]` block of a directory row: one row per org this
// person is connected to, from either side of the platform. `role` is set for a
// member; `relationship` is set for a renter and says which of the three states
// the tenancy is in — `renting` (a live contract), `past` (a finished one) or
// `applied` (a link request and nothing more).
//
// It takes an array of user ids so one page of the directory costs one round
// trip rather than one per row.
// guard-exempt: platform-admin cross-org directory.
func (q *Queries) AdminUserOrgs(ctx context.Context, userIds []pgtype.UUID) ([]AdminUserOrgsRow, error) {
	rows, err := q.db.Query(ctx, adminUserOrgs, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUserOrgsRow{}
	for rows.Next() {
		var i AdminUserOrgsRow
		if err := rows.Scan(
			&i.UserID,
			&i.OrgID,
			&i.OrgName,
			&i.OrgStatus,
			&i.Role,
			&i.Relationship,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUserPaymentsSummary = `-- name: AdminUserPaymentsSummary :one
SELECT count(*)::bigint AS count,
       COALESCE(sum(pm.amount), 0)::bigint AS total,
       max(pm.paid_at) AS last_paid_at
FROM payments pm
JOIN contracts c ON c.id = pm.contract_id
WHERE c.renter_user_id = $1
  AND pm.status = 'recorded' AND pm.deleted_at IS NULL
`

type AdminUserPaymentsSummaryRow struct {
	Count      int64       `json:"count"`
	Total      int64       `json:"total"`
	LastPaidAt interface{} `json:"last_paid_at"`
}

// AdminUserPaymentsSummary is the money line of the detail page: what this
// renter has actually paid, anywhere. Reversed rows are excluded — the summary
// answers "how much has reached a landlord", and a reversal took it back.
// guard-exempt: platform-admin cross-org directory.
func (q *Queries) AdminUserPaymentsSummary(ctx context.Context, userID pgtype.UUID) (AdminUserPaymentsSummaryRow, error) {
	row := q.db.QueryRow(ctx, adminUserPaymentsSummary, userID)
	var i AdminUserPaymentsSummaryRow
	err := row.Scan(&i.Count, &i.Total, &i.LastPaidAt)
	return i, err
}

const listNidaRevealsForUser = `-- name: ListNidaRevealsForUser :many


SELECT a.at, COALESCE(a.after->>'actor_kind', '')::text AS actor_kind,
       COALESCE(o.name, '')::text AS org_name
FROM audit_log a
LEFT JOIN orgs o ON o.id = a.org_id
WHERE a.entity_type = 'user' AND a.entity_id = $1
  AND a.action = 'renter.nida_reveal'
ORDER BY a.at DESC, a.id DESC
LIMIT $2
`

type ListNidaRevealsForUserParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	RowLimit int32       `json:"row_limit"`
}

type ListNidaRevealsForUserRow struct {
	At        pgtype.Timestamptz `json:"at"`
	ActorKind string             `json:"actor_kind"`
	OrgName   string             `json:"org_name"`
}

// Phase 19 — NIDA reveal, the platform user directory, name corrections.
//
// The reveal itself needs no query of its own: it reads the profile through the
// existing GetRenterProfileDecrypted and the relationship through GetOrgRenter,
// which is the one place that decides what "a renter this org knows" means.
// What is new here is the renter's own view of who looked, the signed-contract
// guard on a landlord rename, and the cross-org directory the platform admin
// searches.
// ------------------------------------------------ 19.1 who has seen my NIDA --
// ListNidaRevealsForUser is the renter's own deterrent: every reveal of their
// number, newest first, read straight off the append-only trail rather than
// from a second table that could disagree with it. The `reason` an actor typed
// is deliberately not selected — it is the org's note to itself, and the renter
// is told who looked and when, not what the landlord wrote about them.
// guard-exempt: the renter's own audit rows, keyed by entity_id = their user id.
func (q *Queries) ListNidaRevealsForUser(ctx context.Context, arg ListNidaRevealsForUserParams) ([]ListNidaRevealsForUserRow, error) {
	rows, err := q.db.Query(ctx, listNidaRevealsForUser, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNidaRevealsForUserRow{}
	for rows.Next() {
		var i ListNidaRevealsForUserRow
		if err := rows.Scan(&i.At, &i.ActorKind, &i.OrgName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renterHasSignedAnywhere = `-- name: RenterHasSignedAnywhere :one

SELECT EXISTS (
    SELECT 1 FROM contract_signatures
    WHERE user_id = $1 AND party = 'renter'
) AS signed
`

// ------------------------------------------------------ 19.3 name corrections --
// RenterHasSignedAnywhere is the guard on PATCH /renters/{user_id}: a landlord
// may fix a typo only before the renter has put their name to anything. It
// crosses orgs on purpose — a signature with another landlord is still this
// renter's own act, and the name on it is theirs to correct from their Profile.
// guard-exempt: deliberately cross-org — a signature anywhere blocks the rename.
func (q *Queries) RenterHasSignedAnywhere(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, renterHasSignedAnywhere, userID)
	var signed bool
	err := row.Scan(&signed)
	return signed, err
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :many
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
RETURNING token_hash
`

// RevokeSessionsForUser revokes every live session of one account, whichever
// audience or org it was issued for: a suspended person must be out of the
// product, not merely out of one tenant. The returned hashes let the caller
// evict the Redis copies after the commit.
// guard-exempt: platform-admin cross-org write; the subject is the user id.
func (q *Queries) RevokeSessionsForUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, revokeSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var token_hash string
		if err := rows.Scan(&token_hash); err != nil {
			return nil, err
		}
		items = append(items, token_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrgMemberRole = `-- name: SetOrgMemberRole :one
UPDATE org_members SET role = $1
WHERE org_id = $2 AND id = $3 AND deleted_at IS NULL
RETURNING id, org_id, user_id, role, status, created_at, updated_at, deleted_at
`

type SetOrgMemberRoleParams struct {
	Role  string      `json:"role"`
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// SetOrgMemberRole backs the role half of PATCH /org/members/{id}. The
// last-owner check runs in the handler against CountActiveOwners inside the
// same transaction, so a concurrent demotion cannot empty an org of owners.
func (q *Queries) SetOrgMemberRole(ctx context.Context, arg SetOrgMemberRoleParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, setOrgMemberRole, arg.Role, arg.OrgID, arg.ID)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setRenterProfileFullName = `-- name: SetRenterProfileFullName :one
UPDATE renter_profiles SET full_name = $1
WHERE user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, full_name, nida_number_enc, next_of_kin_name, next_of_kin_phone, kyc_status, kyc_doc_object_key, created_at, updated_at, deleted_at
`

type SetRenterProfileFullNameParams struct {
	FullName string      `json:"full_name"`
	UserID   pgtype.UUID `json:"user_id"`
}

// SetRenterProfileFullName writes the profile half of a rename. The users half
// goes through the existing SetUserFullName, so both callers write the same two
// rows in the same transaction.
func (q *Queries) SetRenterProfileFullName(ctx context.Context, arg SetRenterProfileFullNameParams) (RenterProfile, error) {
	row := q.db.QueryRow(ctx, setRenterProfileFullName, arg.FullName, arg.UserID)
	var i RenterProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.NidaNumberEnc,
		&i.NextOfKinName,
		&i.NextOfKinPhone,
		&i.KycStatus,
		&i.KycDocObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
