// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phase29.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSchedulesBeforeStart = `-- name: CountSchedulesBeforeStart :one
SELECT count(*)::int AS n
FROM payment_schedules s
JOIN contracts c ON c.id = s.contract_id
WHERE s.org_id = $1 AND s.contract_id = $2
  AND s.period_start < c.start_date AND s.deleted_at IS NULL
`

type CountSchedulesBeforeStartParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	ContractID pgtype.UUID `json:"contract_id"`
}

// CountSchedulesBeforeStart says whether a contract already has periods before
// its start date — written by an earlier backfill. A second `from` would
// overlap them, so it is refused; `until` alone can still settle them.
func (q *Queries) CountSchedulesBeforeStart(ctx context.Context, arg CountSchedulesBeforeStartParams) (int32, error) {
	row := q.db.QueryRow(ctx, countSchedulesBeforeStart, arg.OrgID, arg.ContractID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const createBackfillHistorySchedule = `-- name: CreateBackfillHistorySchedule :one

INSERT INTO payment_schedules (
    org_id, contract_id, period_start, period_end, due_date, amount, status, created_by_backfill_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6,
    CASE WHEN $5::date + $7::int < CURRENT_DATE
         THEN 'overdue' ELSE 'pending' END,
    $8
)
RETURNING id, org_id, contract_id, period_start, period_end, due_date, amount, status, created_at, updated_at, deleted_at, paid_amount, written_off_at, written_off_by_user_id, write_off_reason, original_amount, adjustment_kind, adjustment_reason, adjusted_at, adjusted_by_user_id, backfill_batch_id, created_by_backfill_id
`

type CreateBackfillHistoryScheduleParams struct {
	OrgID               pgtype.UUID `json:"org_id"`
	ContractID          pgtype.UUID `json:"contract_id"`
	PeriodStart         pgtype.Date `json:"period_start"`
	PeriodEnd           pgtype.Date `json:"period_end"`
	DueDate             pgtype.Date `json:"due_date"`
	Amount              int64       `json:"amount"`
	GraceDays           int32       `json:"grace_days"`
	CreatedByBackfillID pgtype.UUID `json:"created_by_backfill_id"`
}

// Phase 29 — a backfill that reaches back before the contract's start date
// writes the missing periods itself, and its undo removes them again.
// CreateBackfillHistorySchedule writes one period that predates the contract.
// Its status is what the book would say had it existed all along: overdue
// once past due and grace, pending otherwise. The backfill then settles the
// ones up to `until` in the same transaction.
func (q *Queries) CreateBackfillHistorySchedule(ctx context.Context, arg CreateBackfillHistoryScheduleParams) (PaymentSchedule, error) {
	row := q.db.QueryRow(ctx, createBackfillHistorySchedule,
		arg.OrgID,
		arg.ContractID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.DueDate,
		arg.Amount,
		arg.GraceDays,
		arg.CreatedByBackfillID,
	)
	var i PaymentSchedule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ContractID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.DueDate,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PaidAmount,
		&i.WrittenOffAt,
		&i.WrittenOffByUserID,
		&i.WriteOffReason,
		&i.OriginalAmount,
		&i.AdjustmentKind,
		&i.AdjustmentReason,
		&i.AdjustedAt,
		&i.AdjustedByUserID,
		&i.BackfillBatchID,
		&i.CreatedByBackfillID,
	)
	return i, err
}

const deleteBackfillCreatedSchedules = `-- name: DeleteBackfillCreatedSchedules :execrows
UPDATE payment_schedules SET deleted_at = now()
WHERE org_id = $1 AND created_by_backfill_id = $2
  AND deleted_at IS NULL
`

type DeleteBackfillCreatedSchedulesParams struct {
	OrgID               pgtype.UUID `json:"org_id"`
	CreatedByBackfillID pgtype.UUID `json:"created_by_backfill_id"`
}

// DeleteBackfillCreatedSchedules is the undo's last step: the periods the
// batch wrote go away with it. Soft delete, so the reversed payments that
// pointed at them still resolve.
func (q *Queries) DeleteBackfillCreatedSchedules(ctx context.Context, arg DeleteBackfillCreatedSchedulesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackfillCreatedSchedules, arg.OrgID, arg.CreatedByBackfillID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
