// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phase24.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadInbox = `-- name: CountUnreadInbox :one
SELECT count(*)::bigint FROM org_inbox n
WHERE n.org_id = $1
  AND NOT EXISTS (SELECT 1 FROM org_inbox_reads r
                  WHERE r.notification_id = n.id AND r.user_id = $2)
`

type CountUnreadInboxParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CountUnreadInbox(ctx context.Context, arg CountUnreadInboxParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadInbox, arg.OrgID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInboxItem = `-- name: CreateInboxItem :one

INSERT INTO org_inbox (org_id, kind, title, body, entity_type, entity_id, link, actor_user_id)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
RETURNING id
`

type CreateInboxItemParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	Kind        string      `json:"kind"`
	Title       string      `json:"title"`
	Body        string      `json:"body"`
	EntityType  *string     `json:"entity_type"`
	EntityID    pgtype.UUID `json:"entity_id"`
	Link        *string     `json:"link"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
}

// ------------------------------------------------------ landlord notices --
func (q *Queries) CreateInboxItem(ctx context.Context, arg CreateInboxItemParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createInboxItem,
		arg.OrgID,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.EntityType,
		arg.EntityID,
		arg.Link,
		arg.ActorUserID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listInbox = `-- name: ListInbox :many
SELECT n.id, n.org_id, n.kind, n.title, n.body, n.entity_type, n.entity_id, n.link, n.actor_user_id, n.created_at, (r.read_at IS NOT NULL)::bool AS read
FROM org_inbox n
LEFT JOIN org_inbox_reads r ON r.notification_id = n.id AND r.user_id = $1
WHERE n.org_id = $2
  AND ($3::timestamptz IS NULL
       OR (n.created_at, n.id) < ($3::timestamptz, $4::uuid))
ORDER BY n.created_at DESC, n.id DESC
LIMIT $5
`

type ListInboxParams struct {
	UserID   pgtype.UUID        `json:"user_id"`
	OrgID    pgtype.UUID        `json:"org_id"`
	CursorAt pgtype.Timestamptz `json:"cursor_at"`
	CursorID pgtype.UUID        `json:"cursor_id"`
	RowLimit int32              `json:"row_limit"`
}

type ListInboxRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Kind        string             `json:"kind"`
	Title       string             `json:"title"`
	Body        string             `json:"body"`
	EntityType  *string            `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Link        *string            `json:"link"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Read        bool               `json:"read"`
}

func (q *Queries) ListInbox(ctx context.Context, arg ListInboxParams) ([]ListInboxRow, error) {
	rows, err := q.db.Query(ctx, listInbox,
		arg.UserID,
		arg.OrgID,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInboxRow{}
	for rows.Next() {
		var i ListInboxRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.EntityType,
			&i.EntityID,
			&i.Link,
			&i.ActorUserID,
			&i.CreatedAt,
			&i.Read,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInboxRead = `-- name: MarkInboxRead :exec
INSERT INTO org_inbox_reads (notification_id, user_id, org_id)
SELECT n.id, $1, n.org_id FROM org_inbox n
WHERE n.org_id = $2
  AND ($3::bool OR n.id = ANY($4::uuid[]))
ON CONFLICT DO NOTHING
`

type MarkInboxReadParams struct {
	UserID pgtype.UUID   `json:"user_id"`
	OrgID  pgtype.UUID   `json:"org_id"`
	AllIds bool          `json:"all_ids"`
	Ids    []pgtype.UUID `json:"ids"`
}

func (q *Queries) MarkInboxRead(ctx context.Context, arg MarkInboxReadParams) error {
	_, err := q.db.Exec(ctx, markInboxRead,
		arg.UserID,
		arg.OrgID,
		arg.AllIds,
		arg.Ids,
	)
	return err
}

const paymentByIdempotencyKey = `-- name: PaymentByIdempotencyKey :one
SELECT id FROM payments WHERE org_id = $1 AND idempotency_key = $2
`

type PaymentByIdempotencyKeyParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Key   *string     `json:"key"`
}

func (q *Queries) PaymentByIdempotencyKey(ctx context.Context, arg PaymentByIdempotencyKeyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, paymentByIdempotencyKey, arg.OrgID, arg.Key)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const possibleDuplicates = `-- name: PossibleDuplicates :many

SELECT p.id, p.contract_id, p.amount, p.paid_at, p.method, p.reference, p.created_at
FROM payments p
WHERE p.org_id = $1 AND p.deleted_at IS NULL AND p.status <> 'reversed'
  AND (
    (p.contract_id = $2 AND p.amount = $3
     AND p.paid_at BETWEEN $4::timestamptz - interval '3 days'
                       AND $4::timestamptz + interval '3 days')
    OR ($5::text IS NOT NULL
        AND lower(p.reference) = lower($5::text)
        AND p.paid_at >= $4::timestamptz - interval '90 days')
  )
ORDER BY p.paid_at DESC
LIMIT 5
`

type PossibleDuplicatesParams struct {
	OrgID      pgtype.UUID        `json:"org_id"`
	ContractID pgtype.UUID        `json:"contract_id"`
	Amount     int64              `json:"amount"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	Reference  *string            `json:"reference"`
}

type PossibleDuplicatesRow struct {
	ID         pgtype.UUID        `json:"id"`
	ContractID pgtype.UUID        `json:"contract_id"`
	Amount     int64              `json:"amount"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	Method     string             `json:"method"`
	Reference  *string            `json:"reference"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Phase 24 — payment corrections and landlord notices.
// PossibleDuplicates: live payments on the same contract for the same amount
// within three days, or anywhere in the org with the same reference in the
// last 90 days.
func (q *Queries) PossibleDuplicates(ctx context.Context, arg PossibleDuplicatesParams) ([]PossibleDuplicatesRow, error) {
	rows, err := q.db.Query(ctx, possibleDuplicates,
		arg.OrgID,
		arg.ContractID,
		arg.Amount,
		arg.PaidAt,
		arg.Reference,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PossibleDuplicatesRow{}
	for rows.Next() {
		var i PossibleDuplicatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.Amount,
			&i.PaidAt,
			&i.Method,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentExtras = `-- name: SetPaymentExtras :exec
UPDATE payments SET idempotency_key = $1, corrects_payment_id = $2
WHERE org_id = $3 AND id = $4
`

type SetPaymentExtrasParams struct {
	IdempotencyKey    *string     `json:"idempotency_key"`
	CorrectsPaymentID pgtype.UUID `json:"corrects_payment_id"`
	OrgID             pgtype.UUID `json:"org_id"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) SetPaymentExtras(ctx context.Context, arg SetPaymentExtrasParams) error {
	_, err := q.db.Exec(ctx, setPaymentExtras,
		arg.IdempotencyKey,
		arg.CorrectsPaymentID,
		arg.OrgID,
		arg.ID,
	)
	return err
}
