// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phase28.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectionScenarios = `-- name: CountProjectionScenarios :one
SELECT count(*) FROM projection_scenarios WHERE org_id = $1
`

func (q *Queries) CountProjectionScenarios(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectionScenarios, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProjectionScenario = `-- name: CreateProjectionScenario :one
INSERT INTO projection_scenarios (
    org_id, name, horizon_months, basis, unit_ids, rent_change_pct,
    collection_rate_pct, expense_change_pct, created_by_user_id
) VALUES (
    $1, $2, $3, $4,
    $5::uuid[], $6,
    $7, $8,
    $9
)
RETURNING id, org_id, name, horizon_months, rent_change_pct, collection_rate_pct, expense_change_pct, created_by_user_id, created_at, basis, unit_ids
`

type CreateProjectionScenarioParams struct {
	OrgID             pgtype.UUID   `json:"org_id"`
	Name              string        `json:"name"`
	HorizonMonths     int32         `json:"horizon_months"`
	Basis             string        `json:"basis"`
	UnitIds           []pgtype.UUID `json:"unit_ids"`
	RentChangePct     float64       `json:"rent_change_pct"`
	CollectionRatePct *float64      `json:"collection_rate_pct"`
	ExpenseChangePct  float64       `json:"expense_change_pct"`
	CreatedByUserID   pgtype.UUID   `json:"created_by_user_id"`
}

func (q *Queries) CreateProjectionScenario(ctx context.Context, arg CreateProjectionScenarioParams) (ProjectionScenario, error) {
	row := q.db.QueryRow(ctx, createProjectionScenario,
		arg.OrgID,
		arg.Name,
		arg.HorizonMonths,
		arg.Basis,
		arg.UnitIds,
		arg.RentChangePct,
		arg.CollectionRatePct,
		arg.ExpenseChangePct,
		arg.CreatedByUserID,
	)
	var i ProjectionScenario
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.HorizonMonths,
		&i.RentChangePct,
		&i.CollectionRatePct,
		&i.ExpenseChangePct,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.Basis,
		&i.UnitIds,
	)
	return i, err
}

const deleteProjectionScenario = `-- name: DeleteProjectionScenario :one
DELETE FROM projection_scenarios
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, name, horizon_months, rent_change_pct, collection_rate_pct, expense_change_pct, created_by_user_id, created_at, basis, unit_ids
`

type DeleteProjectionScenarioParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteProjectionScenario(ctx context.Context, arg DeleteProjectionScenarioParams) (ProjectionScenario, error) {
	row := q.db.QueryRow(ctx, deleteProjectionScenario, arg.OrgID, arg.ID)
	var i ProjectionScenario
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.HorizonMonths,
		&i.RentChangePct,
		&i.CollectionRatePct,
		&i.ExpenseChangePct,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.Basis,
		&i.UnitIds,
	)
	return i, err
}

const listProjectionScenarios = `-- name: ListProjectionScenarios :many

SELECT id, org_id, name, horizon_months, rent_change_pct, collection_rate_pct, expense_change_pct, created_by_user_id, created_at, basis, unit_ids FROM projection_scenarios
WHERE org_id = $1
ORDER BY lower(name), id
`

// ------------------------------------------------------ saved scenarios --
func (q *Queries) ListProjectionScenarios(ctx context.Context, orgID pgtype.UUID) ([]ProjectionScenario, error) {
	rows, err := q.db.Query(ctx, listProjectionScenarios, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectionScenario{}
	for rows.Next() {
		var i ProjectionScenario
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.HorizonMonths,
			&i.RentChangePct,
			&i.CollectionRatePct,
			&i.ExpenseChangePct,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.Basis,
			&i.UnitIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectionCollectedMonthly = `-- name: ProjectionCollectedMonthly :many
SELECT u.property_id AS property_id,
       date_trunc('month', p.paid_at AT TIME ZONE 'Africa/Dar_es_Salaam')::date AS month,
       COALESCE(sum(p.amount), 0)::bigint AS amount
FROM payments p
JOIN contracts c ON c.id = p.contract_id AND c.org_id = p.org_id
JOIN units u     ON u.id = c.unit_id AND u.org_id = c.org_id
WHERE p.org_id = $1 AND p.deleted_at IS NULL AND p.status <> 'reversed'
  AND NOT c.is_offline
  AND p.paid_at < $2
  AND ($3::uuid IS NULL OR u.property_id = $3::uuid)
GROUP BY 1, 2
`

type ProjectionCollectedMonthlyParams struct {
	OrgID      pgtype.UUID        `json:"org_id"`
	ToTs       pgtype.Timestamptz `json:"to_ts"`
	PropertyID pgtype.UUID        `json:"property_id"`
}

type ProjectionCollectedMonthlyRow struct {
	PropertyID pgtype.UUID `json:"property_id"`
	Month      pgtype.Date `json:"month"`
	Amount     int64       `json:"amount"`
}

// ProjectionCollectedMonthly is the whole cash history, per property and
// month, before refunds (ProjectionRefundedMonthly is subtracted in Go, as
// phase22_cash.go does for every other cash report).
func (q *Queries) ProjectionCollectedMonthly(ctx context.Context, arg ProjectionCollectedMonthlyParams) ([]ProjectionCollectedMonthlyRow, error) {
	rows, err := q.db.Query(ctx, projectionCollectedMonthly, arg.OrgID, arg.ToTs, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectionCollectedMonthlyRow{}
	for rows.Next() {
		var i ProjectionCollectedMonthlyRow
		if err := rows.Scan(&i.PropertyID, &i.Month, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectionExpectedMonthly = `-- name: ProjectionExpectedMonthly :many
SELECT u.property_id AS property_id,
       date_trunc('month', s.due_date)::date AS month,
       COALESCE(sum(s.amount), 0)::bigint AS amount
FROM payment_schedules s
JOIN contracts c ON c.id = s.contract_id AND c.org_id = s.org_id
JOIN units u     ON u.id = c.unit_id AND u.org_id = c.org_id
WHERE s.org_id = $1 AND s.deleted_at IS NULL AND s.status <> 'waived'
  AND NOT c.is_offline
  AND s.due_date >= $2 AND s.due_date < $3
  AND ($4::uuid IS NULL OR u.property_id = $4::uuid)
GROUP BY 1, 2
`

type ProjectionExpectedMonthlyParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type ProjectionExpectedMonthlyRow struct {
	PropertyID pgtype.UUID `json:"property_id"`
	Month      pgtype.Date `json:"month"`
	Amount     int64       `json:"amount"`
}

// ProjectionExpectedMonthly is what fell due, per property and month, over
// the trailing window: the denominator of the collection rate.
func (q *Queries) ProjectionExpectedMonthly(ctx context.Context, arg ProjectionExpectedMonthlyParams) ([]ProjectionExpectedMonthlyRow, error) {
	rows, err := q.db.Query(ctx, projectionExpectedMonthly,
		arg.OrgID,
		arg.FromDate,
		arg.ToDate,
		arg.PropertyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectionExpectedMonthlyRow{}
	for rows.Next() {
		var i ProjectionExpectedMonthlyRow
		if err := rows.Scan(&i.PropertyID, &i.Month, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectionExpensesMonthly = `-- name: ProjectionExpensesMonthly :many
SELECT e.property_id AS property_id,
       e.category_id AS category_id,
       COALESCE(ec.name, '')::text AS category_name,
       COALESCE(ec.is_capital, false)::boolean AS is_capital,
       date_trunc('month', e.incurred_on)::date AS month,
       COALESCE(sum(e.amount), 0)::bigint AS amount
FROM expenses e
LEFT JOIN expense_categories ec ON ec.id = e.category_id AND ec.org_id = e.org_id
WHERE e.org_id = $1 AND e.deleted_at IS NULL AND e.status = 'recorded'
  AND e.incurred_on < $2
  AND ($3::uuid IS NULL OR e.property_id = $3::uuid)
GROUP BY 1, 2, 3, 4, 5
`

type ProjectionExpensesMonthlyParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	ToDate     pgtype.Date `json:"to_date"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type ProjectionExpensesMonthlyRow struct {
	PropertyID   pgtype.UUID `json:"property_id"`
	CategoryID   pgtype.UUID `json:"category_id"`
	CategoryName string      `json:"category_name"`
	IsCapital    bool        `json:"is_capital"`
	Month        pgtype.Date `json:"month"`
	Amount       int64       `json:"amount"`
}

// ProjectionExpensesMonthly is the whole expense history, per property,
// category and month, with the category's capital flag: capital spend is
// investment, everything else is a running cost.
func (q *Queries) ProjectionExpensesMonthly(ctx context.Context, arg ProjectionExpensesMonthlyParams) ([]ProjectionExpensesMonthlyRow, error) {
	rows, err := q.db.Query(ctx, projectionExpensesMonthly, arg.OrgID, arg.ToDate, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectionExpensesMonthlyRow{}
	for rows.Next() {
		var i ProjectionExpensesMonthlyRow
		if err := rows.Scan(
			&i.PropertyID,
			&i.CategoryID,
			&i.CategoryName,
			&i.IsCapital,
			&i.Month,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectionProperties = `-- name: ProjectionProperties :many

SELECT p.id, p.name, p.purchase_price, p.purchase_date, p.current_value,
       (p.created_at AT TIME ZONE 'Africa/Dar_es_Salaam')::date AS created_on
FROM properties p
WHERE p.org_id = $1 AND p.deleted_at IS NULL
  AND ($2::uuid IS NULL OR p.id = $2::uuid)
ORDER BY p.name, p.id
`

type ProjectionPropertiesParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type ProjectionPropertiesRow struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	PurchasePrice *int64      `json:"purchase_price"`
	PurchaseDate  pgtype.Date `json:"purchase_date"`
	CurrentValue  *int64      `json:"current_value"`
	CreatedOn     pgtype.Date `json:"created_on"`
}

// Phase 28 — projections, break-even and ROI (PLAN2 Phase 28).
//
// The projection is computed in Go (internal/report/projection.go). These
// queries only read the facts it needs, per property, on the same cash
// definitions as GET /reports/revenue: collected = non-reversed payments by
// `paid_at` less rent refunds by `refunded_at` (Phase 22 §22.5), expected =
// non-waived schedules by `due_date`, expenses = recorded (not voided) by
// `incurred_on`. Months are calendar months on the Dar es Salaam wall clock.
// ProjectionProperties is every live property of the org (or the one asked
// for) with its investment fields and the day it entered the rent book.
func (q *Queries) ProjectionProperties(ctx context.Context, arg ProjectionPropertiesParams) ([]ProjectionPropertiesRow, error) {
	rows, err := q.db.Query(ctx, projectionProperties, arg.OrgID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectionPropertiesRow{}
	for rows.Next() {
		var i ProjectionPropertiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PurchasePrice,
			&i.PurchaseDate,
			&i.CurrentValue,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectionRefundedMonthly = `-- name: ProjectionRefundedMonthly :many
SELECT u.property_id AS property_id,
       date_trunc('month', rf.refunded_at AT TIME ZONE 'Africa/Dar_es_Salaam')::date AS month,
       COALESCE(sum(rf.amount), 0)::bigint AS amount
FROM rent_refunds rf
JOIN contracts c ON c.id = rf.contract_id AND c.org_id = rf.org_id
JOIN units u     ON u.id = c.unit_id AND u.org_id = c.org_id
WHERE rf.org_id = $1 AND NOT c.is_offline
  AND rf.refunded_at < $2
  AND ($3::uuid IS NULL OR u.property_id = $3::uuid)
GROUP BY 1, 2
`

type ProjectionRefundedMonthlyParams struct {
	OrgID      pgtype.UUID        `json:"org_id"`
	ToTs       pgtype.Timestamptz `json:"to_ts"`
	PropertyID pgtype.UUID        `json:"property_id"`
}

type ProjectionRefundedMonthlyRow struct {
	PropertyID pgtype.UUID `json:"property_id"`
	Month      pgtype.Date `json:"month"`
	Amount     int64       `json:"amount"`
}

func (q *Queries) ProjectionRefundedMonthly(ctx context.Context, arg ProjectionRefundedMonthlyParams) ([]ProjectionRefundedMonthlyRow, error) {
	rows, err := q.db.Query(ctx, projectionRefundedMonthly, arg.OrgID, arg.ToTs, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectionRefundedMonthlyRow{}
	for rows.Next() {
		var i ProjectionRefundedMonthlyRow
		if err := rows.Scan(&i.PropertyID, &i.Month, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectionScheduledDaily = `-- name: ProjectionScheduledDaily :many
SELECT u.property_id AS property_id,
       s.due_date AS day,
       COALESCE(sum(s.amount), 0)::bigint AS amount
FROM payment_schedules s
JOIN contracts c ON c.id = s.contract_id AND c.org_id = s.org_id
JOIN units u     ON u.id = c.unit_id AND u.org_id = c.org_id
WHERE s.org_id = $1 AND s.deleted_at IS NULL AND s.status <> 'waived'
  AND c.deleted_at IS NULL AND c.status IN ('active', 'expiring')
  AND u.deleted_at IS NULL
  AND s.due_date >= $2 AND s.due_date < $3
  AND ($4::uuid IS NULL OR u.property_id = $4::uuid)
GROUP BY 1, 2
`

type ProjectionScheduledDailyParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type ProjectionScheduledDailyRow struct {
	PropertyID pgtype.UUID `json:"property_id"`
	Day        pgtype.Date `json:"day"`
	Amount     int64       `json:"amount"`
}

// ProjectionScheduledDaily is the known future: every non-waived schedule of
// a running tenancy (active or expiring) falling due inside the horizon.
func (q *Queries) ProjectionScheduledDaily(ctx context.Context, arg ProjectionScheduledDailyParams) ([]ProjectionScheduledDailyRow, error) {
	rows, err := q.db.Query(ctx, projectionScheduledDaily,
		arg.OrgID,
		arg.FromDate,
		arg.ToDate,
		arg.PropertyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectionScheduledDailyRow{}
	for rows.Next() {
		var i ProjectionScheduledDailyRow
		if err := rows.Scan(&i.PropertyID, &i.Day, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectionUnits = `-- name: ProjectionUnits :many
SELECT u.id, u.property_id, u.name, u.status,
       COALESCE(pp.amount, 0)::bigint        AS price_amount,
       COALESCE(pp.period_days, 0)::int      AS price_period_days,
       COALESCE(lc.rent_amount, 0)::bigint   AS last_rent_amount,
       COALESCE(lc.rent_period_days, 0)::int AS last_rent_period_days,
       rc.running_end::date                  AS running_end
FROM units u
LEFT JOIN LATERAL (
    SELECT pl.amount, pl.period_days
    FROM price_plans pl
    WHERE pl.unit_id = u.id AND pl.org_id = u.org_id AND pl.deleted_at IS NULL
      AND pl.effective_from <= CURRENT_DATE
    ORDER BY pl.effective_from DESC, pl.created_at DESC
    LIMIT 1
) pp ON true
LEFT JOIN LATERAL (
    SELECT c.rent_amount, c.rent_period_days
    FROM contracts c
    WHERE c.unit_id = u.id AND c.org_id = u.org_id AND c.deleted_at IS NULL
      AND c.status IN ('active', 'expiring', 'ended', 'terminated') AND NOT c.is_offline
    ORDER BY c.start_date DESC, c.created_at DESC
    LIMIT 1
) lc ON true
LEFT JOIN LATERAL (
    SELECT max(c.end_date) AS running_end
    FROM contracts c
    WHERE c.unit_id = u.id AND c.org_id = u.org_id AND c.deleted_at IS NULL
      AND c.status IN ('active', 'expiring')
) rc ON true
WHERE u.org_id = $1 AND u.deleted_at IS NULL
  AND ($2::uuid IS NULL OR u.property_id = $2::uuid)
ORDER BY u.property_id, u.name, u.id
`

type ProjectionUnitsParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type ProjectionUnitsRow struct {
	ID                 pgtype.UUID `json:"id"`
	PropertyID         pgtype.UUID `json:"property_id"`
	Name               string      `json:"name"`
	Status             string      `json:"status"`
	PriceAmount        int64       `json:"price_amount"`
	PricePeriodDays    int32       `json:"price_period_days"`
	LastRentAmount     int64       `json:"last_rent_amount"`
	LastRentPeriodDays int32       `json:"last_rent_period_days"`
	RunningEnd         pgtype.Date `json:"running_end"`
}

// ProjectionUnits is every live unit with its own price (or, without one, the
// rent of its latest tenancy) and the day its running tenancy, if any, ends.
func (q *Queries) ProjectionUnits(ctx context.Context, arg ProjectionUnitsParams) ([]ProjectionUnitsRow, error) {
	rows, err := q.db.Query(ctx, projectionUnits, arg.OrgID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectionUnitsRow{}
	for rows.Next() {
		var i ProjectionUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.Name,
			&i.Status,
			&i.PriceAmount,
			&i.PricePeriodDays,
			&i.LastRentAmount,
			&i.LastRentPeriodDays,
			&i.RunningEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
