// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phase22.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contractTemplateChanged = `-- name: ContractTemplateChanged :one
SELECT EXISTS (
    SELECT 1 FROM contracts c
    JOIN contract_templates t ON t.id = c.template_id AND t.org_id = c.org_id
    WHERE c.org_id = $1 AND c.id = $2
      AND c.status = 'pending_signature' AND c.deleted_at IS NULL
      AND c.created_at < t.content_updated_at
      AND NOT EXISTS (SELECT 1 FROM contract_signatures cs
                      WHERE cs.contract_id = c.id AND cs.org_id = c.org_id)
) AS changed
`

type ContractTemplateChangedParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// ContractTemplateChanged: a contract nobody has signed yet, written before its
// template's wording or policy last changed.
func (q *Queries) ContractTemplateChanged(ctx context.Context, arg ContractTemplateChangedParams) (bool, error) {
	row := q.db.QueryRow(ctx, contractTemplateChanged, arg.OrgID, arg.ID)
	var changed bool
	err := row.Scan(&changed)
	return changed, err
}

const deletePaymentAllocation = `-- name: DeletePaymentAllocation :exec
DELETE FROM payment_allocations WHERE org_id = $1 AND id = $2
`

type DeletePaymentAllocationParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// DeletePaymentAllocation removes an allocation whose money has been moved.
func (q *Queries) DeletePaymentAllocation(ctx context.Context, arg DeletePaymentAllocationParams) error {
	_, err := q.db.Exec(ctx, deletePaymentAllocation, arg.OrgID, arg.ID)
	return err
}

const listAllocationsFrom = `-- name: ListAllocationsFrom :many
SELECT a.id, a.payment_id, a.schedule_id, a.amount
FROM payment_allocations a
JOIN payment_schedules s ON s.id = a.schedule_id AND s.org_id = a.org_id
JOIN payments p ON p.id = a.payment_id AND p.org_id = a.org_id
WHERE a.org_id = $1 AND s.contract_id = $2
  AND s.period_start >= $3 AND s.deleted_at IS NULL
  AND p.status <> 'reversed' AND p.deleted_at IS NULL
ORDER BY s.period_start, a.created_at
`

type ListAllocationsFromParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	ContractID pgtype.UUID `json:"contract_id"`
	FromDate   pgtype.Date `json:"from_date"`
}

type ListAllocationsFromRow struct {
	ID         pgtype.UUID `json:"id"`
	PaymentID  pgtype.UUID `json:"payment_id"`
	ScheduleID pgtype.UUID `json:"schedule_id"`
	Amount     int64       `json:"amount"`
}

// ListAllocationsFrom is every live allocation on a contract's periods starting
// on or after a date — the money an amendment carries across.
func (q *Queries) ListAllocationsFrom(ctx context.Context, arg ListAllocationsFromParams) ([]ListAllocationsFromRow, error) {
	rows, err := q.db.Query(ctx, listAllocationsFrom, arg.OrgID, arg.ContractID, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllocationsFromRow{}
	for rows.Next() {
		var i ListAllocationsFromRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.ScheduleID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePendingContracts = `-- name: ListStalePendingContracts :many
SELECT c.id FROM contracts c
JOIN contract_templates t ON t.id = c.template_id AND t.org_id = c.org_id
WHERE c.org_id = $1 AND t.id = $2
  AND c.status = 'pending_signature' AND c.deleted_at IS NULL
  AND c.created_at < t.content_updated_at
  AND NOT EXISTS (SELECT 1 FROM contract_signatures cs
                  WHERE cs.contract_id = c.id AND cs.org_id = c.org_id)
ORDER BY c.created_at
`

type ListStalePendingContractsParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	TemplateID pgtype.UUID `json:"template_id"`
}

// ListStalePendingContracts is every unsigned contract on a template written
// before the template's wording or policy last changed.
func (q *Queries) ListStalePendingContracts(ctx context.Context, arg ListStalePendingContractsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listStalePendingContracts, arg.OrgID, arg.TemplateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockContract = `-- name: LockContract :one
SELECT id, status FROM contracts
WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
FOR UPDATE
`

type LockContractParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type LockContractRow struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// LockContract serialises an amendment's activation against the old contract.
func (q *Queries) LockContract(ctx context.Context, arg LockContractParams) (LockContractRow, error) {
	row := q.db.QueryRow(ctx, lockContract, arg.OrgID, arg.ID)
	var i LockContractRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const openAmendmentFor = `-- name: OpenAmendmentFor :one

SELECT id FROM contracts
WHERE org_id = $1 AND supersedes_contract_id = $2
  AND status = 'pending_signature' AND amendment_effective_date IS NOT NULL
  AND deleted_at IS NULL
`

type OpenAmendmentForParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	ContractID pgtype.UUID `json:"contract_id"`
}

// ---------------------------------------------------- §22.4 amendments --
// OpenAmendmentFor is the unsigned amendment of a contract, if any.
func (q *Queries) OpenAmendmentFor(ctx context.Context, arg OpenAmendmentForParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, openAmendmentFor, arg.OrgID, arg.ContractID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const resolveUnitTemplate = `-- name: ResolveUnitTemplate :one

SELECT t.id, t.name,
       (CASE WHEN t.id = u.contract_template_id THEN 'unit'
             WHEN t.id = p.contract_template_id THEN 'property'
             ELSE 'default' END)::text AS source
FROM units u
JOIN properties p ON p.id = u.property_id AND p.org_id = u.org_id
JOIN contract_templates t ON t.org_id = u.org_id AND t.deleted_at IS NULL
 AND t.id = COALESCE(
       (SELECT ut.id FROM contract_templates ut
        WHERE ut.id = u.contract_template_id AND ut.org_id = u.org_id AND ut.deleted_at IS NULL),
       (SELECT pt.id FROM contract_templates pt
        WHERE pt.id = p.contract_template_id AND pt.org_id = u.org_id AND pt.deleted_at IS NULL),
       (SELECT dt.id FROM contract_templates dt
        WHERE dt.org_id = u.org_id AND dt.is_default AND dt.deleted_at IS NULL))
WHERE u.org_id = $1 AND u.id = $2 AND u.deleted_at IS NULL
`

type ResolveUnitTemplateParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UnitID pgtype.UUID `json:"unit_id"`
}

type ResolveUnitTemplateRow struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Source string      `json:"source"`
}

// Phase 22 §22.1 — template assignment.
// ResolveUnitTemplate answers "which template would a tenancy of this unit be
// written on", and why: the unit's own, else its property's, else the org
// default. A soft-deleted assignment is skipped, never an error.
func (q *Queries) ResolveUnitTemplate(ctx context.Context, arg ResolveUnitTemplateParams) (ResolveUnitTemplateRow, error) {
	row := q.db.QueryRow(ctx, resolveUnitTemplate, arg.OrgID, arg.UnitID)
	var i ResolveUnitTemplateRow
	err := row.Scan(&i.ID, &i.Name, &i.Source)
	return i, err
}

const setContractPolicy = `-- name: SetContractPolicy :exec
UPDATE contracts SET policy = $1
WHERE org_id = $2 AND id = $3 AND policy IS NULL
`

type SetContractPolicyParams struct {
	Policy []byte      `json:"policy"`
	OrgID  pgtype.UUID `json:"org_id"`
	ID     pgtype.UUID `json:"id"`
}

// SetContractPolicy stores the policy copy on a contract written in the same
// transaction; it only ever touches a contract that has none yet.
func (q *Queries) SetContractPolicy(ctx context.Context, arg SetContractPolicyParams) error {
	_, err := q.db.Exec(ctx, setContractPolicy, arg.Policy, arg.OrgID, arg.ID)
	return err
}

const setContractSupersedes = `-- name: SetContractSupersedes :exec
UPDATE contracts SET supersedes_contract_id = $1
WHERE org_id = $2 AND id = $3
`

type SetContractSupersedesParams struct {
	SupersedesContractID pgtype.UUID `json:"supersedes_contract_id"`
	OrgID                pgtype.UUID `json:"org_id"`
	ID                   pgtype.UUID `json:"id"`
}

// SetContractSupersedes links a reissued contract to the one it replaced.
func (q *Queries) SetContractSupersedes(ctx context.Context, arg SetContractSupersedesParams) error {
	_, err := q.db.Exec(ctx, setContractSupersedes, arg.SupersedesContractID, arg.OrgID, arg.ID)
	return err
}

const setPropertyTemplate = `-- name: SetPropertyTemplate :one
UPDATE properties SET contract_template_id = $1
WHERE org_id = $2 AND id = $3 AND deleted_at IS NULL
RETURNING id, contract_template_id
`

type SetPropertyTemplateParams struct {
	TemplateID pgtype.UUID `json:"template_id"`
	OrgID      pgtype.UUID `json:"org_id"`
	ID         pgtype.UUID `json:"id"`
}

type SetPropertyTemplateRow struct {
	ID                 pgtype.UUID `json:"id"`
	ContractTemplateID pgtype.UUID `json:"contract_template_id"`
}

// SetPropertyTemplate assigns (or clears) a property's template.
func (q *Queries) SetPropertyTemplate(ctx context.Context, arg SetPropertyTemplateParams) (SetPropertyTemplateRow, error) {
	row := q.db.QueryRow(ctx, setPropertyTemplate, arg.TemplateID, arg.OrgID, arg.ID)
	var i SetPropertyTemplateRow
	err := row.Scan(&i.ID, &i.ContractTemplateID)
	return i, err
}

const setTemplatePolicy = `-- name: SetTemplatePolicy :one

UPDATE contract_templates SET policy = $1
WHERE org_id = $2 AND id = $3 AND deleted_at IS NULL
RETURNING id, org_id, name, body_html, is_default, created_at, updated_at, deleted_at, body_html_sw, policy, content_updated_at
`

type SetTemplatePolicyParams struct {
	Policy []byte      `json:"policy"`
	OrgID  pgtype.UUID `json:"org_id"`
	ID     pgtype.UUID `json:"id"`
}

// ---------------------------------------------- §22.2 contract policies --
// SetTemplatePolicy writes (or, with NULL, clears) a template's policy.
func (q *Queries) SetTemplatePolicy(ctx context.Context, arg SetTemplatePolicyParams) (ContractTemplate, error) {
	row := q.db.QueryRow(ctx, setTemplatePolicy, arg.Policy, arg.OrgID, arg.ID)
	var i ContractTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.BodyHtml,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BodyHtmlSw,
		&i.Policy,
		&i.ContentUpdatedAt,
	)
	return i, err
}

const setUnitsTemplate = `-- name: SetUnitsTemplate :many
UPDATE units SET contract_template_id = $1
WHERE org_id = $2 AND id = ANY($3::uuid[]) AND deleted_at IS NULL
RETURNING id
`

type SetUnitsTemplateParams struct {
	TemplateID pgtype.UUID   `json:"template_id"`
	OrgID      pgtype.UUID   `json:"org_id"`
	UnitIds    []pgtype.UUID `json:"unit_ids"`
}

// SetUnitsTemplate assigns (or, with NULL, clears) the template of a set of
// the org's units in one statement. Ids from another org match nothing.
func (q *Queries) SetUnitsTemplate(ctx context.Context, arg SetUnitsTemplateParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, setUnitsTemplate, arg.TemplateID, arg.OrgID, arg.UnitIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shrinkPaymentAllocation = `-- name: ShrinkPaymentAllocation :exec
UPDATE payment_allocations SET amount = $1
WHERE org_id = $2 AND id = $3
`

type ShrinkPaymentAllocationParams struct {
	Amount int64       `json:"amount"`
	OrgID  pgtype.UUID `json:"org_id"`
	ID     pgtype.UUID `json:"id"`
}

// ShrinkPaymentAllocation keeps the part of an allocation that could not move.
func (q *Queries) ShrinkPaymentAllocation(ctx context.Context, arg ShrinkPaymentAllocationParams) error {
	_, err := q.db.Exec(ctx, shrinkPaymentAllocation, arg.Amount, arg.OrgID, arg.ID)
	return err
}

const supersedeContract = `-- name: SupersedeContract :one
UPDATE contracts
SET superseded_by_contract_id = $1,
    termination_effective_date = $2,
    termination_reason = $3,
    status = CASE WHEN $2::date < CURRENT_DATE THEN 'ended' ELSE status END
WHERE org_id = $4 AND id = $5 AND status IN ('active', 'expiring')
RETURNING id, status
`

type SupersedeContractParams struct {
	NewID   pgtype.UUID `json:"new_id"`
	LastDay pgtype.Date `json:"last_day"`
	Reason  *string     `json:"reason"`
	OrgID   pgtype.UUID `json:"org_id"`
	ID      pgtype.UUID `json:"id"`
}

type SupersedeContractRow struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// SupersedeContract closes the old side of an activated amendment: it points
// at its successor and stops the day before the amendment governs. When that
// day has already passed it ends now; otherwise the lifecycle job ends it.
func (q *Queries) SupersedeContract(ctx context.Context, arg SupersedeContractParams) (SupersedeContractRow, error) {
	row := q.db.QueryRow(ctx, supersedeContract,
		arg.NewID,
		arg.LastDay,
		arg.Reason,
		arg.OrgID,
		arg.ID,
	)
	var i SupersedeContractRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const templateUsage = `-- name: TemplateUsage :many
SELECT t.id,
       (SELECT count(*) FROM units u
        WHERE u.org_id = t.org_id AND u.contract_template_id = t.id AND u.deleted_at IS NULL)::bigint AS units,
       (SELECT count(*) FROM properties p
        WHERE p.org_id = t.org_id AND p.contract_template_id = t.id AND p.deleted_at IS NULL)::bigint AS properties
FROM contract_templates t
WHERE t.org_id = $1 AND t.deleted_at IS NULL
`

type TemplateUsageRow struct {
	ID         pgtype.UUID `json:"id"`
	Units      int64       `json:"units"`
	Properties int64       `json:"properties"`
}

// TemplateUsage counts where each of the org's live templates is assigned, for
// the templates list and for the delete guard.
func (q *Queries) TemplateUsage(ctx context.Context, orgID pgtype.UUID) ([]TemplateUsageRow, error) {
	rows, err := q.db.Query(ctx, templateUsage, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TemplateUsageRow{}
	for rows.Next() {
		var i TemplateUsageRow
		if err := rows.Scan(&i.ID, &i.Units, &i.Properties); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTemplateContent = `-- name: TouchTemplateContent :exec

UPDATE contract_templates SET content_updated_at = now()
WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
`

type TouchTemplateContentParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// ------------------------------------------ §22.3 stale unsigned contracts --
// TouchTemplateContent records that a template's wording or policy changed.
func (q *Queries) TouchTemplateContent(ctx context.Context, arg TouchTemplateContentParams) error {
	_, err := q.db.Exec(ctx, touchTemplateContent, arg.OrgID, arg.ID)
	return err
}

const waiveScheduleFrom = `-- name: WaiveScheduleFrom :exec
UPDATE payment_schedules SET status = 'waived', paid_amount = $1
WHERE org_id = $2 AND id = $3 AND deleted_at IS NULL
`

type WaiveScheduleFromParams struct {
	PaidAmount int64       `json:"paid_amount"`
	OrgID      pgtype.UUID `json:"org_id"`
	ID         pgtype.UUID `json:"id"`
}

// WaiveScheduleFrom closes one of the old contract's periods the amendment
// takes over, keeping only money that could not be moved.
func (q *Queries) WaiveScheduleFrom(ctx context.Context, arg WaiveScheduleFromParams) error {
	_, err := q.db.Exec(ctx, waiveScheduleFrom, arg.PaidAmount, arg.OrgID, arg.ID)
	return err
}
