// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: phase31.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveAmendment = `-- name: ApproveAmendment :one
UPDATE contracts
SET status = 'pending_signature', amendment_stage = 'approved',
    amendment_reviewed_by = $1, amendment_reviewed_at = now(),
    amendment_review_note = NULL
WHERE org_id = $2 AND id = $3
  AND status = 'draft' AND amendment_stage = $4 AND deleted_at IS NULL
RETURNING id, org_id, unit_id, renter_user_id, template_id, terms_snapshot_html, rent_amount, rent_period_days, payment_period_id, payment_period_days, term_days, start_date, end_date, due_day, status, snapshot_hash, created_at, updated_at, deleted_at, activated_at, terminated_at, termination_reason, termination_effective_date, link_request_id, language, policy, supersedes_contract_id, amendment_effective_date, amendment_reason, superseded_by_contract_id, settlement, notice_given_at, notice_leave_on, notice_reason, moved_out_confirmed_at, is_offline, payment_period_months, amendment_stage, amendment_note_sw, amendment_note_en, amendment_body_html, amendment_drafted_by, amendment_submitted_by, amendment_submitted_at, amendment_reviewed_by, amendment_reviewed_at, amendment_review_note, amendment_declined_at, amendment_decline_reason
`

type ApproveAmendmentParams struct {
	Actor     pgtype.UUID `json:"actor"`
	OrgID     pgtype.UUID `json:"org_id"`
	ID        pgtype.UUID `json:"id"`
	FromStage *string     `json:"from_stage"`
}

// ApproveAmendment hands the draft to the renter.
func (q *Queries) ApproveAmendment(ctx context.Context, arg ApproveAmendmentParams) (Contract, error) {
	row := q.db.QueryRow(ctx, approveAmendment,
		arg.Actor,
		arg.OrgID,
		arg.ID,
		arg.FromStage,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.RenterUserID,
		&i.TemplateID,
		&i.TermsSnapshotHtml,
		&i.RentAmount,
		&i.RentPeriodDays,
		&i.PaymentPeriodID,
		&i.PaymentPeriodDays,
		&i.TermDays,
		&i.StartDate,
		&i.EndDate,
		&i.DueDay,
		&i.Status,
		&i.SnapshotHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ActivatedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.TerminationEffectiveDate,
		&i.LinkRequestID,
		&i.Language,
		&i.Policy,
		&i.SupersedesContractID,
		&i.AmendmentEffectiveDate,
		&i.AmendmentReason,
		&i.SupersededByContractID,
		&i.Settlement,
		&i.NoticeGivenAt,
		&i.NoticeLeaveOn,
		&i.NoticeReason,
		&i.MovedOutConfirmedAt,
		&i.IsOffline,
		&i.PaymentPeriodMonths,
		&i.AmendmentStage,
		&i.AmendmentNoteSw,
		&i.AmendmentNoteEn,
		&i.AmendmentBodyHtml,
		&i.AmendmentDraftedBy,
		&i.AmendmentSubmittedBy,
		&i.AmendmentSubmittedAt,
		&i.AmendmentReviewedBy,
		&i.AmendmentReviewedAt,
		&i.AmendmentReviewNote,
		&i.AmendmentDeclinedAt,
		&i.AmendmentDeclineReason,
	)
	return i, err
}

const closeAmendmentDraft = `-- name: CloseAmendmentDraft :one
UPDATE contracts
SET status = 'terminated', terminated_at = now(), amendment_stage = $1,
    termination_reason = $2,
    amendment_reviewed_by = CASE WHEN $1::text = 'rejected'
                                 THEN $3::uuid ELSE amendment_reviewed_by END,
    amendment_reviewed_at = CASE WHEN $1::text = 'rejected'
                                 THEN now() ELSE amendment_reviewed_at END,
    amendment_review_note = CASE WHEN $1::text = 'rejected'
                                 THEN $2 ELSE amendment_review_note END
WHERE org_id = $4 AND id = $5
  AND status = 'draft' AND amendment_stage = ANY($6::text[])
  AND deleted_at IS NULL
RETURNING id, org_id, unit_id, renter_user_id, template_id, terms_snapshot_html, rent_amount, rent_period_days, payment_period_id, payment_period_days, term_days, start_date, end_date, due_day, status, snapshot_hash, created_at, updated_at, deleted_at, activated_at, terminated_at, termination_reason, termination_effective_date, link_request_id, language, policy, supersedes_contract_id, amendment_effective_date, amendment_reason, superseded_by_contract_id, settlement, notice_given_at, notice_leave_on, notice_reason, moved_out_confirmed_at, is_offline, payment_period_months, amendment_stage, amendment_note_sw, amendment_note_en, amendment_body_html, amendment_drafted_by, amendment_submitted_by, amendment_submitted_at, amendment_reviewed_by, amendment_reviewed_at, amendment_review_note, amendment_declined_at, amendment_decline_reason
`

type CloseAmendmentDraftParams struct {
	ToStage    *string     `json:"to_stage"`
	Reason     *string     `json:"reason"`
	Actor      pgtype.UUID `json:"actor"`
	OrgID      pgtype.UUID `json:"org_id"`
	ID         pgtype.UUID `json:"id"`
	FromStages []string    `json:"from_stages"`
}

// CloseAmendmentDraft ends a draft that never reached the renter: rejected by
// an owner, or withdrawn by the org.
func (q *Queries) CloseAmendmentDraft(ctx context.Context, arg CloseAmendmentDraftParams) (Contract, error) {
	row := q.db.QueryRow(ctx, closeAmendmentDraft,
		arg.ToStage,
		arg.Reason,
		arg.Actor,
		arg.OrgID,
		arg.ID,
		arg.FromStages,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.RenterUserID,
		&i.TemplateID,
		&i.TermsSnapshotHtml,
		&i.RentAmount,
		&i.RentPeriodDays,
		&i.PaymentPeriodID,
		&i.PaymentPeriodDays,
		&i.TermDays,
		&i.StartDate,
		&i.EndDate,
		&i.DueDay,
		&i.Status,
		&i.SnapshotHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ActivatedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.TerminationEffectiveDate,
		&i.LinkRequestID,
		&i.Language,
		&i.Policy,
		&i.SupersedesContractID,
		&i.AmendmentEffectiveDate,
		&i.AmendmentReason,
		&i.SupersededByContractID,
		&i.Settlement,
		&i.NoticeGivenAt,
		&i.NoticeLeaveOn,
		&i.NoticeReason,
		&i.MovedOutConfirmedAt,
		&i.IsOffline,
		&i.PaymentPeriodMonths,
		&i.AmendmentStage,
		&i.AmendmentNoteSw,
		&i.AmendmentNoteEn,
		&i.AmendmentBodyHtml,
		&i.AmendmentDraftedBy,
		&i.AmendmentSubmittedBy,
		&i.AmendmentSubmittedAt,
		&i.AmendmentReviewedBy,
		&i.AmendmentReviewedAt,
		&i.AmendmentReviewNote,
		&i.AmendmentDeclinedAt,
		&i.AmendmentDeclineReason,
	)
	return i, err
}

const declineAmendment = `-- name: DeclineAmendment :one
UPDATE contracts
SET status = 'terminated', terminated_at = now(), amendment_stage = 'declined',
    amendment_declined_at = now(), amendment_decline_reason = $1,
    termination_reason = $1
WHERE contracts.id = $2 AND contracts.renter_user_id = $3
  AND contracts.status = 'pending_signature' AND contracts.amendment_stage = 'approved'
  AND contracts.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM contract_signatures s
      WHERE s.contract_id = contracts.id AND s.org_id = contracts.org_id
  )
RETURNING id, org_id, unit_id, renter_user_id, template_id, terms_snapshot_html, rent_amount, rent_period_days, payment_period_id, payment_period_days, term_days, start_date, end_date, due_day, status, snapshot_hash, created_at, updated_at, deleted_at, activated_at, terminated_at, termination_reason, termination_effective_date, link_request_id, language, policy, supersedes_contract_id, amendment_effective_date, amendment_reason, superseded_by_contract_id, settlement, notice_given_at, notice_leave_on, notice_reason, moved_out_confirmed_at, is_offline, payment_period_months, amendment_stage, amendment_note_sw, amendment_note_en, amendment_body_html, amendment_drafted_by, amendment_submitted_by, amendment_submitted_at, amendment_reviewed_by, amendment_reviewed_at, amendment_review_note, amendment_declined_at, amendment_decline_reason
`

type DeclineAmendmentParams struct {
	Reason       *string     `json:"reason"`
	ID           pgtype.UUID `json:"id"`
	RenterUserID pgtype.UUID `json:"renter_user_id"`
}

// DeclineAmendment is the renter's no to an approved amendment they have not
// signed. The contract it would have replaced is not touched.
func (q *Queries) DeclineAmendment(ctx context.Context, arg DeclineAmendmentParams) (Contract, error) {
	row := q.db.QueryRow(ctx, declineAmendment, arg.Reason, arg.ID, arg.RenterUserID)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.RenterUserID,
		&i.TemplateID,
		&i.TermsSnapshotHtml,
		&i.RentAmount,
		&i.RentPeriodDays,
		&i.PaymentPeriodID,
		&i.PaymentPeriodDays,
		&i.TermDays,
		&i.StartDate,
		&i.EndDate,
		&i.DueDay,
		&i.Status,
		&i.SnapshotHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ActivatedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.TerminationEffectiveDate,
		&i.LinkRequestID,
		&i.Language,
		&i.Policy,
		&i.SupersedesContractID,
		&i.AmendmentEffectiveDate,
		&i.AmendmentReason,
		&i.SupersededByContractID,
		&i.Settlement,
		&i.NoticeGivenAt,
		&i.NoticeLeaveOn,
		&i.NoticeReason,
		&i.MovedOutConfirmedAt,
		&i.IsOffline,
		&i.PaymentPeriodMonths,
		&i.AmendmentStage,
		&i.AmendmentNoteSw,
		&i.AmendmentNoteEn,
		&i.AmendmentBodyHtml,
		&i.AmendmentDraftedBy,
		&i.AmendmentSubmittedBy,
		&i.AmendmentSubmittedAt,
		&i.AmendmentReviewedBy,
		&i.AmendmentReviewedAt,
		&i.AmendmentReviewNote,
		&i.AmendmentDeclinedAt,
		&i.AmendmentDeclineReason,
	)
	return i, err
}

const returnAmendment = `-- name: ReturnAmendment :one
UPDATE contracts
SET amendment_stage = 'draft', amendment_reviewed_by = $1,
    amendment_reviewed_at = now(), amendment_review_note = $2
WHERE org_id = $3 AND id = $4
  AND status = 'draft' AND amendment_stage = 'submitted' AND deleted_at IS NULL
RETURNING id, org_id, unit_id, renter_user_id, template_id, terms_snapshot_html, rent_amount, rent_period_days, payment_period_id, payment_period_days, term_days, start_date, end_date, due_day, status, snapshot_hash, created_at, updated_at, deleted_at, activated_at, terminated_at, termination_reason, termination_effective_date, link_request_id, language, policy, supersedes_contract_id, amendment_effective_date, amendment_reason, superseded_by_contract_id, settlement, notice_given_at, notice_leave_on, notice_reason, moved_out_confirmed_at, is_offline, payment_period_months, amendment_stage, amendment_note_sw, amendment_note_en, amendment_body_html, amendment_drafted_by, amendment_submitted_by, amendment_submitted_at, amendment_reviewed_by, amendment_reviewed_at, amendment_review_note, amendment_declined_at, amendment_decline_reason
`

type ReturnAmendmentParams struct {
	Actor pgtype.UUID `json:"actor"`
	Note  *string     `json:"note"`
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// ReturnAmendment sends a submitted draft back to be edited.
func (q *Queries) ReturnAmendment(ctx context.Context, arg ReturnAmendmentParams) (Contract, error) {
	row := q.db.QueryRow(ctx, returnAmendment,
		arg.Actor,
		arg.Note,
		arg.OrgID,
		arg.ID,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.RenterUserID,
		&i.TemplateID,
		&i.TermsSnapshotHtml,
		&i.RentAmount,
		&i.RentPeriodDays,
		&i.PaymentPeriodID,
		&i.PaymentPeriodDays,
		&i.TermDays,
		&i.StartDate,
		&i.EndDate,
		&i.DueDay,
		&i.Status,
		&i.SnapshotHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ActivatedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.TerminationEffectiveDate,
		&i.LinkRequestID,
		&i.Language,
		&i.Policy,
		&i.SupersedesContractID,
		&i.AmendmentEffectiveDate,
		&i.AmendmentReason,
		&i.SupersededByContractID,
		&i.Settlement,
		&i.NoticeGivenAt,
		&i.NoticeLeaveOn,
		&i.NoticeReason,
		&i.MovedOutConfirmedAt,
		&i.IsOffline,
		&i.PaymentPeriodMonths,
		&i.AmendmentStage,
		&i.AmendmentNoteSw,
		&i.AmendmentNoteEn,
		&i.AmendmentBodyHtml,
		&i.AmendmentDraftedBy,
		&i.AmendmentSubmittedBy,
		&i.AmendmentSubmittedAt,
		&i.AmendmentReviewedBy,
		&i.AmendmentReviewedAt,
		&i.AmendmentReviewNote,
		&i.AmendmentDeclinedAt,
		&i.AmendmentDeclineReason,
	)
	return i, err
}

const submitAmendment = `-- name: SubmitAmendment :one
UPDATE contracts
SET amendment_stage = 'submitted', amendment_submitted_by = $1,
    amendment_submitted_at = now()
WHERE org_id = $2 AND id = $3
  AND status = 'draft' AND amendment_stage = 'draft' AND deleted_at IS NULL
RETURNING id, org_id, unit_id, renter_user_id, template_id, terms_snapshot_html, rent_amount, rent_period_days, payment_period_id, payment_period_days, term_days, start_date, end_date, due_day, status, snapshot_hash, created_at, updated_at, deleted_at, activated_at, terminated_at, termination_reason, termination_effective_date, link_request_id, language, policy, supersedes_contract_id, amendment_effective_date, amendment_reason, superseded_by_contract_id, settlement, notice_given_at, notice_leave_on, notice_reason, moved_out_confirmed_at, is_offline, payment_period_months, amendment_stage, amendment_note_sw, amendment_note_en, amendment_body_html, amendment_drafted_by, amendment_submitted_by, amendment_submitted_at, amendment_reviewed_by, amendment_reviewed_at, amendment_review_note, amendment_declined_at, amendment_decline_reason
`

type SubmitAmendmentParams struct {
	Actor pgtype.UUID `json:"actor"`
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) SubmitAmendment(ctx context.Context, arg SubmitAmendmentParams) (Contract, error) {
	row := q.db.QueryRow(ctx, submitAmendment, arg.Actor, arg.OrgID, arg.ID)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.RenterUserID,
		&i.TemplateID,
		&i.TermsSnapshotHtml,
		&i.RentAmount,
		&i.RentPeriodDays,
		&i.PaymentPeriodID,
		&i.PaymentPeriodDays,
		&i.TermDays,
		&i.StartDate,
		&i.EndDate,
		&i.DueDay,
		&i.Status,
		&i.SnapshotHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ActivatedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.TerminationEffectiveDate,
		&i.LinkRequestID,
		&i.Language,
		&i.Policy,
		&i.SupersedesContractID,
		&i.AmendmentEffectiveDate,
		&i.AmendmentReason,
		&i.SupersededByContractID,
		&i.Settlement,
		&i.NoticeGivenAt,
		&i.NoticeLeaveOn,
		&i.NoticeReason,
		&i.MovedOutConfirmedAt,
		&i.IsOffline,
		&i.PaymentPeriodMonths,
		&i.AmendmentStage,
		&i.AmendmentNoteSw,
		&i.AmendmentNoteEn,
		&i.AmendmentBodyHtml,
		&i.AmendmentDraftedBy,
		&i.AmendmentSubmittedBy,
		&i.AmendmentSubmittedAt,
		&i.AmendmentReviewedBy,
		&i.AmendmentReviewedAt,
		&i.AmendmentReviewNote,
		&i.AmendmentDeclinedAt,
		&i.AmendmentDeclineReason,
	)
	return i, err
}

const updateAmendmentDraft = `-- name: UpdateAmendmentDraft :one

UPDATE contracts SET
    template_id = $1,
    terms_snapshot_html = $2,
    rent_amount = $3,
    rent_period_days = $4,
    payment_period_id = $5,
    payment_period_days = $6,
    payment_period_months = $7,
    term_days = $8,
    start_date = $9,
    end_date = $10,
    due_day = $11,
    snapshot_hash = $12,
    language = $13,
    policy = $14,
    amendment_effective_date = $15,
    amendment_reason = $16,
    amendment_note_sw = $17,
    amendment_note_en = $18,
    amendment_body_html = $19
WHERE org_id = $20 AND id = $21
  AND status = 'draft' AND deleted_at IS NULL
  AND amendment_stage = ANY($22::text[])
RETURNING id, org_id, unit_id, renter_user_id, template_id, terms_snapshot_html, rent_amount, rent_period_days, payment_period_id, payment_period_days, term_days, start_date, end_date, due_day, status, snapshot_hash, created_at, updated_at, deleted_at, activated_at, terminated_at, termination_reason, termination_effective_date, link_request_id, language, policy, supersedes_contract_id, amendment_effective_date, amendment_reason, superseded_by_contract_id, settlement, notice_given_at, notice_leave_on, notice_reason, moved_out_confirmed_at, is_offline, payment_period_months, amendment_stage, amendment_note_sw, amendment_note_en, amendment_body_html, amendment_drafted_by, amendment_submitted_by, amendment_submitted_at, amendment_reviewed_by, amendment_reviewed_at, amendment_review_note, amendment_declined_at, amendment_decline_reason
`

type UpdateAmendmentDraftParams struct {
	TemplateID             pgtype.UUID `json:"template_id"`
	TermsSnapshotHtml      string      `json:"terms_snapshot_html"`
	RentAmount             int64       `json:"rent_amount"`
	RentPeriodDays         int32       `json:"rent_period_days"`
	PaymentPeriodID        pgtype.UUID `json:"payment_period_id"`
	PaymentPeriodDays      int32       `json:"payment_period_days"`
	PaymentPeriodMonths    *int32      `json:"payment_period_months"`
	TermDays               int32       `json:"term_days"`
	StartDate              pgtype.Date `json:"start_date"`
	EndDate                pgtype.Date `json:"end_date"`
	DueDay                 *int32      `json:"due_day"`
	SnapshotHash           *string     `json:"snapshot_hash"`
	Language               string      `json:"language"`
	Policy                 []byte      `json:"policy"`
	AmendmentEffectiveDate pgtype.Date `json:"amendment_effective_date"`
	AmendmentReason        *string     `json:"amendment_reason"`
	AmendmentNoteSw        *string     `json:"amendment_note_sw"`
	AmendmentNoteEn        *string     `json:"amendment_note_en"`
	AmendmentBodyHtml      *string     `json:"amendment_body_html"`
	OrgID                  pgtype.UUID `json:"org_id"`
	ID                     pgtype.UUID `json:"id"`
	Stages                 []string    `json:"stages"`
}

// Phase 31: contract changes need an owner's approval (maker-checker).
//
// An amendment is a contract row in status `draft` until an owner approves it;
// `amendment_stage` carries where it is in review. Every transition names the
// stage it leaves, so a double click or a race answers with no row.
// UpdateAmendmentDraft rewrites everything a draft's document says, from a
// fresh render. Only a draft may change; a submitted one only when the caller
// allows it (an owner editing before approval).
func (q *Queries) UpdateAmendmentDraft(ctx context.Context, arg UpdateAmendmentDraftParams) (Contract, error) {
	row := q.db.QueryRow(ctx, updateAmendmentDraft,
		arg.TemplateID,
		arg.TermsSnapshotHtml,
		arg.RentAmount,
		arg.RentPeriodDays,
		arg.PaymentPeriodID,
		arg.PaymentPeriodDays,
		arg.PaymentPeriodMonths,
		arg.TermDays,
		arg.StartDate,
		arg.EndDate,
		arg.DueDay,
		arg.SnapshotHash,
		arg.Language,
		arg.Policy,
		arg.AmendmentEffectiveDate,
		arg.AmendmentReason,
		arg.AmendmentNoteSw,
		arg.AmendmentNoteEn,
		arg.AmendmentBodyHtml,
		arg.OrgID,
		arg.ID,
		arg.Stages,
	)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.RenterUserID,
		&i.TemplateID,
		&i.TermsSnapshotHtml,
		&i.RentAmount,
		&i.RentPeriodDays,
		&i.PaymentPeriodID,
		&i.PaymentPeriodDays,
		&i.TermDays,
		&i.StartDate,
		&i.EndDate,
		&i.DueDay,
		&i.Status,
		&i.SnapshotHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ActivatedAt,
		&i.TerminatedAt,
		&i.TerminationReason,
		&i.TerminationEffectiveDate,
		&i.LinkRequestID,
		&i.Language,
		&i.Policy,
		&i.SupersedesContractID,
		&i.AmendmentEffectiveDate,
		&i.AmendmentReason,
		&i.SupersededByContractID,
		&i.Settlement,
		&i.NoticeGivenAt,
		&i.NoticeLeaveOn,
		&i.NoticeReason,
		&i.MovedOutConfirmedAt,
		&i.IsOffline,
		&i.PaymentPeriodMonths,
		&i.AmendmentStage,
		&i.AmendmentNoteSw,
		&i.AmendmentNoteEn,
		&i.AmendmentBodyHtml,
		&i.AmendmentDraftedBy,
		&i.AmendmentSubmittedBy,
		&i.AmendmentSubmittedAt,
		&i.AmendmentReviewedBy,
		&i.AmendmentReviewedAt,
		&i.AmendmentReviewNote,
		&i.AmendmentDeclinedAt,
		&i.AmendmentDeclineReason,
	)
	return i, err
}
