// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_templates.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlatformTemplates = `-- name: CountPlatformTemplates :one
SELECT count(*)::bigint FROM platform_templates
`

// CountPlatformTemplates drives the seed-if-empty on startup: an installation
// whose catalogue was never seeded gets the code defaults written into the
// table, so the DB is authoritative from the first boot.
func (q *Queries) CountPlatformTemplates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlatformTemplates)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPlatformTemplate = `-- name: GetPlatformTemplate :one
SELECT t.kind, t.sw, t.en, t.variables, t.locked, t.version, t.updated_at,
       COALESCE(u.full_name, '')::text AS updated_by
FROM platform_templates t
LEFT JOIN users u ON u.id = t.updated_by_admin_id
WHERE t.kind = $1
`

type GetPlatformTemplateRow struct {
	Kind      string             `json:"kind"`
	Sw        string             `json:"sw"`
	En        string             `json:"en"`
	Variables []string           `json:"variables"`
	Locked    bool               `json:"locked"`
	Version   int32              `json:"version"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy string             `json:"updated_by"`
}

func (q *Queries) GetPlatformTemplate(ctx context.Context, kind string) (GetPlatformTemplateRow, error) {
	row := q.db.QueryRow(ctx, getPlatformTemplate, kind)
	var i GetPlatformTemplateRow
	err := row.Scan(
		&i.Kind,
		&i.Sw,
		&i.En,
		&i.Variables,
		&i.Locked,
		&i.Version,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getPlatformTemplateVersion = `-- name: GetPlatformTemplateVersion :one
SELECT version, sw, en, created_at
FROM platform_template_versions
WHERE kind = $1 AND version = $2::int
`

type GetPlatformTemplateVersionParams struct {
	Kind    string `json:"kind"`
	Version int32  `json:"version"`
}

type GetPlatformTemplateVersionRow struct {
	Version   int32              `json:"version"`
	Sw        string             `json:"sw"`
	En        string             `json:"en"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPlatformTemplateVersion(ctx context.Context, arg GetPlatformTemplateVersionParams) (GetPlatformTemplateVersionRow, error) {
	row := q.db.QueryRow(ctx, getPlatformTemplateVersion, arg.Kind, arg.Version)
	var i GetPlatformTemplateVersionRow
	err := row.Scan(
		&i.Version,
		&i.Sw,
		&i.En,
		&i.CreatedAt,
	)
	return i, err
}

const insertPlatformTemplateVersion = `-- name: InsertPlatformTemplateVersion :exec
INSERT INTO platform_template_versions (kind, version, sw, en, admin_user_id)
VALUES ($1, $2::int, $3, $4,
        $5)
ON CONFLICT (kind, version) DO NOTHING
`

type InsertPlatformTemplateVersionParams struct {
	Kind        string      `json:"kind"`
	Version     int32       `json:"version"`
	Sw          string      `json:"sw"`
	En          string      `json:"en"`
	AdminUserID pgtype.UUID `json:"admin_user_id"`
}

func (q *Queries) InsertPlatformTemplateVersion(ctx context.Context, arg InsertPlatformTemplateVersionParams) error {
	_, err := q.db.Exec(ctx, insertPlatformTemplateVersion,
		arg.Kind,
		arg.Version,
		arg.Sw,
		arg.En,
		arg.AdminUserID,
	)
	return err
}

const listLockedTemplateKinds = `-- name: ListLockedTemplateKinds :many
SELECT kind FROM platform_templates WHERE locked ORDER BY kind
`

// ListLockedTemplateKinds is what the landlord's notification settings consult
// before accepting an override: a locked kind is the platform's wording and
// stays that way.
func (q *Queries) ListLockedTemplateKinds(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listLockedTemplateKinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var kind string
		if err := rows.Scan(&kind); err != nil {
			return nil, err
		}
		items = append(items, kind)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformTemplateVersions = `-- name: ListPlatformTemplateVersions :many
SELECT v.version, v.sw, v.en, v.created_at,
       COALESCE(u.full_name, '')::text AS admin_name
FROM platform_template_versions v
LEFT JOIN users u ON u.id = v.admin_user_id
WHERE v.kind = $1
ORDER BY v.version DESC
`

type ListPlatformTemplateVersionsRow struct {
	Version   int32              `json:"version"`
	Sw        string             `json:"sw"`
	En        string             `json:"en"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	AdminName string             `json:"admin_name"`
}

func (q *Queries) ListPlatformTemplateVersions(ctx context.Context, kind string) ([]ListPlatformTemplateVersionsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformTemplateVersions, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformTemplateVersionsRow{}
	for rows.Next() {
		var i ListPlatformTemplateVersionsRow
		if err := rows.Scan(
			&i.Version,
			&i.Sw,
			&i.En,
			&i.CreatedAt,
			&i.AdminName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformTemplates = `-- name: ListPlatformTemplates :many

SELECT t.kind, t.sw, t.en, t.variables, t.locked, t.version, t.updated_at,
       COALESCE(u.full_name, '')::text AS updated_by
FROM platform_templates t
LEFT JOIN users u ON u.id = t.updated_by_admin_id
ORDER BY t.kind
`

type ListPlatformTemplatesRow struct {
	Kind      string             `json:"kind"`
	Sw        string             `json:"sw"`
	En        string             `json:"en"`
	Variables []string           `json:"variables"`
	Locked    bool               `json:"locked"`
	Version   int32              `json:"version"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy string             `json:"updated_by"`
}

// Phase 14: the platform SMS wording, editable by an admin (SPEC §5.12).
//
// platform_templates has no org_id: it is the platform's own catalogue, one
// row per notification kind, and the org's own wording lives in
// `orgs.settings.notifications.templates` on top of it. The org-scope guard
// therefore has nothing to check here.
func (q *Queries) ListPlatformTemplates(ctx context.Context) ([]ListPlatformTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listPlatformTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformTemplatesRow{}
	for rows.Next() {
		var i ListPlatformTemplatesRow
		if err := rows.Scan(
			&i.Kind,
			&i.Sw,
			&i.En,
			&i.Variables,
			&i.Locked,
			&i.Version,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedPlatformTemplate = `-- name: SeedPlatformTemplate :exec
INSERT INTO platform_templates (kind, sw, en, variables, locked)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (kind) DO NOTHING
`

type SeedPlatformTemplateParams struct {
	Kind      string   `json:"kind"`
	Sw        string   `json:"sw"`
	En        string   `json:"en"`
	Variables []string `json:"variables"`
	Locked    bool     `json:"locked"`
}

// SeedPlatformTemplate writes one kind's default, leaving an existing row
// untouched: seeding is idempotent and never overwrites an admin's wording.
func (q *Queries) SeedPlatformTemplate(ctx context.Context, arg SeedPlatformTemplateParams) error {
	_, err := q.db.Exec(ctx, seedPlatformTemplate,
		arg.Kind,
		arg.Sw,
		arg.En,
		arg.Variables,
		arg.Locked,
	)
	return err
}

const setPlatformTemplateLocked = `-- name: SetPlatformTemplateLocked :one
UPDATE platform_templates
SET locked = $1, updated_by_admin_id = $2
WHERE kind = $3
RETURNING kind, sw, en, variables, locked, updated_by_admin_id, updated_at, version
`

type SetPlatformTemplateLockedParams struct {
	Locked      bool        `json:"locked"`
	AdminUserID pgtype.UUID `json:"admin_user_id"`
	Kind        string      `json:"kind"`
}

func (q *Queries) SetPlatformTemplateLocked(ctx context.Context, arg SetPlatformTemplateLockedParams) (PlatformTemplate, error) {
	row := q.db.QueryRow(ctx, setPlatformTemplateLocked, arg.Locked, arg.AdminUserID, arg.Kind)
	var i PlatformTemplate
	err := row.Scan(
		&i.Kind,
		&i.Sw,
		&i.En,
		&i.Variables,
		&i.Locked,
		&i.UpdatedByAdminID,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const updatePlatformTemplate = `-- name: UpdatePlatformTemplate :one
UPDATE platform_templates
SET sw = $1, en = $2,
    updated_by_admin_id = $3,
    version = version + 1
WHERE kind = $4
RETURNING kind, sw, en, variables, locked, updated_by_admin_id, updated_at, version
`

type UpdatePlatformTemplateParams struct {
	Sw          string      `json:"sw"`
	En          string      `json:"en"`
	AdminUserID pgtype.UUID `json:"admin_user_id"`
	Kind        string      `json:"kind"`
}

// UpdatePlatformTemplate saves new wording and bumps the version. The previous
// body is written to platform_template_versions by the caller first, inside the
// same transaction, so history never loses a step.
func (q *Queries) UpdatePlatformTemplate(ctx context.Context, arg UpdatePlatformTemplateParams) (PlatformTemplate, error) {
	row := q.db.QueryRow(ctx, updatePlatformTemplate,
		arg.Sw,
		arg.En,
		arg.AdminUserID,
		arg.Kind,
	)
	var i PlatformTemplate
	err := row.Scan(
		&i.Kind,
		&i.Sw,
		&i.En,
		&i.Variables,
		&i.Locked,
		&i.UpdatedByAdminID,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
