// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPricePlan = `-- name: CreatePricePlan :one

INSERT INTO price_plans (org_id, unit_id, amount, currency, period_days, effective_from, created_by_user_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, org_id, unit_id, amount, currency, period_days, effective_from, created_at, updated_at, deleted_at, created_by_user_id
`

type CreatePricePlanParams struct {
	OrgID           pgtype.UUID `json:"org_id"`
	UnitID          pgtype.UUID `json:"unit_id"`
	Amount          int64       `json:"amount"`
	Currency        string      `json:"currency"`
	PeriodDays      int32       `json:"period_days"`
	EffectiveFrom   pgtype.Date `json:"effective_from"`
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
}

// Price history is append-only in practice: a new price is a new row with its
// own effective_from, and the "current" price is the newest row whose
// effective_from has arrived (SPEC §4 — active contracts keep their snapshot).
func (q *Queries) CreatePricePlan(ctx context.Context, arg CreatePricePlanParams) (PricePlan, error) {
	row := q.db.QueryRow(ctx, createPricePlan,
		arg.OrgID,
		arg.UnitID,
		arg.Amount,
		arg.Currency,
		arg.PeriodDays,
		arg.EffectiveFrom,
		arg.CreatedByUserID,
	)
	var i PricePlan
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.Amount,
		&i.Currency,
		&i.PeriodDays,
		&i.EffectiveFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const getCurrentPricePlan = `-- name: GetCurrentPricePlan :one
SELECT pl.id, pl.org_id, pl.unit_id, pl.amount, pl.currency, pl.period_days,
       pl.effective_from, pl.created_at
FROM price_plans pl
WHERE pl.org_id = $1 AND pl.unit_id = $2
  AND pl.deleted_at IS NULL AND pl.effective_from <= CURRENT_DATE
ORDER BY pl.effective_from DESC, pl.created_at DESC
LIMIT 1
`

type GetCurrentPricePlanParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UnitID pgtype.UUID `json:"unit_id"`
}

type GetCurrentPricePlanRow struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	UnitID        pgtype.UUID        `json:"unit_id"`
	Amount        int64              `json:"amount"`
	Currency      string             `json:"currency"`
	PeriodDays    int32              `json:"period_days"`
	EffectiveFrom pgtype.Date        `json:"effective_from"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetCurrentPricePlan(ctx context.Context, arg GetCurrentPricePlanParams) (GetCurrentPricePlanRow, error) {
	row := q.db.QueryRow(ctx, getCurrentPricePlan, arg.OrgID, arg.UnitID)
	var i GetCurrentPricePlanRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UnitID,
		&i.Amount,
		&i.Currency,
		&i.PeriodDays,
		&i.EffectiveFrom,
		&i.CreatedAt,
	)
	return i, err
}

const listPricePlans = `-- name: ListPricePlans :many
SELECT pl.id, pl.org_id, pl.unit_id, pl.amount, pl.currency, pl.period_days,
       pl.effective_from, pl.created_at, pl.created_by_user_id,
       u.full_name AS created_by_name
FROM price_plans pl
LEFT JOIN users u ON u.id = pl.created_by_user_id
WHERE pl.org_id = $1 AND pl.unit_id = $2 AND pl.deleted_at IS NULL
ORDER BY pl.effective_from DESC, pl.created_at DESC, pl.id DESC
`

type ListPricePlansParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	UnitID pgtype.UUID `json:"unit_id"`
}

type ListPricePlansRow struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	UnitID          pgtype.UUID        `json:"unit_id"`
	Amount          int64              `json:"amount"`
	Currency        string             `json:"currency"`
	PeriodDays      int32              `json:"period_days"`
	EffectiveFrom   pgtype.Date        `json:"effective_from"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	CreatedByName   *string            `json:"created_by_name"`
}

func (q *Queries) ListPricePlans(ctx context.Context, arg ListPricePlansParams) ([]ListPricePlansRow, error) {
	rows, err := q.db.Query(ctx, listPricePlans, arg.OrgID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPricePlansRow{}
	for rows.Next() {
		var i ListPricePlansRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UnitID,
			&i.Amount,
			&i.Currency,
			&i.PeriodDays,
			&i.EffectiveFrom,
			&i.CreatedAt,
			&i.CreatedByUserID,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
