// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: properties.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBlockingContractsForProperty = `-- name: CountBlockingContractsForProperty :one
SELECT count(*)
FROM contracts c
JOIN units u ON u.id = c.unit_id
WHERE c.org_id = $1
  AND u.property_id = $2
  AND c.status IN ('active', 'pending_signature')
  AND c.deleted_at IS NULL
`

type CountBlockingContractsForPropertyParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	PropertyID pgtype.UUID `json:"property_id"`
}

func (q *Queries) CountBlockingContractsForProperty(ctx context.Context, arg CountBlockingContractsForPropertyParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBlockingContractsForProperty, arg.OrgID, arg.PropertyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProperty = `-- name: CreateProperty :one

INSERT INTO properties (org_id, name, location_text, lat, lng, notes)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, org_id, name, location_text, lat, lng, notes, created_at, updated_at, deleted_at
`

type CreatePropertyParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	Name         string      `json:"name"`
	LocationText string      `json:"location_text"`
	Lat          *float64    `json:"lat"`
	Lng          *float64    `json:"lng"`
	Notes        *string     `json:"notes"`
}

// Properties are org-scoped: every statement filters by org_id, so a property
// belonging to another org is indistinguishable from one that does not exist
// (the handler turns "no rows" into 404 — API.md).
func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, createProperty,
		arg.OrgID,
		arg.Name,
		arg.LocationText,
		arg.Lat,
		arg.Lng,
		arg.Notes,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.LocationText,
		&i.Lat,
		&i.Lng,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProperty = `-- name: GetProperty :one
SELECT p.id, p.org_id, p.name, p.location_text, p.lat, p.lng, p.notes,
       p.created_at, p.updated_at,
       c.total, c.vacant, c.occupied, c.maintenance, c.unlisted
FROM properties p
LEFT JOIN LATERAL (
    SELECT count(*)                                            AS total,
           count(*) FILTER (WHERE u.status = 'vacant')         AS vacant,
           count(*) FILTER (WHERE u.status = 'occupied')       AS occupied,
           count(*) FILTER (WHERE u.status = 'maintenance')    AS maintenance,
           count(*) FILTER (WHERE u.status = 'unlisted')       AS unlisted
    FROM units u
    WHERE u.property_id = p.id AND u.org_id = p.org_id AND u.deleted_at IS NULL
) c ON true
WHERE p.org_id = $1 AND p.id = $2 AND p.deleted_at IS NULL
`

type GetPropertyParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetPropertyRow struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	Name         string             `json:"name"`
	LocationText string             `json:"location_text"`
	Lat          *float64           `json:"lat"`
	Lng          *float64           `json:"lng"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Total        int64              `json:"total"`
	Vacant       int64              `json:"vacant"`
	Occupied     int64              `json:"occupied"`
	Maintenance  int64              `json:"maintenance"`
	Unlisted     int64              `json:"unlisted"`
}

func (q *Queries) GetProperty(ctx context.Context, arg GetPropertyParams) (GetPropertyRow, error) {
	row := q.db.QueryRow(ctx, getProperty, arg.OrgID, arg.ID)
	var i GetPropertyRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.LocationText,
		&i.Lat,
		&i.Lng,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Total,
		&i.Vacant,
		&i.Occupied,
		&i.Maintenance,
		&i.Unlisted,
	)
	return i, err
}

const listProperties = `-- name: ListProperties :many
SELECT p.id, p.org_id, p.name, p.location_text, p.lat, p.lng, p.notes,
       p.created_at, p.updated_at,
       c.total, c.vacant, c.occupied, c.maintenance, c.unlisted
FROM properties p
LEFT JOIN LATERAL (
    SELECT count(*)                                            AS total,
           count(*) FILTER (WHERE u.status = 'vacant')         AS vacant,
           count(*) FILTER (WHERE u.status = 'occupied')       AS occupied,
           count(*) FILTER (WHERE u.status = 'maintenance')    AS maintenance,
           count(*) FILTER (WHERE u.status = 'unlisted')       AS unlisted
    FROM units u
    WHERE u.property_id = p.id AND u.org_id = p.org_id AND u.deleted_at IS NULL
) c ON true
WHERE p.org_id = $1 AND p.deleted_at IS NULL
  AND ($2::timestamptz IS NULL
       OR (p.created_at, p.id) < ($2::timestamptz, $3::uuid))
ORDER BY p.created_at DESC, p.id DESC
LIMIT $4
`

type ListPropertiesParams struct {
	OrgID    pgtype.UUID        `json:"org_id"`
	CursorAt pgtype.Timestamptz `json:"cursor_at"`
	CursorID pgtype.UUID        `json:"cursor_id"`
	RowLimit int32              `json:"row_limit"`
}

type ListPropertiesRow struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	Name         string             `json:"name"`
	LocationText string             `json:"location_text"`
	Lat          *float64           `json:"lat"`
	Lng          *float64           `json:"lng"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Total        int64              `json:"total"`
	Vacant       int64              `json:"vacant"`
	Occupied     int64              `json:"occupied"`
	Maintenance  int64              `json:"maintenance"`
	Unlisted     int64              `json:"unlisted"`
}

func (q *Queries) ListProperties(ctx context.Context, arg ListPropertiesParams) ([]ListPropertiesRow, error) {
	rows, err := q.db.Query(ctx, listProperties,
		arg.OrgID,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPropertiesRow{}
	for rows.Next() {
		var i ListPropertiesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.LocationText,
			&i.Lat,
			&i.Lng,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
			&i.Vacant,
			&i.Occupied,
			&i.Maintenance,
			&i.Unlisted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProperty = `-- name: SoftDeleteProperty :one
UPDATE properties SET deleted_at = now()
WHERE org_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, org_id, name, location_text, lat, lng, notes, created_at, updated_at, deleted_at
`

type SoftDeletePropertyParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) SoftDeleteProperty(ctx context.Context, arg SoftDeletePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, softDeleteProperty, arg.OrgID, arg.ID)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.LocationText,
		&i.Lat,
		&i.Lng,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUnitsOfProperty = `-- name: SoftDeleteUnitsOfProperty :exec
UPDATE units SET deleted_at = now()
WHERE org_id = $1 AND property_id = $2 AND deleted_at IS NULL
`

type SoftDeleteUnitsOfPropertyParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	PropertyID pgtype.UUID `json:"property_id"`
}

func (q *Queries) SoftDeleteUnitsOfProperty(ctx context.Context, arg SoftDeleteUnitsOfPropertyParams) error {
	_, err := q.db.Exec(ctx, softDeleteUnitsOfProperty, arg.OrgID, arg.PropertyID)
	return err
}

const updateProperty = `-- name: UpdateProperty :one
UPDATE properties
SET name          = COALESCE($1, name),
    location_text = COALESCE($2, location_text),
    lat           = CASE WHEN $3::boolean THEN $4::double precision ELSE lat END,
    lng           = CASE WHEN $5::boolean THEN $6::double precision ELSE lng END,
    notes         = CASE WHEN $7::boolean THEN $8::text ELSE notes END
WHERE org_id = $9 AND id = $10 AND deleted_at IS NULL
RETURNING id, org_id, name, location_text, lat, lng, notes, created_at, updated_at, deleted_at
`

type UpdatePropertyParams struct {
	Name         *string     `json:"name"`
	LocationText *string     `json:"location_text"`
	SetLat       bool        `json:"set_lat"`
	Lat          *float64    `json:"lat"`
	SetLng       bool        `json:"set_lng"`
	Lng          *float64    `json:"lng"`
	SetNotes     bool        `json:"set_notes"`
	Notes        *string     `json:"notes"`
	OrgID        pgtype.UUID `json:"org_id"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, updateProperty,
		arg.Name,
		arg.LocationText,
		arg.SetLat,
		arg.Lat,
		arg.SetLng,
		arg.Lng,
		arg.SetNotes,
		arg.Notes,
		arg.OrgID,
		arg.ID,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.LocationText,
		&i.Lat,
		&i.Lng,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
