// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: renter_profiles.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRenterProfileDecrypted = `-- name: GetRenterProfileDecrypted :one
SELECT p.id, p.user_id, p.full_name,
       CASE WHEN p.nida_number_enc IS NULL THEN NULL
            ELSE pgp_sym_decrypt(p.nida_number_enc, $1::text) END::text AS nida_number,
       p.next_of_kin_name, p.next_of_kin_phone, p.kyc_status, p.kyc_doc_object_key,
       p.created_at, p.updated_at
FROM renter_profiles p
WHERE p.user_id = $2 AND p.deleted_at IS NULL
`

type GetRenterProfileDecryptedParams struct {
	EncKey string      `json:"enc_key"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetRenterProfileDecryptedRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	FullName        string             `json:"full_name"`
	NidaNumber      string             `json:"nida_number"`
	NextOfKinName   *string            `json:"next_of_kin_name"`
	NextOfKinPhone  *string            `json:"next_of_kin_phone"`
	KycStatus       string             `json:"kyc_status"`
	KycDocObjectKey *string            `json:"kyc_doc_object_key"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRenterProfileDecrypted(ctx context.Context, arg GetRenterProfileDecryptedParams) (GetRenterProfileDecryptedRow, error) {
	row := q.db.QueryRow(ctx, getRenterProfileDecrypted, arg.EncKey, arg.UserID)
	var i GetRenterProfileDecryptedRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.NidaNumber,
		&i.NextOfKinName,
		&i.NextOfKinPhone,
		&i.KycStatus,
		&i.KycDocObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRenterProfile = `-- name: UpsertRenterProfile :one

INSERT INTO renter_profiles (user_id, full_name, nida_number_enc, next_of_kin_name, next_of_kin_phone)
VALUES (
    $1,
    $2,
    CASE WHEN $3::text IS NULL THEN NULL
         ELSE pgp_sym_encrypt($3::text, $4::text) END,
    $5,
    $6
)
ON CONFLICT (user_id) DO UPDATE
SET full_name         = EXCLUDED.full_name,
    nida_number_enc   = COALESCE(EXCLUDED.nida_number_enc, renter_profiles.nida_number_enc),
    next_of_kin_name  = COALESCE(EXCLUDED.next_of_kin_name, renter_profiles.next_of_kin_name),
    next_of_kin_phone = COALESCE(EXCLUDED.next_of_kin_phone, renter_profiles.next_of_kin_phone)
RETURNING id, user_id, full_name, nida_number_enc, next_of_kin_name, next_of_kin_phone, kyc_status, kyc_doc_object_key, created_at, updated_at, deleted_at
`

type UpsertRenterProfileParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	FullName       string      `json:"full_name"`
	NidaNumber     *string     `json:"nida_number"`
	EncKey         string      `json:"enc_key"`
	NextOfKinName  *string     `json:"next_of_kin_name"`
	NextOfKinPhone *string     `json:"next_of_kin_phone"`
}

// renter_profiles belongs to a user, not to an org (a renter can hold
// contracts with several orgs), so these queries are keyed by user_id.
//
// nida_number is encrypted at rest with pgcrypto. The symmetric key is passed
// as a parameter (config NIDA_ENC_KEY) and never stored.
func (q *Queries) UpsertRenterProfile(ctx context.Context, arg UpsertRenterProfileParams) (RenterProfile, error) {
	row := q.db.QueryRow(ctx, upsertRenterProfile,
		arg.UserID,
		arg.FullName,
		arg.NidaNumber,
		arg.EncKey,
		arg.NextOfKinName,
		arg.NextOfKinPhone,
	)
	var i RenterProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.NidaNumberEnc,
		&i.NextOfKinName,
		&i.NextOfKinPhone,
		&i.KycStatus,
		&i.KycDocObjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
