// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: renters.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrgRenter = `-- name: GetOrgRenter :one
SELECT u.id AS user_id, u.phone, u.email, u.full_name AS user_name, u.created_at,
       COALESCE(rp.full_name, u.full_name)::text AS profile_name,
       COALESCE(rp.kyc_status, 'incomplete')::text AS kyc_status,
       (rp.kyc_doc_object_key IS NOT NULL)::boolean AS kyc_doc_uploaded
FROM users u
LEFT JOIN renter_profiles rp ON rp.user_id = u.id AND rp.deleted_at IS NULL
WHERE u.id = $1 AND u.kind = 'renter' AND u.deleted_at IS NULL
  AND (EXISTS (SELECT 1 FROM unit_link_requests lr
               WHERE lr.renter_user_id = u.id AND lr.org_id = $2 AND lr.deleted_at IS NULL)
    OR EXISTS (SELECT 1 FROM contracts c
               WHERE c.renter_user_id = u.id AND c.org_id = $2 AND c.deleted_at IS NULL))
`

type GetOrgRenterParams struct {
	UserID pgtype.UUID `json:"user_id"`
	OrgID  pgtype.UUID `json:"org_id"`
}

type GetOrgRenterRow struct {
	UserID         pgtype.UUID        `json:"user_id"`
	Phone          *string            `json:"phone"`
	Email          *string            `json:"email"`
	UserName       string             `json:"user_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ProfileName    string             `json:"profile_name"`
	KycStatus      string             `json:"kyc_status"`
	KycDocUploaded bool               `json:"kyc_doc_uploaded"`
}

// GetOrgRenter is the directory's single-row form: it answers only for a
// renter this org already knows, so an unrelated renter is a 404 rather than a
// probe that confirms the account exists.
func (q *Queries) GetOrgRenter(ctx context.Context, arg GetOrgRenterParams) (GetOrgRenterRow, error) {
	row := q.db.QueryRow(ctx, getOrgRenter, arg.UserID, arg.OrgID)
	var i GetOrgRenterRow
	err := row.Scan(
		&i.UserID,
		&i.Phone,
		&i.Email,
		&i.UserName,
		&i.CreatedAt,
		&i.ProfileName,
		&i.KycStatus,
		&i.KycDocUploaded,
	)
	return i, err
}

const listOrgRenters = `-- name: ListOrgRenters :many

SELECT u.id AS user_id, u.phone, u.email, u.full_name AS user_name, u.created_at,
       COALESCE(rp.full_name, u.full_name)::text AS profile_name,
       COALESCE(rp.kyc_status, 'incomplete')::text AS kyc_status,
       (rp.kyc_doc_object_key IS NOT NULL)::boolean AS kyc_doc_uploaded
FROM users u
JOIN LATERAL (
    SELECT min(seen) AS first_seen FROM (
        SELECT lr.created_at AS seen FROM unit_link_requests lr
        WHERE lr.renter_user_id = u.id AND lr.org_id = $1 AND lr.deleted_at IS NULL
        UNION ALL
        SELECT c.created_at FROM contracts c
        WHERE c.renter_user_id = u.id AND c.org_id = $1 AND c.deleted_at IS NULL
    ) s
) rel ON rel.first_seen IS NOT NULL
LEFT JOIN renter_profiles rp ON rp.user_id = u.id AND rp.deleted_at IS NULL
WHERE u.kind = 'renter' AND u.deleted_at IS NULL
  AND ($2::text IS NULL
       OR u.full_name ILIKE '%' || $2::text || '%'
       OR COALESCE(rp.full_name, '') ILIKE '%' || $2::text || '%'
       OR COALESCE(u.phone, '') ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL
       OR COALESCE(rp.kyc_status, 'incomplete') = $3::text)
  AND ($4::timestamptz IS NULL
       OR (u.created_at, u.id) < ($4::timestamptz, $5::uuid))
ORDER BY u.created_at DESC, u.id DESC
LIMIT $6
`

type ListOrgRentersParams struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	Q         *string            `json:"q"`
	KycStatus *string            `json:"kyc_status"`
	CursorAt  pgtype.Timestamptz `json:"cursor_at"`
	CursorID  pgtype.UUID        `json:"cursor_id"`
	RowLimit  int32              `json:"row_limit"`
}

type ListOrgRentersRow struct {
	UserID         pgtype.UUID        `json:"user_id"`
	Phone          *string            `json:"phone"`
	Email          *string            `json:"email"`
	UserName       string             `json:"user_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ProfileName    string             `json:"profile_name"`
	KycStatus      string             `json:"kyc_status"`
	KycDocUploaded bool               `json:"kyc_doc_uploaded"`
}

// The landlord's renter directory (SPEC §5.4). "A renter this org knows" means
// a renter who has ever made a link request to one of the org's units, or who
// holds a contract with it — nothing else makes a renter visible to an org, so
// these are the queries that decide cross-org visibility.
func (q *Queries) ListOrgRenters(ctx context.Context, arg ListOrgRentersParams) ([]ListOrgRentersRow, error) {
	rows, err := q.db.Query(ctx, listOrgRenters,
		arg.OrgID,
		arg.Q,
		arg.KycStatus,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgRentersRow{}
	for rows.Next() {
		var i ListOrgRentersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Phone,
			&i.Email,
			&i.UserName,
			&i.CreatedAt,
			&i.ProfileName,
			&i.KycStatus,
			&i.KycDocUploaded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenterUnitsForOrg = `-- name: ListRenterUnitsForOrg :many
SELECT lr.unit_id, u.name AS unit_name, p.name AS property_name, lr.status AS link_status
FROM unit_link_requests lr
JOIN units u      ON u.id = lr.unit_id AND u.org_id = lr.org_id
JOIN properties p ON p.id = u.property_id AND p.org_id = lr.org_id
WHERE lr.org_id = $1 AND lr.renter_user_id = $2
  AND lr.deleted_at IS NULL
ORDER BY lr.created_at DESC
`

type ListRenterUnitsForOrgParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	RenterUserID pgtype.UUID `json:"renter_user_id"`
}

type ListRenterUnitsForOrgRow struct {
	UnitID       pgtype.UUID `json:"unit_id"`
	UnitName     string      `json:"unit_name"`
	PropertyName string      `json:"property_name"`
	LinkStatus   string      `json:"link_status"`
}

func (q *Queries) ListRenterUnitsForOrg(ctx context.Context, arg ListRenterUnitsForOrgParams) ([]ListRenterUnitsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listRenterUnitsForOrg, arg.OrgID, arg.RenterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRenterUnitsForOrgRow{}
	for rows.Next() {
		var i ListRenterUnitsForOrgRow
		if err := rows.Scan(
			&i.UnitID,
			&i.UnitName,
			&i.PropertyName,
			&i.LinkStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
