// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports_v2.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const occupancyContractSpans = `-- name: OccupancyContractSpans :many

SELECT c.unit_id,
       c.start_date,
       (CASE WHEN c.status = 'terminated' AND c.termination_effective_date IS NOT NULL
             THEN LEAST(c.end_date, c.termination_effective_date + 1)
             ELSE c.end_date END)::date AS end_date
FROM contracts c
JOIN units u ON u.id = c.unit_id AND u.org_id = c.org_id
WHERE c.org_id = $1 AND c.deleted_at IS NULL
  AND c.status IN ('active', 'expiring', 'ended', 'terminated')
  AND c.start_date < $2
  AND ($3::uuid IS NULL OR u.property_id = $3::uuid)
`

type OccupancyContractSpansParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	ToDate     pgtype.Date `json:"to_date"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type OccupancyContractSpansRow struct {
	UnitID    pgtype.UUID `json:"unit_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

// ----------------------------------------------- GET /reports/occupancy --
// OccupancyContractSpans is every tenancy that could have covered any day of
// the window, as a half-open `[start_date, end_date)` span.
//
// `draft` and `pending_signature` contracts are excluded: nobody has moved in.
// `ended` and `terminated` ones are included, because occupancy is a history —
// a unit that was let in March was let in March whatever happened since. A
// terminated tenancy is occupied through its effective date inclusive, which is
// the same day its remaining schedules stop being waived (FLOWS 6.5), so the
// exclusive end is the day after.
func (q *Queries) OccupancyContractSpans(ctx context.Context, arg OccupancyContractSpansParams) ([]OccupancyContractSpansRow, error) {
	rows, err := q.db.Query(ctx, occupancyContractSpans, arg.OrgID, arg.ToDate, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OccupancyContractSpansRow{}
	for rows.Next() {
		var i OccupancyContractSpansRow
		if err := rows.Scan(&i.UnitID, &i.StartDate, &i.EndDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const occupancyUnitDates = `-- name: OccupancyUnitDates :many
SELECT u.id, u.created_at::date AS created_on
FROM units u
WHERE u.org_id = $1 AND u.deleted_at IS NULL
  AND ($2::uuid IS NULL OR u.property_id = $2::uuid)
`

type OccupancyUnitDatesParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type OccupancyUnitDatesRow struct {
	ID        pgtype.UUID `json:"id"`
	CreatedOn pgtype.Date `json:"created_on"`
}

// OccupancyUnitDates is the denominator's raw material: when each live unit
// came into existence, so a bucket before a unit was created does not count it.
func (q *Queries) OccupancyUnitDates(ctx context.Context, arg OccupancyUnitDatesParams) ([]OccupancyUnitDatesRow, error) {
	rows, err := q.db.Query(ctx, occupancyUnitDates, arg.OrgID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OccupancyUnitDatesRow{}
	for rows.Next() {
		var i OccupancyUnitDatesRow
		if err := rows.Scan(&i.ID, &i.CreatedOn); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportPropertyNames = `-- name: ReportPropertyNames :many
SELECT p.id, p.name
FROM properties p
WHERE p.org_id = $1 AND p.deleted_at IS NULL
  AND ($2::uuid IS NULL OR p.id = $2::uuid)
ORDER BY p.name, p.id
`

type ReportPropertyNamesParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type ReportPropertyNamesRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// ReportPropertyNames is the zero-fill skeleton: every live property of the
// org, in the order the breakdown falls back to when two properties tie.
func (q *Queries) ReportPropertyNames(ctx context.Context, arg ReportPropertyNamesParams) ([]ReportPropertyNamesRow, error) {
	rows, err := q.db.Query(ctx, reportPropertyNames, arg.OrgID, arg.PropertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportPropertyNamesRow{}
	for rows.Next() {
		var i ReportPropertyNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueCollectedByProperty = `-- name: RevenueCollectedByProperty :many


SELECT u.property_id AS property_id,
       COALESCE(sum(p.amount), 0)::bigint AS amount
FROM payments p
JOIN contracts c ON c.id = p.contract_id AND c.org_id = p.org_id
JOIN units u     ON u.id = c.unit_id AND u.org_id = c.org_id
WHERE p.org_id = $1 AND p.deleted_at IS NULL AND p.status <> 'reversed'
  AND p.paid_at >= $2 AND p.paid_at < $3
  AND ($4::uuid IS NULL OR u.property_id = $4::uuid)
GROUP BY 1
`

type RevenueCollectedByPropertyParams struct {
	OrgID      pgtype.UUID        `json:"org_id"`
	FromTs     pgtype.Timestamptz `json:"from_ts"`
	ToTs       pgtype.Timestamptz `json:"to_ts"`
	PropertyID pgtype.UUID        `json:"property_id"`
}

type RevenueCollectedByPropertyRow struct {
	PropertyID pgtype.UUID `json:"property_id"`
	Amount     int64       `json:"amount"`
}

// --------------------------------- GET /reports/revenue?group_by=property --
// The three breakdowns key on property_id; the handler zero-fills them against
// the org's live properties, so a property that earned nothing this month is a
// row of zeroes rather than a gap.
func (q *Queries) RevenueCollectedByProperty(ctx context.Context, arg RevenueCollectedByPropertyParams) ([]RevenueCollectedByPropertyRow, error) {
	rows, err := q.db.Query(ctx, revenueCollectedByProperty,
		arg.OrgID,
		arg.FromTs,
		arg.ToTs,
		arg.PropertyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueCollectedByPropertyRow{}
	for rows.Next() {
		var i RevenueCollectedByPropertyRow
		if err := rows.Scan(&i.PropertyID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueCollectedDaily = `-- name: RevenueCollectedDaily :many


SELECT (p.paid_at AT TIME ZONE 'Africa/Dar_es_Salaam')::date AS day,
       COALESCE(sum(p.amount), 0)::bigint AS amount
FROM payments p
WHERE p.org_id = $1 AND p.deleted_at IS NULL AND p.status <> 'reversed'
  AND p.paid_at >= $2 AND p.paid_at < $3
  AND ($4::uuid IS NULL OR EXISTS (
        SELECT 1 FROM contracts c
        JOIN units u ON u.id = c.unit_id AND u.org_id = c.org_id
        WHERE c.id = p.contract_id AND c.org_id = p.org_id
          AND u.property_id = $4::uuid))
GROUP BY 1
ORDER BY 1
`

type RevenueCollectedDailyParams struct {
	OrgID      pgtype.UUID        `json:"org_id"`
	FromTs     pgtype.Timestamptz `json:"from_ts"`
	ToTs       pgtype.Timestamptz `json:"to_ts"`
	PropertyID pgtype.UUID        `json:"property_id"`
}

type RevenueCollectedDailyRow struct {
	Day    pgtype.Date `json:"day"`
	Amount int64       `json:"amount"`
}

// Phase 11 reports (SPEC §5.9, PLAN2 Phase 11): the revenue series, its
// per-property breakdown, and the occupancy series.
//
// Definitions, shared with the Phase 7 reports so the two never disagree:
//
//	collected = payments with `paid_at` inside the window whose status is not
//	            `reversed`, bucketed on the org's own wall clock.
//	expected  = payment_schedules with `due_date` inside the window, excluding
//	            `waived` rows — which is also how a terminated tenancy's
//	            remaining periods drop out (FLOWS 6.5 waives them).
//	expenses  = expenses with `incurred_on` inside the window and status
//	            `recorded` (a voided row is a correction, not a cost).
//
// Every window here is half-open `[from, to)`, matching internal/period.
//
// The series are read at **day** grain and bucketed in Go rather than with
// `date_trunc`. A custom range may start on the 12th, and internal/period's
// buckets then start on the 12th too; `date_trunc` would align them to the 1st
// and the two would silently disagree about which bucket a row belongs to. A
// five-year window is at most ~1830 rows per series, which is cheaper to carry
// than a bucketing bug.
//
// `property_id` is filtered through EXISTS rather than a join, so the plain
// (unfiltered) call still walks the `(org_id, paid_at)` index alone.
// ------------------------------------------------- GET /reports/revenue --
func (q *Queries) RevenueCollectedDaily(ctx context.Context, arg RevenueCollectedDailyParams) ([]RevenueCollectedDailyRow, error) {
	rows, err := q.db.Query(ctx, revenueCollectedDaily,
		arg.OrgID,
		arg.FromTs,
		arg.ToTs,
		arg.PropertyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueCollectedDailyRow{}
	for rows.Next() {
		var i RevenueCollectedDailyRow
		if err := rows.Scan(&i.Day, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueExpectedByProperty = `-- name: RevenueExpectedByProperty :many
SELECT u.property_id AS property_id,
       COALESCE(sum(s.amount), 0)::bigint AS amount
FROM payment_schedules s
JOIN contracts c ON c.id = s.contract_id AND c.org_id = s.org_id
JOIN units u     ON u.id = c.unit_id AND u.org_id = c.org_id
WHERE s.org_id = $1 AND s.deleted_at IS NULL AND s.status <> 'waived'
  AND s.due_date >= $2 AND s.due_date < $3
  AND ($4::uuid IS NULL OR u.property_id = $4::uuid)
GROUP BY 1
`

type RevenueExpectedByPropertyParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type RevenueExpectedByPropertyRow struct {
	PropertyID pgtype.UUID `json:"property_id"`
	Amount     int64       `json:"amount"`
}

func (q *Queries) RevenueExpectedByProperty(ctx context.Context, arg RevenueExpectedByPropertyParams) ([]RevenueExpectedByPropertyRow, error) {
	rows, err := q.db.Query(ctx, revenueExpectedByProperty,
		arg.OrgID,
		arg.FromDate,
		arg.ToDate,
		arg.PropertyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueExpectedByPropertyRow{}
	for rows.Next() {
		var i RevenueExpectedByPropertyRow
		if err := rows.Scan(&i.PropertyID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueExpectedDaily = `-- name: RevenueExpectedDaily :many
SELECT s.due_date AS day,
       COALESCE(sum(s.amount), 0)::bigint AS amount
FROM payment_schedules s
WHERE s.org_id = $1 AND s.deleted_at IS NULL AND s.status <> 'waived'
  AND s.due_date >= $2 AND s.due_date < $3
  AND ($4::uuid IS NULL OR EXISTS (
        SELECT 1 FROM contracts c
        JOIN units u ON u.id = c.unit_id AND u.org_id = c.org_id
        WHERE c.id = s.contract_id AND c.org_id = s.org_id
          AND u.property_id = $4::uuid))
GROUP BY 1
ORDER BY 1
`

type RevenueExpectedDailyParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type RevenueExpectedDailyRow struct {
	Day    pgtype.Date `json:"day"`
	Amount int64       `json:"amount"`
}

func (q *Queries) RevenueExpectedDaily(ctx context.Context, arg RevenueExpectedDailyParams) ([]RevenueExpectedDailyRow, error) {
	rows, err := q.db.Query(ctx, revenueExpectedDaily,
		arg.OrgID,
		arg.FromDate,
		arg.ToDate,
		arg.PropertyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueExpectedDailyRow{}
	for rows.Next() {
		var i RevenueExpectedDailyRow
		if err := rows.Scan(&i.Day, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueExpensesByProperty = `-- name: RevenueExpensesByProperty :many
SELECT e.property_id AS property_id,
       COALESCE(sum(e.amount), 0)::bigint AS amount
FROM expenses e
WHERE e.org_id = $1 AND e.deleted_at IS NULL AND e.status = 'recorded'
  AND e.incurred_on >= $2 AND e.incurred_on < $3
  AND ($4::uuid IS NULL OR e.property_id = $4::uuid)
GROUP BY 1
`

type RevenueExpensesByPropertyParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type RevenueExpensesByPropertyRow struct {
	PropertyID pgtype.UUID `json:"property_id"`
	Amount     int64       `json:"amount"`
}

func (q *Queries) RevenueExpensesByProperty(ctx context.Context, arg RevenueExpensesByPropertyParams) ([]RevenueExpensesByPropertyRow, error) {
	rows, err := q.db.Query(ctx, revenueExpensesByProperty,
		arg.OrgID,
		arg.FromDate,
		arg.ToDate,
		arg.PropertyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueExpensesByPropertyRow{}
	for rows.Next() {
		var i RevenueExpensesByPropertyRow
		if err := rows.Scan(&i.PropertyID, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueExpensesDaily = `-- name: RevenueExpensesDaily :many
SELECT e.incurred_on AS day,
       COALESCE(sum(e.amount), 0)::bigint AS amount
FROM expenses e
WHERE e.org_id = $1 AND e.deleted_at IS NULL AND e.status = 'recorded'
  AND e.incurred_on >= $2 AND e.incurred_on < $3
  AND ($4::uuid IS NULL OR e.property_id = $4::uuid)
GROUP BY 1
ORDER BY 1
`

type RevenueExpensesDailyParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type RevenueExpensesDailyRow struct {
	Day    pgtype.Date `json:"day"`
	Amount int64       `json:"amount"`
}

func (q *Queries) RevenueExpensesDaily(ctx context.Context, arg RevenueExpensesDailyParams) ([]RevenueExpensesDailyRow, error) {
	rows, err := q.db.Query(ctx, revenueExpensesDaily,
		arg.OrgID,
		arg.FromDate,
		arg.ToDate,
		arg.PropertyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueExpensesDailyRow{}
	for rows.Next() {
		var i RevenueExpensesDailyRow
		if err := rows.Scan(&i.Day, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
