// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upcoming.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMySubmittedProofsBySchedule = `-- name: ListMySubmittedProofsBySchedule :many
SELECT DISTINCT ON (p.schedule_id) p.schedule_id, p.id, p.status
FROM payment_proofs p
WHERE p.renter_user_id = $1
  AND p.status = 'submitted' AND p.schedule_id IS NOT NULL
ORDER BY p.schedule_id, p.created_at DESC, p.id DESC
`

type ListMySubmittedProofsByScheduleRow struct {
	ScheduleID pgtype.UUID `json:"schedule_id"`
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
}

// ListMySubmittedProofsBySchedule is the "Awaiting confirmation" chip on the
// renter's own screens (§16.3): the newest proof still awaiting a decision for
// each instalment they have filed one against.
//
// guard-exempt: renter scope. A proof belongs to the person who filed it and
// the caller is that person; the org it concerns is the row's own fact, not a
// filter the renter's session could supply (the same rule GET /me/payments and
// GET /me/schedules follow).
func (q *Queries) ListMySubmittedProofsBySchedule(ctx context.Context, renterUserID pgtype.UUID) ([]ListMySubmittedProofsByScheduleRow, error) {
	rows, err := q.db.Query(ctx, listMySubmittedProofsBySchedule, renterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMySubmittedProofsByScheduleRow{}
	for rows.Next() {
		var i ListMySubmittedProofsByScheduleRow
		if err := rows.Scan(&i.ScheduleID, &i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitNextDue = `-- name: ListUnitNextDue :many
SELECT DISTINCT ON (c.unit_id)
       c.unit_id, s.due_date
FROM payment_schedules s
JOIN contracts c ON c.id = s.contract_id AND c.org_id = s.org_id
WHERE s.org_id = $1 AND s.deleted_at IS NULL
  AND c.deleted_at IS NULL AND c.status IN ('active', 'expiring')
  AND s.status IN ('pending', 'partial', 'overdue')
ORDER BY c.unit_id, s.due_date, s.id
`

type ListUnitNextDueRow struct {
	UnitID  pgtype.UUID `json:"unit_id"`
	DueDate pgtype.Date `json:"due_date"`
}

// ListUnitNextDue is the units board chip: for each unit with a running
// tenancy, the next date money is owed on it. Units with nothing outstanding
// are absent rather than null — the handler leaves their chip empty.
func (q *Queries) ListUnitNextDue(ctx context.Context, orgID pgtype.UUID) ([]ListUnitNextDueRow, error) {
	rows, err := q.db.Query(ctx, listUnitNextDue, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitNextDueRow{}
	for rows.Next() {
		var i ListUnitNextDueRow
		if err := rows.Scan(&i.UnitID, &i.DueDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingSchedules = `-- name: ListUpcomingSchedules :many

SELECT s.id, s.contract_id, s.period_start, s.period_end, s.due_date,
       s.amount, s.paid_amount, s.status,
       c.renter_user_id,
       ru.full_name AS renter_name, ru.phone AS renter_phone,
       u.name AS unit_name, pr.name AS property_name
FROM payment_schedules s
JOIN contracts c   ON c.id = s.contract_id AND c.org_id = s.org_id
JOIN units u       ON u.id = c.unit_id AND u.org_id = s.org_id
JOIN properties pr ON pr.id = u.property_id AND pr.org_id = s.org_id
JOIN users ru      ON ru.id = c.renter_user_id
WHERE s.org_id = $1 AND s.deleted_at IS NULL
  AND c.deleted_at IS NULL AND c.status IN ('active', 'expiring')
  AND s.status IN ('pending', 'partial', 'overdue')
  AND s.due_date >= $2 AND s.due_date <= $3
  AND ($4::uuid IS NULL OR pr.id = $4::uuid)
ORDER BY s.due_date, u.name, s.id
`

type ListUpcomingSchedulesParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	FromDate   pgtype.Date `json:"from_date"`
	ToDate     pgtype.Date `json:"to_date"`
	PropertyID pgtype.UUID `json:"property_id"`
}

type ListUpcomingSchedulesRow struct {
	ID           pgtype.UUID `json:"id"`
	ContractID   pgtype.UUID `json:"contract_id"`
	PeriodStart  pgtype.Date `json:"period_start"`
	PeriodEnd    pgtype.Date `json:"period_end"`
	DueDate      pgtype.Date `json:"due_date"`
	Amount       int64       `json:"amount"`
	PaidAmount   int64       `json:"paid_amount"`
	Status       string      `json:"status"`
	RenterUserID pgtype.UUID `json:"renter_user_id"`
	RenterName   string      `json:"renter_name"`
	RenterPhone  *string     `json:"renter_phone"`
	UnitName     string      `json:"unit_name"`
	PropertyName string      `json:"property_name"`
}

// Phase 16 §16.3: due-date visibility (PLAN2 Phase 16, API.md Part 2 — Phase 16).
//
// One rule holds across every query here and the Phase 7 report beside it: a
// row is "still owed" when its status is pending, partial or overdue, and what
// it owes is `GREATEST(amount - paid_amount, 0)`. `waived` and `paid` rows are
// not money anybody is waiting for, and a contract that has ended or been
// terminated is not a tenancy the landlord is chasing.
//
// The window is a pair of calendar dates already resolved on the Dar es Salaam
// wall clock by the handler (internal/tz): the database is never asked what
// "today" is, because two callers on either side of 21:00 UTC would get
// different answers to that question.
// ListUpcomingSchedules is GET /reports/upcoming: everything still owed with a
// due date inside the window, oldest first, with the renter and the unit it
// belongs to so the row reads without a second call.
func (q *Queries) ListUpcomingSchedules(ctx context.Context, arg ListUpcomingSchedulesParams) ([]ListUpcomingSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingSchedules,
		arg.OrgID,
		arg.FromDate,
		arg.ToDate,
		arg.PropertyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingSchedulesRow{}
	for rows.Next() {
		var i ListUpcomingSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.DueDate,
			&i.Amount,
			&i.PaidAmount,
			&i.Status,
			&i.RenterUserID,
			&i.RenterName,
			&i.RenterPhone,
			&i.UnitName,
			&i.PropertyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upcomingTotals = `-- name: UpcomingTotals :one
SELECT count(*)::bigint AS row_count,
       COALESCE(sum(GREATEST(s.amount - s.paid_amount, 0)), 0)::bigint AS total_due
FROM payment_schedules s
JOIN contracts c ON c.id = s.contract_id AND c.org_id = s.org_id
WHERE s.org_id = $1 AND s.deleted_at IS NULL
  AND c.deleted_at IS NULL AND c.status IN ('active', 'expiring')
  AND s.status IN ('pending', 'partial', 'overdue')
  AND s.due_date >= $2 AND s.due_date <= $3
`

type UpcomingTotalsParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type UpcomingTotalsRow struct {
	RowCount int64 `json:"row_count"`
	TotalDue int64 `json:"total_due"`
}

// UpcomingTotals is the same window as one aggregate, for the dashboard card:
// the landlord's home screen wants "8 rows, TZS 2,400,000" and must not have to
// download the rows to add them up.
func (q *Queries) UpcomingTotals(ctx context.Context, arg UpcomingTotalsParams) (UpcomingTotalsRow, error) {
	row := q.db.QueryRow(ctx, upcomingTotals, arg.OrgID, arg.FromDate, arg.ToDate)
	var i UpcomingTotalsRow
	err := row.Scan(&i.RowCount, &i.TotalDue)
	return i, err
}
