// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlatformAdmins = `-- name: CountPlatformAdmins :one
SELECT count(*) FROM users WHERE kind = 'platform_admin' AND deleted_at IS NULL
`

func (q *Queries) CountPlatformAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlatformAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (kind, phone, email, full_name, pin_hash, password_hash, email_verified_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, kind, phone, email, full_name, pin_hash, password_hash, email_verified_at, status, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Kind            string             `json:"kind"`
	Phone           *string            `json:"phone"`
	Email           *string            `json:"email"`
	FullName        string             `json:"full_name"`
	PinHash         *string            `json:"pin_hash"`
	PasswordHash    *string            `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
}

// users is a platform-global table (a person may be a renter in one org and
// staff in another), so no org_id scoping applies here.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Kind,
		arg.Phone,
		arg.Email,
		arg.FullName,
		arg.PinHash,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.PinHash,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, kind, phone, email, full_name, pin_hash, password_hash, email_verified_at, status, created_at, updated_at, deleted_at FROM users WHERE lower(email) = lower($1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.PinHash,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, kind, phone, email, full_name, pin_hash, password_hash, email_verified_at, status, created_at, updated_at, deleted_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.PinHash,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, kind, phone, email, full_name, pin_hash, password_hash, email_verified_at, status, created_at, updated_at, deleted_at FROM users WHERE phone = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.PinHash,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :one
UPDATE users SET email_verified_at = COALESCE(email_verified_at, now())
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, kind, phone, email, full_name, pin_hash, password_hash, email_verified_at, status, created_at, updated_at, deleted_at
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markEmailVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.PinHash,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type SetUserPasswordParams struct {
	PasswordHash *string     `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const setUserPin = `-- name: SetUserPin :exec
UPDATE users SET pin_hash = $1 WHERE id = $2
`

type SetUserPinParams struct {
	PinHash *string     `json:"pin_hash"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) SetUserPin(ctx context.Context, arg SetUserPinParams) error {
	_, err := q.db.Exec(ctx, setUserPin, arg.PinHash, arg.ID)
	return err
}
