export {
  FONT_IDS,
  FONT_LABELS,
  PRESET_IDS,
  PRESETS,
  DEFAULT_THEME,
  LEDGER_THEME,
  CONTRAST_PAIRS,
  derivePrimaryTokens,
  deriveTokens,
  themeStyle,
  contrastRatio,
  luminance,
  onPrimary,
  mix,
  isHexColor,
  normalizeHex,
  presetById,
  themeContrastReport,
  validateTheme,
  toResolvedTheme,
  applyOrgTheme,
  resetOrgTheme,
} from './theme';
export type {
  FontId,
  OrgTheme,
  LegacyOrgTheme,
  PresetId,
  ThemeTokens,
  ResolvedTheme,
  ThemePreset,
  ThemeFailure,
  CssVars,
} from './theme';
export { ThemeSwitcher } from './ThemeSwitcher';
export { TableScroll } from './TableScroll';
export { PeriodPicker } from './PeriodPicker';
export type { PeriodPickerProps } from './PeriodPicker';
export {
  CADENCES,
  CADENCE_LABELS,
  addDays,
  daysBetween,
  formatDate,
  parseDate,
  periodLabel,
  resolvePeriod,
  shiftPeriod,
  today,
} from './period';
export type { Cadence, PeriodValue } from './period';

/* Charts (phase 11) — inline SVG, no chart library. See charts/index.ts. */
export {
  LineAreaChart,
  BarChart,
  Sparkline,
  StatTile,
  ChangeMark,
  RowBar,
  Legend,
  LegendKey,
  ChartFrame,
  ChartTooltip,
  HoverLayer,
  useChartWidth,
  GridLines,
  XTicks,
  PAD,
  CHART_SLOTS,
  CHART_ROLES,
  compactNumber,
  compactTZS,
  fullTZS,
  pctLabel,
  changeLabel,
  bucketTick,
  bucketHeading,
  tickStride,
  linearScale,
  niceDomain,
  bands,
  nearestIndex,
  linePath,
  areaPath,
} from './charts';
export type {
  LineAreaChartProps,
  LineSeries,
  BarChartProps,
  BarSeries,
  SparklineProps,
  StatTileProps,
  GoodDirection,
  LegendItem,
  LegendShape,
  TooltipRow,
  Bucket,
  LinearScale,
  NiceDomain,
  Band,
} from './charts';
