// Phase 30 — a backfill that reaches back records an OFFLINE CONTRACT.
//
// Phase 29 put the periods before the start date on the running contract. That
// made the running contract lie about its own start, so a backfill given `from`
// now writes what actually happened: a separate contract for the real renter
// and unit, from the real move-in to the last covered day, marked
// `is_offline`, status `ended`, never signed and never issued. Its periods are
// generated by the same generator, owned by the batch and settled exactly as a
// running contract's are.
//
// Nothing about it can be acted on afterwards — no signing, renewing,
// amending, terminating — and everything that shows it says so.
package httpserver

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/jackc/pgx/v5/pgtype"

	"tms/backend/internal/audit"
	"tms/backend/internal/contract"
	"tms/backend/internal/db"
	"tms/backend/internal/db/sqlc"
	"tms/backend/internal/validate"
)

// offlineDefaultCadenceDays is the payment cadence of an offline contract when
// the unit has no running contract to inherit one from.
const offlineDefaultCadenceDays = 30

// offlineNoticeEN / offlineNoticeSW are the whole "terms" of an offline
// contract: a statement of what it is, in the org's language. There is no
// template, no snapshot hash and no signature.
const (
	offlineNoticeEN = "<p><strong>Offline contract.</strong> Recorded from the landlord's paper records. " +
		"This contract was never signed or issued in TMS and has no document to sign.</p>"
	offlineNoticeSW = "<p><strong>Mkataba wa nje ya mfumo.</strong> Umeandikwa kutoka kwenye kumbukumbu za karatasi " +
		"za mwenye nyumba. Mkataba huu haukusainiwa wala kutolewa kupitia TMS, na hauna hati ya kusaini.</p>"
)

// offlineNotice is the fixed text for a language ('sw' unless 'en').
func offlineNotice(lang string) string {
	if lang == "en" {
		return offlineNoticeEN
	}
	return offlineNoticeSW
}

// refuseOffline answers 409 for an action that makes no sense on an offline
// contract (sign, renew, amend, terminate, ...). True when it refused.
func refuseOffline(w http.ResponseWriter, isOffline bool) bool {
	if !isOffline {
		return false
	}
	conflictCode(w, "offline_contract", "offline contract",
		"this is an offline contract recorded from paper records; it was never issued in TMS "+
			"and cannot be signed, renewed, amended or terminated")
	return true
}

// loadActionableContract is loadContract for the routes that change a
// contract's state: it refuses an offline one.
func (s *Server) loadActionableContract(w http.ResponseWriter, r *http.Request) (sqlc.GetContractRow, bool) {
	row, ok := s.loadContract(w, r)
	if !ok {
		return row, false
	}
	if refuseOffline(w, row.IsOffline) {
		return row, false
	}
	return row, true
}

// overlapInfo names the contract an offline stretch would run into.
type overlapInfo struct {
	Start, End time.Time // End is the last covered day, inclusive
	Offline    bool
}

func (o overlapInfo) message() string {
	kind := "contract"
	if o.Offline {
		kind = "offline contract"
	}
	return fmt.Sprintf("overlaps another %s on this unit (%s to %s)",
		kind, o.Start.Format(dateLayout), o.End.Format(dateLayout))
}

// planError is what planOffline returns instead of a plan: field problems
// (422 / a row error) or a clash with another contract (409 / a row error on
// `from`). Neither wrote anything.
type planError struct {
	Fields   validate.Fields
	Conflict *overlapInfo
}

func (e *planError) Error() string { return "backfill: offline contract refused" }

// offlinePlanInput is everything planOffline decides from.
type offlinePlanInput struct {
	OrgID        pgtype.UUID
	UnitID       pgtype.UUID
	RenterUserID pgtype.UUID
	Settings     OrgSettings
	// UnitRunning is the contract running on the unit, whoever the renter;
	// the offline stretch must end the day before it starts.
	UnitRunning *sqlc.GetContractRow
	From        time.Time
	Until       time.Time
	// PeriodAmount is the rent per payment period, 0 to take the renter's own
	// running contract's.
	PeriodAmount int64
	// Amount, when set, is the total paid for the whole stretch (Phase 32):
	// the offline contract is one period for exactly this sum.
	Amount int64
	// LaterStarts are the `from` dates of other lines of the same sheet for
	// this unit, which the preview has to floor against before any of them
	// is written (Phase 32). The commit writes later lines first, so the
	// database answers instead.
	LaterStarts []time.Time
}

// offlinePlan is a validated offline contract, not yet written.
type offlinePlan struct {
	From, End    time.Time // both inclusive: End is the last covered day
	TermDays     int
	PeriodAmount int64
	CadenceDays  int
	// CadenceMonths is set when the cadence is a calendar period.
	CadenceMonths   *int32
	PaymentPeriodID pgtype.UUID
	DueDay          *int32
	Language        string
	Rows            []contract.Row
}

// planOffline validates the stretch and generates its periods. It writes
// nothing, so the CSV preview and the transaction share it.
func (s *Server) planOffline(ctx context.Context, q *sqlc.Queries, in offlinePlanInput) (*offlinePlan, error) {
	f := validate.Fields{}
	today := todayEAT()
	if in.Until.Before(in.From) {
		f.Add("until", "must not be before from ("+in.From.Format(dateLayout)+")")
	}
	if in.From.Before(today.AddDate(0, 0, -contractStartBackstopDays)) {
		f.Add("from", "must be at most 10 years ago")
	}
	end := in.Until
	if run := in.UnitRunning; run != nil {
		start := run.StartDate.Time
		if !in.From.Before(start) {
			f.Add("from", "the offline stretch would overlap the running contract that starts "+
				start.Format(dateLayout))
		} else if last := start.AddDate(0, 0, -1); last.Before(end) {
			end = last
		}
	}
	// Phase 32 — the floor: any contract of the unit that starts inside the
	// stretch (a finished TMS contract, another offline one, or another line
	// of this sheet) keeps its start date, and the stretch ends the day before.
	if f.Empty() {
		next, err := q.FindNextContractStart(ctx, sqlc.FindNextContractStartParams{
			OrgID: in.OrgID, UnitID: in.UnitID,
			FromDate: pgtype.Date{Time: in.From, Valid: true},
			LastDay:  pgtype.Date{Time: end, Valid: true},
		})
		if err != nil && !isNoRows(err) {
			return nil, err
		}
		if next.Valid {
			end = next.Time.AddDate(0, 0, -1)
		}
		for _, later := range in.LaterStarts {
			if later.After(in.From) && !later.After(end) {
				end = later.AddDate(0, 0, -1)
			}
		}
	}
	// Only after the floor: a stretch that would run past today is fine when
	// a contract already in TMS cuts it off first.
	if end.After(today) {
		f.Add("until", "must not be in the future (nothing in TMS starts before it to end the stretch)")
	}
	if in.Amount > 0 && in.PeriodAmount > 0 {
		f.Add("amount", "give amount or period_amount, not both")
	}
	// The renter's own running contract gives the default rent.
	amount := in.PeriodAmount
	if in.Amount > 0 {
		amount = in.Amount
	}
	if amount <= 0 {
		if run := in.UnitRunning; run != nil && run.RenterUserID == in.RenterUserID {
			amount = backfillDefaultPeriodAmount(*run)
		} else {
			f.Add("period_amount", "required when the renter has no running contract on this unit")
		}
	}
	if !f.Empty() {
		return nil, &planError{Fields: f}
	}

	plan := &offlinePlan{
		From: in.From, End: end, PeriodAmount: amount,
		CadenceDays: offlineDefaultCadenceDays, Language: in.Settings.SMSLanguage,
	}
	if plan.Language != "en" {
		plan.Language = "sw"
	}
	if run := in.UnitRunning; run != nil {
		plan.CadenceDays = int(run.PaymentPeriodDays)
		plan.CadenceMonths = run.PaymentPeriodMonths
		plan.PaymentPeriodID = run.PaymentPeriodID
		plan.DueDay = run.DueDay
		if run.Language == "en" || run.Language == "sw" {
			plan.Language = run.Language
		}
	} else {
		if in.Settings.DueDay != nil {
			d := int32(*in.Settings.DueDay)
			plan.DueDay = &d
		}
		per, err := q.GetRecommendedPaymentPeriodByDays(ctx, sqlc.GetRecommendedPaymentPeriodByDaysParams{
			OrgID: in.OrgID, Days: offlineDefaultCadenceDays,
		})
		if err != nil && !isNoRows(err) {
			return nil, err
		}
		if err == nil {
			plan.PaymentPeriodID = per.ID
			plan.CadenceMonths = per.Months
		}
	}
	plan.TermDays = int(end.Sub(in.From).Hours()/24) + 1
	if in.Amount > 0 {
		// Phase 32: one line is one paper payment — one period spanning the
		// whole stretch, for the whole sum, due on its first day. The cadence
		// is the stretch itself, so nothing about it repeats.
		plan.CadenceDays, plan.CadenceMonths, plan.DueDay = plan.TermDays, nil, nil
		plan.PaymentPeriodID = pgtype.UUID{}
		plan.Rows = []contract.Row{{
			PeriodStart: in.From, PeriodEnd: end, DueDate: in.From,
			Days: plan.TermDays, Amount: in.Amount,
		}}
	} else {
		// amount is one period's rent, so the cadence is its own basis.
		plan.Rows = contract.GenerateCadence(int(amount), plan.CadenceDays, plan.TermDays,
			cadenceOf(int32(plan.CadenceDays), plan.CadenceMonths), in.From, intPtr(plan.DueDay))
	}

	// A clash with anything else on the unit: 409, naming it.
	clash, err := q.FindOverlappingContract(ctx, sqlc.FindOverlappingContractParams{
		OrgID: in.OrgID, UnitID: in.UnitID,
		ToExcl:   pgtype.Date{Time: end.AddDate(0, 0, 1), Valid: true},
		FromDate: pgtype.Date{Time: in.From, Valid: true},
	})
	if err == nil {
		return nil, &planError{Conflict: &overlapInfo{
			Start: clash.StartDate.Time, End: clash.EndDate.Time.AddDate(0, 0, -1), Offline: clash.IsOffline,
		}}
	}
	if !isNoRows(err) {
		return nil, err
	}
	return plan, nil
}

// createOfflineContract writes the ended, never-signed contract of a plan.
func (s *Server) createOfflineContract(
	ctx context.Context, q *sqlc.Queries, req backfillRequest, plan *offlinePlan,
) (sqlc.Contract, error) {
	yes := true
	lang := plan.Language
	return q.CreateContract(ctx, sqlc.CreateContractParams{
		OrgID: req.OrgID, UnitID: req.Party.UnitID, RenterUserID: req.Party.RenterUserID,
		TermsSnapshotHtml: offlineNotice(plan.Language),
		RentAmount:        plan.PeriodAmount, RentPeriodDays: int32(plan.CadenceDays),
		PaymentPeriodID: plan.PaymentPeriodID, PaymentPeriodDays: int32(plan.CadenceDays),
		PaymentPeriodMonths: plan.CadenceMonths,
		TermDays:            int32(plan.TermDays),
		StartDate:           pgtype.Date{Time: plan.From, Valid: true},
		EndDate:             pgtype.Date{Time: contract.EndDate(plan.From, plan.TermDays), Valid: true},
		DueDay:              plan.DueDay, Status: contractEnded, Language: &lang, IsOffline: &yes,
	})
}

// createOfflineSchedules writes the plan's periods, owned by the batch.
func (s *Server) createOfflineSchedules(
	ctx context.Context, q *sqlc.Queries, req backfillRequest, plan *offlinePlan,
	contractID, batchID pgtype.UUID,
) error {
	for _, r := range plan.Rows {
		if _, err := q.CreateOfflineSchedule(ctx, sqlc.CreateOfflineScheduleParams{
			OrgID: req.OrgID, ContractID: contractID,
			PeriodStart: pgtype.Date{Time: r.PeriodStart, Valid: true},
			PeriodEnd:   pgtype.Date{Time: r.PeriodEnd, Valid: true},
			DueDate:     pgtype.Date{Time: r.DueDate, Valid: true}, Amount: r.Amount,
			CreatedByBackfillID: batchID,
		}); err != nil {
			return err
		}
	}
	return nil
}

// auditOfflineContract is the `contract.create` row of the offline contract.
func (s *Server) auditOfflineContract(
	ctx context.Context, q *sqlc.Queries, req backfillRequest, c sqlc.Contract, plan *offlinePlan,
) error {
	return audit.Record(ctx, q, audit.Entry{
		OrgID:       db.UUIDString(req.OrgID),
		ActorUserID: db.UUIDString(req.ActorUserID),
		Action:      audit.ActionContractCreate,
		EntityType:  audit.EntityContract,
		EntityID:    db.UUIDString(c.ID),
		After: map[string]any{
			"offline": true, "status": contractEnded,
			"start_date": plan.From.Format(dateLayout), "end": plan.End.Format(dateLayout),
			"rent_per_period": plan.PeriodAmount, "periods": len(plan.Rows),
		},
	})
}
